package android.os.statsd.privatespace;

public final class PrivateSpaceProtoEnums {
    public static final int TRANSFER_RESULT_UNKNOWN = 0;
    public static final int TRANSFER_RESULT_SUCCESS = 1;
    public static final int TRANSFER_RESULT_FAILURE = 2;
    public static final int TTRANSFER_RESULT_PARTIAL_SUCCESS = 3;
    public static final int OPERATION_UNKNOWN = 0;
    public static final int OPERATION_MOVE = 1;
    public static final int OPERATION_COPY = 2;
    public static final int OPERATION_CANCEL_BY_USER = 3;
    public static final int OPERATION_DIALOG_DISMISSED = 4;
    public static final int TRANSFER_ERROR_UNKNOWN = 0;
    public static final int TRANSFER_ERROR_ANOTHER_TRANSFER_IN_PROGRESS = 1;
    public static final int TRANSFER_ERROR_ABOVE_FILE_SIZE_LIMITS = 2;
    public static final int TRANSFER_ERROR_TOO_MANY_FILES_SELECTED = 3;
    public static final int TRANSFER_ERROR_ABOVE_AVAILABLE_DEVICE_STORAGE = 4;
    public static final int TRANSFER_ERROR_NOT_ENOUGH_SPACE = 5;
    public static final int TRANSFER_ERROR_CALCULATE_FILE_SIZE = 101;
    public static final int TRANSFER_ERROR_GET_METADATA = 102;
    public static final int TRANSFER_ERROR_CREATE_NEW_MEDIA_ENTRY = 103;
    public static final int TRANSFER_ERROR_GET_FILE_NAME = 104;
    public static final int TRANSFER_ERROR_QUERY_URI = 105;
    public static final int TRANSFER_ERROR_OPEN_OUTPUT_STREAM = 106;
    public static final int TRANSFER_ERROR_OPEN_INPUT_STREAM = 107;
    public static final int TRANSFER_ERROR_COPY_FILE = 108;
    public static final int TRANSFER_ERROR_REMOVE_ORIGINAL_FILE = 109;
    public static final int FILE_SIZE_UNKNOWN = 0;
    public static final int FILE_SIZE_0_TO_1_KB = 1;
    public static final int FILE_SIZE_1_TO_10_KB = 2;
    public static final int FILE_SIZE_10_TO_100_KB = 3;
    public static final int FILE_SIZE_100_TO_500_KB = 4;
    public static final int FILE_SIZE_500_KB_TO_1_MB = 5;
    public static final int FILE_SIZE_1_TO_10_MB = 6;
    public static final int FILE_SIZE_10_TO_100_MB = 7;
    public static final int FILE_SIZE_100_TO_500_MB = 8;
    public static final int FILE_SIZE_500_MB_TO_1_GB = 9;
    public static final int FILE_SIZE_1_TO_2_GB = 10;
    public static final int FILE_SIZE_MORE_THAN_2_GB = 11;
    public static final int MIME_TYPE_CATEGORY_UNKNOWN = 0;
    public static final int MIME_TYPE_CATEGORY_IMAGE = 1;
    public static final int MIME_TYPE_CATEGORY_VIDEO = 2;
    public static final int MIME_TYPE_CATEGORY_AUDIO = 3;
    public static final int MIME_TYPE_CATEGORY_APPLICATION = 4;
    public static final int MIME_TYPE_CATEGORY_PDF = 5;
    public static final int MIME_TYPE_CATEGORY_TEXT = 6;
    public static final int MIME_TYPE_CATEGORY_GENERIC_OCTET_STREAM = 7;
    public static final int MIME_TYPE_CATEGORY_OTHERS = 8;
    public static final int NOTIFICATION_EVENT_TYPE_UNKNOWN = 0;
    public static final int NOTIFICATION_EVENT_TYPE_SHOW_FILES_CLICK = 1;
    public static final int ADD_BUTTON_CLICK_UNKNOWN = 0;
    public static final int ADD_BUTTON_CLICK_OPEN_MARKET_APP_SHORTCUT = 1;
    public static final int ADD_BUTTON_CLICK_MOVE_FILES_SHORTCUT = 2;
    public PrivateSpaceProtoEnums() {}
}
