package android.app.admin.flags;

public interface FeatureFlags {
    public boolean allowQueryingProfileType();
    public boolean allowScreenBrightnessControlOnCope();
    public boolean alwaysPersistDo();
    public boolean assistContentUserRestrictionEnabled();
    public boolean backupConnectedAppsSettings();
    public boolean backupServiceSecurityLogEventEnabled();
    public boolean coexistenceMigrationForNonEmmManagementEnabled();
    public boolean copyAccountWithRetryEnabled();
    public boolean crossUserSuspensionEnabledRo();
    public boolean dedicatedDeviceControlApiEnabled();
    public boolean dedicatedDeviceControlEnabled();
    public boolean defaultSmsPersonalAppSuspensionFixEnabled();
    public boolean deletePrivateSpaceUnderRestriction();
    public boolean devicePolicySizeTrackingEnabled();
    public boolean devicePolicySizeTrackingInternalBugFixEnabled();
    public boolean devicePolicySizeTrackingInternalEnabled();
    public boolean deviceTheftApiEnabled();
    public boolean deviceTheftImplEnabled();
    public boolean disallowUserControlBgUsageFix();
    public boolean disallowUserControlStoppedStateFix();
    public boolean dmrhSetAppRestrictions();
    public boolean dumpsysPolicyEngineMigrationEnabled();
    public boolean esimManagementEnabled();
    public boolean esimManagementUxEnabled();
    public boolean headlessDeviceOwnerDelegateSecurityLoggingBugFix();
    public boolean headlessDeviceOwnerProvisioningFixEnabled();
    public boolean headlessDeviceOwnerSingleUserEnabled();
    public boolean headlessSingleMinTargetSdk();
    public boolean headlessSingleUserBadDeviceAdminStateFix();
    public boolean headlessSingleUserCompatibilityFix();
    public boolean headlessSingleUserFixes();
    public boolean hsumUnlockNotificationFix();
    public boolean isMtePolicyEnforced();
    public boolean isRecursiveRequiredAppMergingEnabled();
    public boolean onboardingBugreportStorageBugFix();
    public boolean onboardingBugreportV2Enabled();
    public boolean onboardingConsentlessBugreports();
    public boolean permissionMigrationForZeroTrustApiEnabled();
    public boolean permissionMigrationForZeroTrustImplEnabled();
    public boolean policyEngineMigrationV2Enabled();
    public boolean powerExemptionBgUsageFix();
    public boolean quietModeCredentialBugFix();
    public boolean securityLogV2Enabled();
    public boolean unmanagedModeMigration();
}
