package android.app.personalcontext.insight;

public final class InsightCreator {
    private InsightCreator() {}
    public static android.app.personalcontext.insight.ActionableInsight createActionableInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, android.app.personalcontext.insight.InsightActionDetails p1, android.app.personalcontext.insight.InsightDisplayDetails p2) { return null; }
    public static android.app.personalcontext.insight.AugmentedAutofillInsight createAugmentedAutofillInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, java.util.List<android.app.personalcontext.insight.AugmentedAutofillOptionInsight> p1) { return null; }
    public static android.app.personalcontext.insight.AugmentedAutofillOptionInsight createAugmentedAutofillOptionInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, android.app.personalcontext.insight.InsightDisplayDetails p1, java.util.List<java.lang.String> p2) { return null; }
    public static android.app.personalcontext.insight.BundleInsight createBundleInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, java.lang.String p1, android.os.Bundle p2) { return null; }
    public static android.app.personalcontext.insight.ContextInsight.ConstructorParams createConstructorParams(java.util.UUID p0, java.util.Collection<android.app.personalcontext.hint.PublishedContextHint> p1, java.util.Collection<android.app.personalcontext.Token> p2, java.time.Instant p3, android.app.personalcontext.insight.InsightBranding p4, android.app.personalcontext.insight.interaction.AttributionDetails p5, java.util.UUID p6, java.time.Instant p7) { return null; }
    public static android.app.personalcontext.insight.DisplayInsight createDisplayInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, android.app.personalcontext.insight.InsightDisplayDetails p1) { return null; }
    public static android.app.personalcontext.insight.HintInvalidationInsight createHintInvalidationInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0) { return null; }
    public static android.app.personalcontext.insight.InsightCollection createInsightCollection(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, java.util.Collection<android.app.personalcontext.insight.ContextInsight> p1) { return null; }
    public static android.app.personalcontext.insight.ListInsight createListInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, java.util.List<android.app.personalcontext.insight.ContextInsight> p1) { return null; }
    public static android.app.personalcontext.insight.MapInsight createMapInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, java.util.Map<java.lang.String, android.app.personalcontext.insight.ContextInsight> p1) { return null; }
    public static android.app.personalcontext.insight.NoResultInsight createNoResultInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0) { return null; }
    public static android.app.personalcontext.insight.NotificationInsight createNotificationInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, java.util.List<android.app.personalcontext.insight.ContextInsight> p1) { return null; }
    public static android.app.personalcontext.insight.PromptInsight createPromptInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, android.app.personalcontext.insight.InsightDisplayDetails p1, int p2, android.app.PendingIntent p3) { return null; }
    public static android.app.personalcontext.insight.ScreenWhisperAutofillInsight createScreenWhisperAutofillInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, android.app.personalcontext.insight.ContextInsight p1) { return null; }
    public static android.app.personalcontext.insight.ScreenWhisperInsight createScreenWhisperInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, android.app.personalcontext.insight.ContextInsight p1) { return null; }
    public static android.app.personalcontext.insight.TextClassificationInsight createTextClassificationInsight(android.app.personalcontext.insight.ContextInsight.ConstructorParams p0, android.app.personalcontext.insight.InsightActionDetails p1, android.app.personalcontext.insight.InsightDisplayDetails p2) { return null; }
}
