package android.security;

public interface FeatureFlags {
    public boolean aapmApi();
    public boolean aapmFeatureDisableCellular2g();
    public boolean aapmFeatureDisableInstallUnknownSources();
    public boolean aapmFeatureMemoryTaggingExtension();
    public boolean aapmFeatureUsbDataProtection();
    public boolean aflApi();
    public boolean asmOptSystemIntoEnforcement();
    public boolean asmReintroduceGracePeriod();
    public boolean asmRestrictionsEnabled();
    public boolean asmRestrictionsV2();
    public boolean asmToastsEnabled();
    public boolean blockNullActionIntents();
    public boolean certificateTransparencyConfiguration();
    public boolean contentUriPermissionApis();
    public boolean disableAdaptiveAuthCounterLock();
    public boolean enableIntentMatchingFlags();
    public boolean enforceIntentFilterMatch();
    public boolean extendEcmToAllSettings();
    public boolean failedAuthLockToggle();
    public boolean frpEnforcement();
    public boolean fsverityApi();
    public boolean implicitUriGrantsRestrictedForSendAction();
    public boolean implicitUriGrantsRestrictedForSendmultipleImagecaptureActions();
    public boolean internalLogEventListener();
    public boolean keyinfoUnlockedDeviceRequired();
    public boolean keystoreGrantApi();
    public boolean mgf1DigestSetterV2();
    public boolean preventIntentRedirect();
    public boolean preventIntentRedirectAbortOrThrowException();
    public boolean preventIntentRedirectCollectNestedKeysOnServerIfNotCollected();
    public boolean preventIntentRedirectShowToast();
    public boolean preventIntentRedirectShowToastIfNestedKeysNotCollectedRW();
    public boolean preventIntentRedirectThrowExceptionIfNestedKeysNotCollected();
    public boolean protectDeviceConfigFlags();
    public boolean secureLockDevice();
    public boolean secureLockdown();
    public boolean shouldTrustManagerListenForPrimaryAuth();
    public boolean softwareRatelimiter();
    public boolean subscribeToKeyguardLockedStatePermPrivFlag();
    public boolean unlockedStorageApi();
}
