package android.app;

public abstract class ActivityManagerInternal {
    public static final int ALLOW_NON_FULL = 0;
    public static final int ALLOW_NON_FULL_IN_PROFILE = 1;
    public static final int ALLOW_FULL_ONLY = 2;
    public static final int ALLOW_ALL_PROFILE_PERMISSIONS_IN_PROFILE = 3;
    public ActivityManagerInternal() {}
    public abstract java.lang.String checkContentProviderAccess(java.lang.String p0, int p1);
    public abstract int checkContentProviderUriPermission(android.net.Uri p0, int p1, int p2, int p3);
    public abstract void onWakefulnessChanged(int p0);
    public abstract boolean startIsolatedProcess(java.lang.String p0, java.lang.String[] p1, java.lang.String p2, java.lang.String p3, int p4, java.lang.Runnable p5);
    public abstract void onUserRemoved(int p0);
    public abstract void killForegroundAppsForUser(int p0);
    public abstract void setPendingIntentAllowlistDuration(android.content.IIntentSender p0, android.os.IBinder p1, long p2, int p3, int p4, java.lang.String p5);
    public abstract int getPendingIntentFlags(android.content.IIntentSender p0);
    public abstract void setPendingIntentAllowBgActivityStarts(android.content.IIntentSender p0, android.os.IBinder p1, int p2);
    public abstract void clearPendingIntentAllowBgActivityStarts(android.content.IIntentSender p0, android.os.IBinder p1);
    public abstract void setDeviceIdleAllowlist(int[] p0, int[] p1);
    public abstract void updateDeviceIdleTempAllowlist(int[] p0, int p1, boolean p2, long p3, int p4, int p5, java.lang.String p6, int p7);
    public abstract int getUidProcessState(int p0);
    public abstract java.util.Map<java.lang.Integer, java.lang.String> getProcessesWithPendingBindMounts(int p0);
    public abstract boolean isSystemReady();
    public abstract void setHasOverlayUi(int p0, boolean p1);
    public abstract void notifyNetworkPolicyRulesUpdated(int p0, long p1);
    public abstract boolean isRuntimeRestarted();
    public abstract boolean canStartMoreUsers();
    public abstract void setSwitchingFromSystemUserMessage(java.lang.String p0);
    public abstract void setSwitchingToSystemUserMessage(java.lang.String p0);
    public abstract int getMaxRunningUsers();
    public abstract boolean isUidActive(int p0);
    public abstract java.util.List<android.app.ProcessMemoryState> getMemoryStateForProcesses();
    public abstract int handleIncomingUser(int p0, int p1, int p2, boolean p3, int p4, java.lang.String p5, java.lang.String p6);
    public abstract void enforceCallingPermission(java.lang.String p0, java.lang.String p1);
    public abstract int getCurrentUserId();
    public abstract int[] getStartedUserIds();
    public abstract boolean isUserRunning(int p0, int p1);
    public abstract void trimApplications();
    public abstract void killProcessesForRemovedTask(java.util.ArrayList<java.lang.Object> p0);
    public abstract void killProcess(java.lang.String p0, int p1, java.lang.String p2);
    public abstract boolean hasRunningActivity(int p0, java.lang.String p1);
    public abstract void updateOomAdj();
    public abstract void updateCpuStats();
    public abstract void updateBatteryStats(android.content.ComponentName p0, int p1, int p2, boolean p3);
    public abstract void updateActivityUsageStats(android.content.ComponentName p0, int p1, int p2, android.os.IBinder p3, android.content.ComponentName p4);
    public abstract void updateForegroundTimeIfOnBattery(java.lang.String p0, int p1, long p2);
    public abstract void sendForegroundProfileChanged(int p0);
    public abstract boolean shouldConfirmCredentials(int p0);
    public abstract void noteAlarmFinish(android.app.PendingIntent p0, android.os.WorkSource p1, int p2, java.lang.String p3);
    public abstract void noteAlarmStart(android.app.PendingIntent p0, android.os.WorkSource p1, int p2, java.lang.String p3);
    public abstract void noteWakeupAlarm(android.app.PendingIntent p0, android.os.WorkSource p1, int p2, java.lang.String p3, java.lang.String p4);
    public abstract boolean isAppStartModeDisabled(int p0, java.lang.String p1);
    public abstract int[] getCurrentProfileIds();
    public abstract android.content.pm.UserInfo getCurrentUser();
    public abstract void ensureNotSpecialUser(int p0);
    public abstract boolean isCurrentProfile(int p0);
    public abstract boolean hasStartedUserState(int p0);
    public abstract void finishUserSwitch(java.lang.Object p0);
    public abstract void scheduleAppGcs();
    public abstract int getTaskIdForActivity(android.os.IBinder p0, boolean p1);
    public abstract android.content.pm.ActivityPresentationInfo getActivityPresentationInfo(android.os.IBinder p0);
    public abstract void setBooting(boolean p0);
    public abstract boolean isBooting();
    public abstract void setBooted(boolean p0);
    public abstract boolean isBooted();
    public abstract void finishBooting();
    public abstract void tempAllowlistForPendingIntent(int p0, int p1, int p2, long p3, int p4, int p5, java.lang.String p6);
    public abstract int broadcastIntentInPackage(java.lang.String p0, java.lang.String p1, int p2, int p3, int p4, android.content.Intent p5, java.lang.String p6, android.content.IIntentReceiver p7, int p8, java.lang.String p9, android.os.Bundle p10, java.lang.String p11, android.os.Bundle p12, boolean p13, boolean p14, int p15, boolean p16, android.os.IBinder p17);
    public abstract android.content.ComponentName startServiceInPackage(int p0, android.content.Intent p1, java.lang.String p2, boolean p3, java.lang.String p4, java.lang.String p5, int p6, boolean p7, android.os.IBinder p8) throws android.os.TransactionTooLargeException;
    public abstract void disconnectActivityFromServices(java.lang.Object p0);
    public abstract void cleanUpServices(int p0, android.content.ComponentName p1, android.content.Intent p2);
    public abstract android.content.pm.ActivityInfo getActivityInfoForUser(android.content.pm.ActivityInfo p0, int p1);
    public abstract void ensureBootCompleted();
    public abstract void updateOomLevelsForDisplay(int p0);
    public abstract boolean isActivityStartsLoggingEnabled();
    public abstract boolean isBackgroundActivityStartsEnabled();
    public abstract void reportCurKeyguardUsageEvent(boolean p0);
    public abstract void monitor();
    public abstract long inputDispatchingTimedOut(int p0, boolean p1, java.lang.String p2);
    public abstract boolean inputDispatchingTimedOut(java.lang.Object p0, java.lang.String p1, android.content.pm.ApplicationInfo p2, java.lang.String p3, java.lang.Object p4, boolean p5, java.lang.String p6);
    public abstract void inputDispatchingResumed(int p0);
    public abstract void broadcastGlobalConfigurationChanged(int p0, boolean p1);
    public abstract void broadcastCloseSystemDialogs(java.lang.String p0);
    public abstract void killAllBackgroundProcessesExcept(int p0, int p1);
    public abstract void startProcess(java.lang.String p0, android.content.pm.ApplicationInfo p1, boolean p2, boolean p3, java.lang.String p4, android.content.ComponentName p5);
    public abstract void setDebugFlagsForStartingActivity(android.content.pm.ActivityInfo p0, int p1, android.app.ProfilerInfo p2, java.lang.Object p3);
    public abstract int getStorageMountMode(int p0, int p1);
    public abstract boolean isAppForeground(int p0);
    public abstract boolean isAppBad(java.lang.String p0, int p1);
    public abstract void clearPendingBackup(int p0);
    public abstract void prepareForPossibleShutdown();
    public abstract boolean hasRunningForegroundService(int p0, int p1);
    public abstract boolean hasForegroundServiceNotification(java.lang.String p0, int p1, java.lang.String p2);
    public abstract android.app.ActivityManagerInternal.ServiceNotificationPolicy applyForegroundServiceNotification(android.app.Notification p0, java.lang.String p1, int p2, java.lang.String p3, int p4);
    public abstract void onForegroundServiceNotificationUpdate(boolean p0, android.app.Notification p1, int p2, java.lang.String p3, int p4);
    public abstract void stopForegroundServicesForChannel(java.lang.String p0, int p1, java.lang.String p2);
    public abstract void registerProcessObserver(android.app.IProcessObserver p0);
    public abstract void unregisterProcessObserver(android.app.IProcessObserver p0);
    public abstract boolean isUidCurrentlyInstrumented(int p0);
    public abstract boolean isDeviceOwner(int p0);
    public abstract void setDeviceOwnerUid(int p0);
    public abstract boolean isProfileOwner(int p0);
    public abstract void setProfileOwnerUid(android.util.ArraySet<java.lang.Integer> p0);
    public abstract void setCompanionAppUids(int p0, java.util.Set<java.lang.Integer> p1);
    public abstract boolean isAssociatedCompanionApp(int p0, int p1);
    public abstract int broadcastIntent(android.content.Intent p0, android.content.IIntentReceiver p1, java.lang.String[] p2, boolean p3, int p4, int[] p5, android.os.Bundle p6);
    public abstract void addPendingTopUid(int p0, int p1);
    public abstract void deletePendingTopUid(int p0);
    public abstract boolean isPendingTopUid(int p0);
    public abstract android.content.Intent getIntentForIntentSender(android.content.IIntentSender p0);
    public abstract android.app.PendingIntent getPendingIntentActivityAsApp(int p0, android.content.Intent p1, int p2, android.os.Bundle p3, java.lang.String p4, int p5);
    public abstract android.app.PendingIntent getPendingIntentActivityAsApp(int p0, android.content.Intent[] p1, int p2, android.os.Bundle p3, java.lang.String p4, int p5);
    public abstract long getBootTimeTempAllowListDuration();
    public abstract void registerAnrController(android.app.AnrController p0);
    public abstract void unregisterAnrController(android.app.AnrController p0);
    public abstract boolean isTempAllowlistedForFgsWhileInUse(int p0);
    public abstract int getPushMessagingOverQuotaBehavior();
    public abstract int getUidCapability(int p0);
    public abstract java.util.List<java.lang.Integer> getIsolatedProcesses(int p0);

    public static enum ServiceNotificationPolicy {
        NOT_FOREGROUND_SERVICE,
        SHOW_IMMEDIATELY,
        UPDATE_ONLY;
        private ServiceNotificationPolicy() {}
    }
}
