package android.app;

public interface FeatureFlags {
    public boolean apiRichOngoing();
    public boolean apiTvextender();
    public boolean appRestrictionsApi();
    public boolean appStartInfo();
    public boolean appStartInfoTimestamps();
    public boolean bicClient();
    public boolean categoryVoicemail();
    public boolean checkAutogroupBeforePost();
    public boolean cleanUpSpansAndNewLines();
    public boolean clearDnsCacheOnNetworkRulesUpdate();
    public boolean compactHeadsUpNotification();
    public boolean compactHeadsUpNotificationReply();
    public boolean enableFgsTimeoutCrashBehavior();
    public boolean enableNightModeBinderCache();
    public boolean enablePipUiStateCallbackOnEntering();
    public boolean evenlyDividedCallStyleActionLayout();
    public boolean gateFgsTimeoutAnrBehavior();
    public boolean getBindingUidImportance();
    public boolean introduceNewServiceOntimeoutCallback();
    public boolean keyguardPrivateNotifications();
    public boolean lifetimeExtensionRefactor();
    public boolean modesApi();
    public boolean modesUi();
    public boolean notificationChannelVibrationEffectApi();
    public boolean notificationExpansionOptional();
    public boolean notificationsUseAppIcon();
    public boolean notificationsUseAppIconInRow();
    public boolean notificationsUseMonochromeAppIcon();
    public boolean pinnerServiceClientApi();
    public boolean redactSensitiveContentNotificationsOnLockscreen();
    public boolean removeRemoteViews();
    public boolean restrictAudioAttributesAlarm();
    public boolean restrictAudioAttributesCall();
    public boolean restrictAudioAttributesMedia();
    public boolean secureAllowlistToken();
    public boolean skipBgMemTrimOnFgApp();
    public boolean sortSectionByTime();
    public boolean systemTermsOfAddressEnabled();
    public boolean uidImportanceListenerForUids();
    public boolean updateRankingTime();
    public boolean visitPersonUri();
}
