package android.app;

public final class FeatureFlagsImpl implements android.app.FeatureFlags {
    public FeatureFlagsImpl() {}
    public boolean apiMetricStyle() { return false; }
    public boolean apiRichOngoing() { return false; }
    public boolean apiRichOngoingPermission() { return false; }
    public boolean apiTvextender() { return false; }
    public boolean appExitInfoDebugMemoryApi() { return false; }
    public boolean appRestrictionsApi() { return false; }
    public boolean appStartInfo() { return false; }
    public boolean appStartInfoCleanupOldRecords() { return false; }
    public boolean appStartInfoComponent() { return false; }
    public boolean appStartInfoKeepRecordsSorted() { return false; }
    public boolean appStartInfoTimestamps() { return false; }
    public boolean backgroundInstallControlCallbackApi() { return false; }
    public boolean backupRestoreLogging() { return false; }
    public boolean bicClient() { return false; }
    public boolean categoryVoicemail() { return false; }
    public boolean cleanUpSpansAndNewLines() { return false; }
    public boolean compactHeadsUpNotificationReply() { return false; }
    public boolean deviceUnlockListener() { return false; }
    public boolean enableConnectedDisplaysWallpaper() { return false; }
    public boolean enableCurrentModeTypeBinderCache() { return false; }
    public boolean enableNightModeBinderCache() { return false; }
    public boolean enablePipUiStateCallbackOnEntering() { return false; }
    public boolean enableProcessObserverBroadcastOnProcessStarted() { return false; }
    public boolean enableTvImplicitEnterPipRestriction() { return false; }
    public boolean enableWallpaperTransformSurfaceControlCommand() { return false; }
    public boolean enforcePicTestmodeProtocol() { return false; }
    public boolean evenlyDividedCallStyleActionLayout() { return false; }
    public boolean expandingPublicView() { return false; }
    public boolean fixGetBitmapCrops() { return false; }
    public boolean fixWallpaperChanged() { return false; }
    public boolean getBindingUidImportance() { return false; }
    public boolean hideStatusBarNotification() { return false; }
    public boolean includeAnrSubreason() { return false; }
    public boolean introduceNewServiceOntimeoutCallback() { return false; }
    public boolean jankPerceptibleNarrow() { return false; }
    public boolean jankPerceptibleNarrowHoldback() { return false; }
    public boolean lifetimeExtensionRefactor() { return false; }
    public boolean liveWallpaperContentHandling() { return false; }
    public boolean modesApi() { return false; }
    public boolean modesUi() { return false; }
    public boolean modesUiDndSlice() { return false; }
    public boolean modesUiDndTile() { return false; }
    public boolean modesUiTileReactivatesLast() { return false; }
    public boolean nmBinderPerfCacheChannels() { return false; }
    public boolean nmBinderPerfGetAppsWithChannels() { return false; }
    public boolean nmBinderPerfLogNmThrottling() { return false; }
    public boolean nmBinderPerfPermissionCheck() { return false; }
    public boolean nmBinderPerfThrottleNotify() { return false; }
    public boolean nmCollapsedLines() { return false; }
    public boolean nmSummarization() { return false; }
    public boolean nmSummarizationOnboardingUi() { return false; }
    public boolean nmSummarizationUi() { return false; }
    public boolean noSbnholder() { return false; }
    public boolean notifChannelCropVibrationEffects() { return false; }
    public boolean notifChannelEstimateEffectSize() { return false; }
    public boolean notifEntryCreationTimeUseElapsedRealtime() { return false; }
    public boolean notificationChannelVibrationEffectApi() { return false; }
    public boolean notificationClassificationUi() { return false; }
    public boolean notificationExpansionOptional() { return false; }
    public boolean notificationNoCustomViewConversations() { return false; }
    public boolean notificationsRedesignAppIcons() { return false; }
    public boolean notificationsRedesignFonts() { return false; }
    public boolean notificationsRedesignTemplates() { return false; }
    public boolean notificationsRedesignThemedAppIcons() { return false; }
    public boolean notifyKeyguardEvents() { return false; }
    public boolean onRestartActivityLifecycleCallback() { return false; }
    public boolean optInRichOngoing() { return false; }
    public boolean optimizeGetAppsAndShortcuts() { return false; }
    public boolean picCacheNulls() { return false; }
    public boolean picIsolateCacheByUid() { return false; }
    public boolean picIsolatedCacheStatistics() { return false; }
    public boolean picSeparatePermissionNotifications() { return false; }
    public boolean picTestMode() { return false; }
    public boolean pinnerServiceClientApi() { return false; }
    public boolean redactSensitiveContentNotificationsOnLockscreen() { return false; }
    public boolean removeNextWallpaperComponent() { return false; }
    public boolean removeRemoteViews() { return false; }
    public boolean reportPostgcMemoryMetrics() { return false; }
    public boolean restrictAudioAttributesAlarm() { return false; }
    public boolean restrictAudioAttributesCall() { return false; }
    public boolean restrictAudioAttributesMedia() { return false; }
    public boolean skipBgMemTrimOnFgApp() { return false; }
    public boolean skipRefContentProvider() { return false; }
    public boolean systemTermsOfAddressEnabled() { return false; }
    public boolean uiRichOngoing() { return false; }
    public boolean uidImportanceListenerForUids() { return false; }
    public boolean updateRecentsFromSystem() { return false; }
    public boolean useAppInfoNotLaunched() { return false; }
    public boolean useStickyBcastCache() { return false; }
}
