package com.android.media.flags;

public interface FeatureFlags {
    public boolean adjustVolumeForForegroundAppPlayingAudioWithoutMediaSession();
    public boolean avoidBinderCallsDuringRender();
    public boolean avoidBinderCallsForMutingExpectedDevice();
    public boolean cleanUpDeadRouterRecordsAfterUnbinding();
    public boolean disableSetBluetoothAd2pOnCalls();
    public boolean disableTransferWhenAppsDoNotSupport();
    public boolean enableAudioInputDeviceRoutingAndVolumeControl();
    public boolean enableAudioPoliciesDeviceAndBluetoothController();
    public boolean enableBuiltInSpeakerRouteSuitabilityStatuses();
    public boolean enableCrossUserRoutingInMediaRouter2();
    public boolean enableDeviceAddressAsIdentifierInMediaRouter2();
    public boolean enableDeviceSuggestionsPreference();
    public boolean enableFixForRouteVisibility();
    public boolean enableFullScanWithMediaContentControl();
    public boolean enableGetTransferableRoutes();
    public boolean enableMediaRoute2InfoProviderPackageName();
    public boolean enableMirroringInMediaRouter2();
    public boolean enableMr2ServiceNonMainBgThread();
    public boolean enableNewMediaRoute2InfoTypes();
    public boolean enableNewWiredMediaRoute2InfoTypes();
    public boolean enableNotifyingActivityManagerWithMediaSessionStatusChange();
    public boolean enableOutputSwitcherDeviceGrouping();
    public boolean enableOutputSwitcherPersonalAudioSharing();
    public boolean enableOutputSwitcherRedesign();
    public boolean enableOutputSwitcherSessionGrouping();
    public boolean enablePerAppMirroringInMediaRouter2();
    public boolean enablePreventionOfKeepAliveRouteProviders();
    public boolean enablePrivilegedRoutingForMediaRoutingControl();
    public boolean enableRlpCallbacksInMediaRouter2();
    public boolean enableRouteVisibilityControlApi();
    public boolean enableScreenOffScanning();
    public boolean enableSuggestedDeviceApi();
    public boolean enableUseOfBluetoothDeviceGetAliasForMr2infoGetName();
    public boolean enableUseOfSingletonAudioManagerRouteController();
    public boolean enableWaitingStateForSystemSessionCreationRequest();
    public boolean fallbackToDefaultHandlingWhenMediaSessionHasFixedVolumeHandling();
    public boolean hideBtAddressFromAppsWithoutBtPermission();
}
