package com.google.android.wearable.media.sessions;

public final class Enums {
    public static final int AUTO_LAUNCH = 3;
    public static final int COMPLICATION = 5;
    public static final int CUSTOM_ACTION = 11;
    public static final int LAUNCHER = 2;
    public static final int MEDIA_SCREEN_OVERFLOW_SCREEN = 2;
    public static final int MEDIA_SCREEN_PLAYER_SCREEN = 1;
    public static final int MEDIA_SCREEN_QUEUE_SCREEN = 3;
    public static final int MEDIA_SCREEN_UNKNOWN_SCREEN = 0;
    public static final int MEDIA_SCREEN_VOLUME_SCREEN = 4;
    public static final int ONGOING_ACTIVITY = 1;
    public static final int PAUSE = 2;
    public static final int PLAY = 1;
    public static final int RECENT_APPS = 4;
    public static final int RESUME = 5;
    public static final int SEEK_BACK = 9;
    public static final int SEEK_FORWARD = 10;
    public static final int SEEK_IN_CURRENT_MEDIA_ITEM = 8;
    public static final int SEEK_TO_MEDIA_ITEM = 12;
    public static final int SKIP_NEXT = 3;
    public static final int SKIP_PREV = 4;
    public static final int TYPE_ADVANCE_BLUETOOTH = 21;
    public static final int TYPE_BLE_HEADSET = 23;
    public static final int TYPE_BLUETOOTH_A2DP = 2;
    public static final int TYPE_BUILTIN_SPEAKER = 1;
    public static final int TYPE_GROUP = 5;
    public static final int TYPE_HDMI = 12;
    public static final int TYPE_HDMI_ARC = 13;
    public static final int TYPE_HDMI_EARC = 14;
    public static final int TYPE_REMOTE_CAR = 18;
    public static final int TYPE_REMOTE_COMPUTER = 16;
    public static final int TYPE_REMOTE_GAME_CONSOLE = 17;
    public static final int TYPE_REMOTE_SMARTPHONE = 20;
    public static final int TYPE_REMOTE_SMARTWATCH = 19;
    public static final int TYPE_REMOTE_SPEAKER = 3;
    public static final int TYPE_REMOTE_TABLET = 15;
    public static final int TYPE_REMOTE_TABLET_DOCKED = 11;
    public static final int TYPE_REMOTE_TV = 4;
    public static final int TYPE_SASS = 22;
    public static final int TYPE_UNKNOWN = 0;
    public static final int TYPE_USB_ACCESSORY = 8;
    public static final int TYPE_USB_DEVICE = 6;
    public static final int TYPE_USB_HEADSET = 7;
    public static final int TYPE_WIRED_HEADPHONES = 10;
    public static final int TYPE_WIRED_HEADSET = 9;
    public static final int UNKNOWN_ACTION = 0;
    public static final int UNKNOWN_SOURCE = 0;
    public static final int VOLUME_DECREASE = 7;
    public static final int VOLUME_INCREASE = 6;
    public static final int VOLUME_SET = 13;
    public Enums() {}
}
