package com.android.org.conscrypt;

public final class NativeCrypto {
    static final int GN_STACK_SUBJECT_ALT_NAME = 1;
    static final int GN_STACK_ISSUER_ALT_NAME = 2;
    static final int EXTENSION_TYPE_NON_CRITICAL = 0;
    static final int EXTENSION_TYPE_CRITICAL = 1;
    static final int PKCS7_CERTS = 1;
    static final int PKCS7_CRLS = 2;
    static final java.lang.String OBSOLETE_PROTOCOL_SSLV3 = "SSLv3";
    static final java.lang.String SUPPORTED_PROTOCOL_TLSV1_3 = "TLSv1.3";
    static final java.lang.String[] SUPPORTED_TLS_1_3_CIPHER_SUITES = null;
    static final java.util.Set<java.lang.String> SUPPORTED_TLS_1_2_CIPHER_SUITES_SET = null;
    static final java.util.Set<java.lang.String> SUPPORTED_TLS_1_3_CIPHER_SUITES_SET = null;
    static final java.lang.String TLS_EMPTY_RENEGOTIATION_INFO_SCSV = "TLS_EMPTY_RENEGOTIATION_INFO_SCSV";
    static final java.lang.String[] DEFAULT_X509_CIPHER_SUITES = null;
    static final java.lang.String[] DEFAULT_PSK_CIPHER_SUITES = null;
    static final java.lang.String[] TLSV13_PROTOCOLS = null;
    static final java.lang.String[] TLSV12_PROTOCOLS = null;
    static final java.lang.String[] TLSV11_PROTOCOLS = null;
    static final java.lang.String[] TLSV1_PROTOCOLS = null;
    static final java.lang.String[] DEFAULT_PROTOCOLS = null;
    public NativeCrypto() {}
    static void checkAvailability() {}
    static native long EVP_PKEY_new_RSA(byte[] p0, byte[] p1, byte[] p2, byte[] p3, byte[] p4, byte[] p5, byte[] p6, byte[] p7);
    static native int EVP_PKEY_type(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native java.lang.String EVP_PKEY_print_public(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native java.lang.String EVP_PKEY_print_params(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native void EVP_PKEY_free(long p0);
    static native int EVP_PKEY_cmp(com.android.org.conscrypt.NativeRef.EVP_PKEY p0, com.android.org.conscrypt.NativeRef.EVP_PKEY p1);
    static native byte[] EVP_marshal_private_key(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native long EVP_parse_private_key(byte[] p0) throws com.android.org.conscrypt.OpenSSLX509CertificateFactory.ParsingException;
    static native byte[] EVP_marshal_public_key(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native long EVP_parse_public_key(byte[] p0) throws com.android.org.conscrypt.OpenSSLX509CertificateFactory.ParsingException;
    static native long PEM_read_bio_PUBKEY(long p0);
    static native long PEM_read_bio_PrivateKey(long p0);
    static native long getRSAPrivateKeyWrapper(java.security.PrivateKey p0, byte[] p1);
    static native long getECPrivateKeyWrapper(java.security.PrivateKey p0, com.android.org.conscrypt.NativeRef.EC_GROUP p1);
    static native long RSA_generate_key_ex(int p0, byte[] p1);
    static native int RSA_size(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native int RSA_private_encrypt(int p0, byte[] p1, byte[] p2, com.android.org.conscrypt.NativeRef.EVP_PKEY p3, int p4);
    static native int RSA_public_decrypt(int p0, byte[] p1, byte[] p2, com.android.org.conscrypt.NativeRef.EVP_PKEY p3, int p4) throws javax.crypto.BadPaddingException, java.security.SignatureException;
    static native int RSA_public_encrypt(int p0, byte[] p1, byte[] p2, com.android.org.conscrypt.NativeRef.EVP_PKEY p3, int p4);
    static native int RSA_private_decrypt(int p0, byte[] p1, byte[] p2, com.android.org.conscrypt.NativeRef.EVP_PKEY p3, int p4) throws javax.crypto.BadPaddingException, java.security.SignatureException;
    static native byte[][] get_RSA_public_params(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native byte[][] get_RSA_private_params(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native void chacha20_encrypt_decrypt(byte[] p0, int p1, byte[] p2, int p3, int p4, byte[] p5, byte[] p6, int p7);
    static native long EVP_PKEY_new_EC_KEY(com.android.org.conscrypt.NativeRef.EC_GROUP p0, com.android.org.conscrypt.NativeRef.EC_POINT p1, byte[] p2);
    static native long EC_GROUP_new_by_curve_name(java.lang.String p0);
    static native long EC_GROUP_new_arbitrary(byte[] p0, byte[] p1, byte[] p2, byte[] p3, byte[] p4, byte[] p5, int p6);
    static native java.lang.String EC_GROUP_get_curve_name(com.android.org.conscrypt.NativeRef.EC_GROUP p0);
    static native byte[][] EC_GROUP_get_curve(com.android.org.conscrypt.NativeRef.EC_GROUP p0);
    static native void EC_GROUP_clear_free(long p0);
    static native long EC_GROUP_get_generator(com.android.org.conscrypt.NativeRef.EC_GROUP p0);
    static native byte[] EC_GROUP_get_order(com.android.org.conscrypt.NativeRef.EC_GROUP p0);
    static native int EC_GROUP_get_degree(com.android.org.conscrypt.NativeRef.EC_GROUP p0);
    static native byte[] EC_GROUP_get_cofactor(com.android.org.conscrypt.NativeRef.EC_GROUP p0);
    static native long EC_POINT_new(com.android.org.conscrypt.NativeRef.EC_GROUP p0);
    static native void EC_POINT_clear_free(long p0);
    static native byte[][] EC_POINT_get_affine_coordinates(com.android.org.conscrypt.NativeRef.EC_GROUP p0, com.android.org.conscrypt.NativeRef.EC_POINT p1);
    static native void EC_POINT_set_affine_coordinates(com.android.org.conscrypt.NativeRef.EC_GROUP p0, com.android.org.conscrypt.NativeRef.EC_POINT p1, byte[] p2, byte[] p3);
    static native long EC_KEY_generate_key(com.android.org.conscrypt.NativeRef.EC_GROUP p0);
    static native long EC_KEY_get1_group(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native byte[] EC_KEY_get_private_key(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native long EC_KEY_get_public_key(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native byte[] EC_KEY_marshal_curve_name(com.android.org.conscrypt.NativeRef.EC_GROUP p0) throws java.io.IOException;
    static native long EC_KEY_parse_curve_name(byte[] p0) throws java.io.IOException;
    static native int ECDH_compute_key(byte[] p0, int p1, com.android.org.conscrypt.NativeRef.EVP_PKEY p2, com.android.org.conscrypt.NativeRef.EVP_PKEY p3) throws java.security.InvalidKeyException, java.lang.IndexOutOfBoundsException;
    static native int ECDSA_size(com.android.org.conscrypt.NativeRef.EVP_PKEY p0);
    static native int ECDSA_sign(byte[] p0, byte[] p1, com.android.org.conscrypt.NativeRef.EVP_PKEY p2);
    static native int ECDSA_verify(byte[] p0, byte[] p1, com.android.org.conscrypt.NativeRef.EVP_PKEY p2);
    static native boolean X25519(byte[] p0, byte[] p1, byte[] p2) throws java.security.InvalidKeyException;
    static native void X25519_keypair(byte[] p0, byte[] p1);
    static native long EVP_get_digestbyname(java.lang.String p0);
    static native int EVP_MD_size(long p0);
    static native long EVP_MD_CTX_create();
    static native void EVP_MD_CTX_cleanup(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0);
    static native void EVP_MD_CTX_destroy(long p0);
    static native int EVP_MD_CTX_copy_ex(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, com.android.org.conscrypt.NativeRef.EVP_MD_CTX p1);
    static native int EVP_DigestInit_ex(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, long p1);
    static native void EVP_DigestUpdate(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, byte[] p1, int p2, int p3);
    static native void EVP_DigestUpdateDirect(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, long p1, int p2);
    static native int EVP_DigestFinal_ex(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, byte[] p1, int p2);
    static native long EVP_DigestSignInit(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, long p1, com.android.org.conscrypt.NativeRef.EVP_PKEY p2);
    static native long EVP_DigestVerifyInit(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, long p1, com.android.org.conscrypt.NativeRef.EVP_PKEY p2);
    static native void EVP_DigestSignUpdate(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, byte[] p1, int p2, int p3);
    static native void EVP_DigestSignUpdateDirect(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, long p1, int p2);
    static native void EVP_DigestVerifyUpdate(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, byte[] p1, int p2, int p3);
    static native void EVP_DigestVerifyUpdateDirect(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, long p1, int p2);
    static native byte[] EVP_DigestSignFinal(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0);
    static native boolean EVP_DigestVerifyFinal(com.android.org.conscrypt.NativeRef.EVP_MD_CTX p0, byte[] p1, int p2, int p3) throws java.lang.IndexOutOfBoundsException;
    static native long EVP_PKEY_encrypt_init(com.android.org.conscrypt.NativeRef.EVP_PKEY p0) throws java.security.InvalidKeyException;
    static native int EVP_PKEY_encrypt(com.android.org.conscrypt.NativeRef.EVP_PKEY_CTX p0, byte[] p1, int p2, byte[] p3, int p4, int p5) throws java.lang.IndexOutOfBoundsException, javax.crypto.BadPaddingException;
    static native long EVP_PKEY_decrypt_init(com.android.org.conscrypt.NativeRef.EVP_PKEY p0) throws java.security.InvalidKeyException;
    static native int EVP_PKEY_decrypt(com.android.org.conscrypt.NativeRef.EVP_PKEY_CTX p0, byte[] p1, int p2, byte[] p3, int p4, int p5) throws java.lang.IndexOutOfBoundsException, javax.crypto.BadPaddingException;
    static native void EVP_PKEY_CTX_free(long p0);
    static native void EVP_PKEY_CTX_set_rsa_padding(long p0, int p1) throws java.security.InvalidAlgorithmParameterException;
    static native void EVP_PKEY_CTX_set_rsa_pss_saltlen(long p0, int p1) throws java.security.InvalidAlgorithmParameterException;
    static native void EVP_PKEY_CTX_set_rsa_mgf1_md(long p0, long p1) throws java.security.InvalidAlgorithmParameterException;
    static native void EVP_PKEY_CTX_set_rsa_oaep_md(long p0, long p1) throws java.security.InvalidAlgorithmParameterException;
    static native void EVP_PKEY_CTX_set_rsa_oaep_label(long p0, byte[] p1) throws java.security.InvalidAlgorithmParameterException;
    static native long EVP_get_cipherbyname(java.lang.String p0);
    static native void EVP_CipherInit_ex(com.android.org.conscrypt.NativeRef.EVP_CIPHER_CTX p0, long p1, byte[] p2, byte[] p3, boolean p4);
    static native int EVP_CipherUpdate(com.android.org.conscrypt.NativeRef.EVP_CIPHER_CTX p0, byte[] p1, int p2, byte[] p3, int p4, int p5) throws java.lang.IndexOutOfBoundsException;
    static native int EVP_CipherFinal_ex(com.android.org.conscrypt.NativeRef.EVP_CIPHER_CTX p0, byte[] p1, int p2) throws javax.crypto.BadPaddingException, javax.crypto.IllegalBlockSizeException;
    static native int EVP_CIPHER_iv_length(long p0);
    static native long EVP_CIPHER_CTX_new();
    static native int EVP_CIPHER_CTX_block_size(com.android.org.conscrypt.NativeRef.EVP_CIPHER_CTX p0);
    static native int get_EVP_CIPHER_CTX_buf_len(com.android.org.conscrypt.NativeRef.EVP_CIPHER_CTX p0);
    static native boolean get_EVP_CIPHER_CTX_final_used(com.android.org.conscrypt.NativeRef.EVP_CIPHER_CTX p0);
    static native void EVP_CIPHER_CTX_set_padding(com.android.org.conscrypt.NativeRef.EVP_CIPHER_CTX p0, boolean p1);
    static native void EVP_CIPHER_CTX_set_key_length(com.android.org.conscrypt.NativeRef.EVP_CIPHER_CTX p0, int p1);
    static native void EVP_CIPHER_CTX_free(long p0);
    static native long EVP_aead_aes_128_gcm();
    static native long EVP_aead_aes_256_gcm();
    static native long EVP_aead_chacha20_poly1305();
    static native long EVP_aead_aes_128_gcm_siv();
    static native long EVP_aead_aes_256_gcm_siv();
    static native int EVP_AEAD_max_overhead(long p0);
    static native int EVP_AEAD_nonce_length(long p0);
    static native int EVP_AEAD_CTX_seal(long p0, byte[] p1, int p2, byte[] p3, int p4, byte[] p5, byte[] p6, int p7, int p8, byte[] p9) throws javax.crypto.ShortBufferException, javax.crypto.BadPaddingException;
    static native int EVP_AEAD_CTX_seal_buf(long p0, byte[] p1, int p2, java.nio.ByteBuffer p3, byte[] p4, java.nio.ByteBuffer p5, byte[] p6) throws javax.crypto.ShortBufferException, javax.crypto.BadPaddingException;
    static native int EVP_AEAD_CTX_open(long p0, byte[] p1, int p2, byte[] p3, int p4, byte[] p5, byte[] p6, int p7, int p8, byte[] p9) throws javax.crypto.ShortBufferException, javax.crypto.BadPaddingException;
    static native int EVP_AEAD_CTX_open_buf(long p0, byte[] p1, int p2, java.nio.ByteBuffer p3, byte[] p4, java.nio.ByteBuffer p5, byte[] p6) throws javax.crypto.ShortBufferException, javax.crypto.BadPaddingException;
    static native long CMAC_CTX_new();
    static native void CMAC_CTX_free(long p0);
    static native void CMAC_Init(com.android.org.conscrypt.NativeRef.CMAC_CTX p0, byte[] p1);
    static native void CMAC_Update(com.android.org.conscrypt.NativeRef.CMAC_CTX p0, byte[] p1, int p2, int p3);
    static native void CMAC_UpdateDirect(com.android.org.conscrypt.NativeRef.CMAC_CTX p0, long p1, int p2);
    static native byte[] CMAC_Final(com.android.org.conscrypt.NativeRef.CMAC_CTX p0);
    static native long HMAC_CTX_new();
    static native void HMAC_CTX_free(long p0);
    static native void HMAC_Init_ex(com.android.org.conscrypt.NativeRef.HMAC_CTX p0, byte[] p1, long p2);
    static native void HMAC_Update(com.android.org.conscrypt.NativeRef.HMAC_CTX p0, byte[] p1, int p2, int p3);
    static native void HMAC_UpdateDirect(com.android.org.conscrypt.NativeRef.HMAC_CTX p0, long p1, int p2);
    static native byte[] HMAC_Final(com.android.org.conscrypt.NativeRef.HMAC_CTX p0);
    static native void RAND_bytes(byte[] p0);
    static int X509_NAME_hash(javax.security.auth.x500.X500Principal p0) { return 0; }
    public static int X509_NAME_hash_old(javax.security.auth.x500.X500Principal p0) { return 0; }
    static native long d2i_X509_bio(long p0);
    static native long d2i_X509(byte[] p0) throws com.android.org.conscrypt.OpenSSLX509CertificateFactory.ParsingException;
    static native long PEM_read_bio_X509(long p0);
    static native byte[] i2d_X509(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native byte[] i2d_X509_PUBKEY(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native byte[] ASN1_seq_pack_X509(long[] p0);
    static native long[] ASN1_seq_unpack_X509_bio(long p0) throws com.android.org.conscrypt.OpenSSLX509CertificateFactory.ParsingException;
    static native void X509_free(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native int X509_cmp(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1, long p2, com.android.org.conscrypt.OpenSSLX509Certificate p3);
    static native void X509_print_ex(long p0, long p1, com.android.org.conscrypt.OpenSSLX509Certificate p2, long p3, long p4);
    static native byte[] X509_get_issuer_name(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native byte[] X509_get_subject_name(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native java.lang.String get_X509_sig_alg_oid(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native byte[] get_X509_sig_alg_parameter(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native boolean[] get_X509_issuerUID(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native boolean[] get_X509_subjectUID(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native long X509_get_pubkey(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1) throws java.security.NoSuchAlgorithmException, java.security.InvalidKeyException;
    static native java.lang.String get_X509_pubkey_oid(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native byte[] X509_get_ext_oid(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1, java.lang.String p2);
    static native java.lang.String[] get_X509_ext_oids(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1, int p2);
    static native java.lang.Object[][] get_X509_GENERAL_NAME_stack(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1, int p2) throws java.security.cert.CertificateParsingException;
    static native boolean[] get_X509_ex_kusage(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native java.lang.String[] get_X509_ex_xkusage(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native int get_X509_ex_pathlen(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native long X509_get_notBefore(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native long X509_get_notAfter(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native long X509_get_version(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native byte[] X509_get_serialNumber(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native void X509_verify(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1, com.android.org.conscrypt.NativeRef.EVP_PKEY p2) throws javax.crypto.BadPaddingException;
    static native byte[] get_X509_tbs_cert(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native byte[] get_X509_tbs_cert_without_ext(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1, java.lang.String p2);
    static native byte[] get_X509_signature(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native int get_X509_ex_flags(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1);
    static native int X509_check_issued(long p0, com.android.org.conscrypt.OpenSSLX509Certificate p1, long p2, com.android.org.conscrypt.OpenSSLX509Certificate p3);
    static native long[] d2i_PKCS7_bio(long p0, int p1) throws com.android.org.conscrypt.OpenSSLX509CertificateFactory.ParsingException;
    static native byte[] i2d_PKCS7(long[] p0);
    static native long[] PEM_read_bio_PKCS7(long p0, int p1);
    static native long d2i_X509_CRL_bio(long p0);
    static native long PEM_read_bio_X509_CRL(long p0);
    static native byte[] i2d_X509_CRL(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native void X509_CRL_free(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native void X509_CRL_print(long p0, long p1, com.android.org.conscrypt.OpenSSLX509CRL p2);
    static native java.lang.String get_X509_CRL_sig_alg_oid(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native byte[] get_X509_CRL_sig_alg_parameter(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native byte[] X509_CRL_get_issuer_name(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native long X509_CRL_get0_by_cert(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1, long p2, com.android.org.conscrypt.OpenSSLX509Certificate p3);
    static native long X509_CRL_get0_by_serial(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1, byte[] p2);
    static native long[] X509_CRL_get_REVOKED(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native java.lang.String[] get_X509_CRL_ext_oids(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1, int p2);
    static native byte[] X509_CRL_get_ext_oid(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1, java.lang.String p2);
    static native long X509_CRL_get_version(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native long X509_CRL_get_ext(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1, java.lang.String p2);
    static native byte[] get_X509_CRL_signature(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native void X509_CRL_verify(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1, com.android.org.conscrypt.NativeRef.EVP_PKEY p2) throws javax.crypto.BadPaddingException, java.security.SignatureException, java.security.NoSuchAlgorithmException, java.security.InvalidKeyException, javax.crypto.IllegalBlockSizeException;
    static native byte[] get_X509_CRL_crl_enc(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native long X509_CRL_get_lastUpdate(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native long X509_CRL_get_nextUpdate(long p0, com.android.org.conscrypt.OpenSSLX509CRL p1);
    static native long X509_REVOKED_dup(long p0);
    static native byte[] i2d_X509_REVOKED(long p0);
    static native java.lang.String[] get_X509_REVOKED_ext_oids(long p0, int p1);
    static native byte[] X509_REVOKED_get_ext_oid(long p0, java.lang.String p1);
    static native byte[] X509_REVOKED_get_serialNumber(long p0);
    static native long X509_REVOKED_get_ext(long p0, java.lang.String p1);
    static native long get_X509_REVOKED_revocationDate(long p0);
    static native void X509_REVOKED_print(long p0, long p1);
    static native int X509_supported_extension(long p0);
    static native void ASN1_TIME_to_Calendar(long p0, java.util.Calendar p1) throws com.android.org.conscrypt.OpenSSLX509CertificateFactory.ParsingException;
    static native long asn1_read_init(byte[] p0) throws java.io.IOException;
    static native long asn1_read_sequence(long p0) throws java.io.IOException;
    static native boolean asn1_read_next_tag_is(long p0, int p1) throws java.io.IOException;
    static native long asn1_read_tagged(long p0) throws java.io.IOException;
    static native byte[] asn1_read_octetstring(long p0) throws java.io.IOException;
    static native long asn1_read_uint64(long p0) throws java.io.IOException;
    static native void asn1_read_null(long p0) throws java.io.IOException;
    static native java.lang.String asn1_read_oid(long p0) throws java.io.IOException;
    static native boolean asn1_read_is_empty(long p0);
    static native void asn1_read_free(long p0);
    static native long asn1_write_init() throws java.io.IOException;
    static native long asn1_write_sequence(long p0) throws java.io.IOException;
    static native long asn1_write_tag(long p0, int p1) throws java.io.IOException;
    static native void asn1_write_octetstring(long p0, byte[] p1) throws java.io.IOException;
    static native void asn1_write_uint64(long p0, long p1) throws java.io.IOException;
    static native void asn1_write_null(long p0) throws java.io.IOException;
    static native void asn1_write_oid(long p0, java.lang.String p1) throws java.io.IOException;
    static native void asn1_write_flush(long p0) throws java.io.IOException;
    static native byte[] asn1_write_finish(long p0) throws java.io.IOException;
    static native void asn1_write_cleanup(long p0);
    static native void asn1_write_free(long p0);
    static native long create_BIO_InputStream(com.android.org.conscrypt.OpenSSLBIOInputStream p0, boolean p1);
    static native long create_BIO_OutputStream(java.io.OutputStream p0);
    static native void BIO_free_all(long p0);
    static java.lang.String cipherSuiteToJava(java.lang.String p0) { return null; }
    static java.lang.String cipherSuiteFromJava(java.lang.String p0) { return null; }
    static native int EVP_has_aes_hardware();
    static native long SSL_CTX_new();
    static java.lang.String[] getSupportedCipherSuites() { return null; }
    static native void SSL_CTX_free(long p0, com.android.org.conscrypt.AbstractSessionContext p1);
    static native void SSL_CTX_set_session_id_context(long p0, com.android.org.conscrypt.AbstractSessionContext p1, byte[] p2);
    static native long SSL_CTX_set_timeout(long p0, com.android.org.conscrypt.AbstractSessionContext p1, long p2);
    static native long SSL_new(long p0, com.android.org.conscrypt.AbstractSessionContext p1) throws javax.net.ssl.SSLException;
    static native void SSL_enable_tls_channel_id(long p0, com.android.org.conscrypt.NativeSsl p1) throws javax.net.ssl.SSLException;
    static native byte[] SSL_get_tls_channel_id(long p0, com.android.org.conscrypt.NativeSsl p1) throws javax.net.ssl.SSLException;
    static native void SSL_set1_tls_channel_id(long p0, com.android.org.conscrypt.NativeSsl p1, com.android.org.conscrypt.NativeRef.EVP_PKEY p2);
    static native void setLocalCertsAndPrivateKey(long p0, com.android.org.conscrypt.NativeSsl p1, byte[][] p2, com.android.org.conscrypt.NativeRef.EVP_PKEY p3) throws javax.net.ssl.SSLException;
    static native void SSL_set_client_CA_list(long p0, com.android.org.conscrypt.NativeSsl p1, byte[][] p2) throws javax.net.ssl.SSLException;
    static native long SSL_set_mode(long p0, com.android.org.conscrypt.NativeSsl p1, long p2);
    static native long SSL_set_options(long p0, com.android.org.conscrypt.NativeSsl p1, long p2);
    static native long SSL_clear_options(long p0, com.android.org.conscrypt.NativeSsl p1, long p2);
    static native int SSL_set_protocol_versions(long p0, com.android.org.conscrypt.NativeSsl p1, int p2, int p3);
    static native void SSL_enable_signed_cert_timestamps(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native byte[] SSL_get_signed_cert_timestamp_list(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void SSL_set_signed_cert_timestamp_list(long p0, com.android.org.conscrypt.NativeSsl p1, byte[] p2);
    static native void SSL_enable_ocsp_stapling(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native byte[] SSL_get_ocsp_response(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void SSL_set_ocsp_response(long p0, com.android.org.conscrypt.NativeSsl p1, byte[] p2);
    static native byte[] SSL_get_tls_unique(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native byte[] SSL_export_keying_material(long p0, com.android.org.conscrypt.NativeSsl p1, byte[] p2, byte[] p3, int p4) throws javax.net.ssl.SSLException;
    static native void SSL_use_psk_identity_hint(long p0, com.android.org.conscrypt.NativeSsl p1, java.lang.String p2) throws javax.net.ssl.SSLException;
    static native void set_SSL_psk_client_callback_enabled(long p0, com.android.org.conscrypt.NativeSsl p1, boolean p2);
    static native void set_SSL_psk_server_callback_enabled(long p0, com.android.org.conscrypt.NativeSsl p1, boolean p2);
    static java.lang.String[] getSupportedProtocols() { return null; }
    static void setEnabledProtocols(long p0, com.android.org.conscrypt.NativeSsl p1, java.lang.String[] p2) {}
    static java.lang.String[] checkEnabledProtocols(java.lang.String[] p0) { return null; }
    static native void SSL_set_cipher_lists(long p0, com.android.org.conscrypt.NativeSsl p1, java.lang.String[] p2);
    static native long[] SSL_get_ciphers(long p0, com.android.org.conscrypt.NativeSsl p1);
    static void setEnabledCipherSuites(long p0, com.android.org.conscrypt.NativeSsl p1, java.lang.String[] p2, java.lang.String[] p3) {}
    static java.lang.String[] checkEnabledCipherSuites(java.lang.String[] p0) { return null; }
    static native void SSL_set_accept_state(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void SSL_set_connect_state(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void SSL_set_verify(long p0, com.android.org.conscrypt.NativeSsl p1, int p2);
    static native void SSL_set_session(long p0, com.android.org.conscrypt.NativeSsl p1, long p2) throws javax.net.ssl.SSLException;
    static native void SSL_set_session_creation_enabled(long p0, com.android.org.conscrypt.NativeSsl p1, boolean p2) throws javax.net.ssl.SSLException;
    static native boolean SSL_session_reused(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void SSL_accept_renegotiations(long p0, com.android.org.conscrypt.NativeSsl p1) throws javax.net.ssl.SSLException;
    static native void SSL_set_tlsext_host_name(long p0, com.android.org.conscrypt.NativeSsl p1, java.lang.String p2) throws javax.net.ssl.SSLException;
    static native java.lang.String SSL_get_servername(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void SSL_do_handshake(long p0, com.android.org.conscrypt.NativeSsl p1, java.io.FileDescriptor p2, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p3, int p4) throws javax.net.ssl.SSLException, java.net.SocketTimeoutException, java.security.cert.CertificateException;
    public static native java.lang.String SSL_get_current_cipher(long p0, com.android.org.conscrypt.NativeSsl p1);
    public static native java.lang.String SSL_get_version(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native byte[][] SSL_get0_peer_certificates(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native int SSL_read(long p0, com.android.org.conscrypt.NativeSsl p1, java.io.FileDescriptor p2, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p3, byte[] p4, int p5, int p6, int p7) throws java.io.IOException;
    static native void SSL_write(long p0, com.android.org.conscrypt.NativeSsl p1, java.io.FileDescriptor p2, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p3, byte[] p4, int p5, int p6, int p7) throws java.io.IOException;
    static native void SSL_interrupt(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void SSL_shutdown(long p0, com.android.org.conscrypt.NativeSsl p1, java.io.FileDescriptor p2, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p3) throws java.io.IOException;
    static native int SSL_get_shutdown(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void SSL_free(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native long SSL_get_time(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native long SSL_set_timeout(long p0, com.android.org.conscrypt.NativeSsl p1, long p2);
    static native long SSL_get_timeout(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native int SSL_get_signature_algorithm_key_type(int p0);
    static native byte[] SSL_session_id(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native byte[] SSL_SESSION_session_id(long p0);
    static native long SSL_SESSION_get_time(long p0);
    static native long SSL_SESSION_get_timeout(long p0);
    static native java.lang.String SSL_SESSION_get_version(long p0);
    static native java.lang.String SSL_SESSION_cipher(long p0);
    static native boolean SSL_SESSION_should_be_single_use(long p0);
    static native void SSL_SESSION_up_ref(long p0);
    static native void SSL_SESSION_free(long p0);
    static native byte[] i2d_SSL_SESSION(long p0);
    static native long d2i_SSL_SESSION(byte[] p0) throws java.io.IOException;
    static native java.lang.String SSL_CIPHER_get_kx_name(long p0);
    static native java.lang.String[] get_cipher_names(java.lang.String p0);
    public static native byte[] get_ocsp_single_extension(byte[] p0, java.lang.String p1, long p2, com.android.org.conscrypt.OpenSSLX509Certificate p3, long p4, com.android.org.conscrypt.OpenSSLX509Certificate p5);
    static native long getDirectBufferAddress(java.nio.Buffer p0);
    static native long SSL_BIO_new(long p0, com.android.org.conscrypt.NativeSsl p1) throws javax.net.ssl.SSLException;
    static native int SSL_get_error(long p0, com.android.org.conscrypt.NativeSsl p1, int p2);
    static native void SSL_clear_error();
    static native int SSL_pending_readable_bytes(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native int SSL_pending_written_bytes_in_BIO(long p0);
    static native int SSL_max_seal_overhead(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native void setApplicationProtocols(long p0, com.android.org.conscrypt.NativeSsl p1, boolean p2, byte[] p3) throws java.io.IOException;
    static native void setHasApplicationProtocolSelector(long p0, com.android.org.conscrypt.NativeSsl p1, boolean p2) throws java.io.IOException;
    static native byte[] getApplicationProtocol(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native int ENGINE_SSL_do_handshake(long p0, com.android.org.conscrypt.NativeSsl p1, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p2) throws java.io.IOException;
    static native int ENGINE_SSL_read_direct(long p0, com.android.org.conscrypt.NativeSsl p1, long p2, int p3, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p4) throws java.io.IOException, java.security.cert.CertificateException;
    static native int ENGINE_SSL_write_direct(long p0, com.android.org.conscrypt.NativeSsl p1, long p2, int p3, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p4) throws java.io.IOException;
    static native int ENGINE_SSL_write_BIO_direct(long p0, com.android.org.conscrypt.NativeSsl p1, long p2, long p3, int p4, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p5) throws java.io.IOException;
    static native int ENGINE_SSL_read_BIO_direct(long p0, com.android.org.conscrypt.NativeSsl p1, long p2, long p3, int p4, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p5) throws java.io.IOException;
    static native void ENGINE_SSL_force_read(long p0, com.android.org.conscrypt.NativeSsl p1, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p2) throws java.io.IOException;
    static native void ENGINE_SSL_shutdown(long p0, com.android.org.conscrypt.NativeSsl p1, com.android.org.conscrypt.NativeCrypto.SSLHandshakeCallbacks p2) throws java.io.IOException;
    static native boolean usesBoringSsl_FIPS_mode();
    static native int BIO_read(long p0, byte[] p1) throws java.io.IOException;
    static native void BIO_write(long p0, byte[] p1, int p2, int p3) throws java.io.IOException, java.lang.IndexOutOfBoundsException;
    static native long SSL_clear_mode(long p0, com.android.org.conscrypt.NativeSsl p1, long p2);
    static native long SSL_get_mode(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native long SSL_get_options(long p0, com.android.org.conscrypt.NativeSsl p1);
    static native long SSL_get1_session(long p0, com.android.org.conscrypt.NativeSsl p1);

    private static class Range {
        public final java.lang.String min = null;
        public final java.lang.String max = null;
        public Range(java.lang.String p0, java.lang.String p1) {}
    }

    static interface SSLHandshakeCallbacks {
        public void verifyCertificateChain(byte[][] p0, java.lang.String p1) throws java.security.cert.CertificateException;
        public void clientCertificateRequested(byte[] p0, int[] p1, byte[][] p2) throws java.security.cert.CertificateEncodingException, javax.net.ssl.SSLException;
        public void serverCertificateRequested() throws java.io.IOException;
        public int clientPSKKeyRequested(java.lang.String p0, byte[] p1, byte[] p2);
        public int serverPSKKeyRequested(java.lang.String p0, java.lang.String p1, byte[] p2);
        public void onSSLStateChange(int p0, int p1);
        public void onNewSessionEstablished(long p0);
        public long serverSessionRequested(byte[] p0);
        public int selectApplicationProtocol(byte[] p0);
    }
}
