package android.multiuser;

public interface FeatureFlags {
    public boolean addUiForSoundsFromBackgroundUsers();
    public boolean allowMainUserToAccessBlockedNumberProvider();
    public boolean allowResolverSheetForPrivateSpace();
    public boolean avatarSync();
    public boolean bindWallpaperServiceOnItsOwnThreadDuringAUserSwitch();
    public boolean blockPrivateSpaceCreation();
    public boolean deletePrivateSpaceFromReset();
    public boolean disablePrivateSpaceItemsOnHome();
    public boolean enableBiometricsToUnlockPrivateSpace();
    public boolean enableHidingProfiles();
    public boolean enableLauncherAppsHiddenProfileChecks();
    public boolean enablePermissionToAccessHiddenProfiles();
    public boolean enablePrivateSpaceAutolockOnRestarts();
    public boolean enablePrivateSpaceFeatures();
    public boolean enablePrivateSpaceIntentRedirection();
    public boolean enablePsSensitiveNotificationsToggle();
    public boolean enableSystemUserOnlyForServicesAndProviders();
    public boolean fixAvatarConcurrentFileWrite();
    public boolean fixAvatarPickerReadBackOrder();
    public boolean fixAvatarPickerSelectedReadBack();
    public boolean handleInterleavedSettingsForPrivateSpace();
    public boolean moveQuietModeOperationsToSeparateThread();
    public boolean newMultiuserSettingsUx();
    public boolean reorderWallpaperDuringUserSwitch();
    public boolean restrictQuietModeCredentialBugFixToManagedProfiles();
    public boolean saveGlobalAndGuestRestrictionsOnSystemUserXml();
    public boolean saveGlobalAndGuestRestrictionsOnSystemUserXmlReadOnly();
    public boolean scheduleStopOfBackgroundUser();
    public boolean setPowerModeDuringUserSwitch();
    public boolean showSetScreenLockDialog();
    public boolean startUserBeforeScheduledAlarms();
    public boolean supportAutolockForPrivateSpace();
    public boolean supportCommunalProfile();
    public boolean supportCommunalProfileNextgen();
    public boolean useAllCpusDuringUserSwitch();
    public boolean usePrivateSpaceIconInBiometricPrompt();
}
