package com.google.android.gles_jni;

public class GLImpl implements javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.opengles.GL10Ext, javax.microedition.khronos.opengles.GL11, javax.microedition.khronos.opengles.GL11Ext, javax.microedition.khronos.opengles.GL11ExtensionPack {
    java.nio.Buffer _colorPointer;
    java.nio.Buffer _normalPointer;
    java.nio.Buffer _texCoordPointer;
    java.nio.Buffer _vertexPointer;
    java.nio.Buffer _pointSizePointerOES;
    java.nio.Buffer _matrixIndexPointerOES;
    java.nio.Buffer _weightPointerOES;
    private boolean haveCheckedExtensions;
    private boolean have_OES_blend_equation_separate;
    private boolean have_OES_blend_subtract;
    private boolean have_OES_framebuffer_object;
    private boolean have_OES_texture_cube_map;
    private static native void _nativeClassInit();
    public GLImpl() {}
    public void glGetPointerv(int p0, java.nio.Buffer[] p1) {}
    private static boolean allowIndirectBuffers(java.lang.String p0) { return false; }
    public native void glActiveTexture(int p0);
    public native void glAlphaFunc(int p0, float p1);
    public native void glAlphaFuncx(int p0, int p1);
    public native void glBindTexture(int p0, int p1);
    public native void glBlendFunc(int p0, int p1);
    public native void glClear(int p0);
    public native void glClearColor(float p0, float p1, float p2, float p3);
    public native void glClearColorx(int p0, int p1, int p2, int p3);
    public native void glClearDepthf(float p0);
    public native void glClearDepthx(int p0);
    public native void glClearStencil(int p0);
    public native void glClientActiveTexture(int p0);
    public native void glColor4f(float p0, float p1, float p2, float p3);
    public native void glColor4x(int p0, int p1, int p2, int p3);
    public native void glColorMask(boolean p0, boolean p1, boolean p2, boolean p3);
    private native void glColorPointerBounds(int p0, int p1, int p2, java.nio.Buffer p3, int p4);
    public void glColorPointer(int p0, int p1, int p2, java.nio.Buffer p3) {}
    public native void glCompressedTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.Buffer p7);
    public native void glCompressedTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.Buffer p8);
    public native void glCopyTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7);
    public native void glCopyTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7);
    public native void glCullFace(int p0);
    public native void glDeleteTextures(int p0, int[] p1, int p2);
    public native void glDeleteTextures(int p0, java.nio.IntBuffer p1);
    public native void glDepthFunc(int p0);
    public native void glDepthMask(boolean p0);
    public native void glDepthRangef(float p0, float p1);
    public native void glDepthRangex(int p0, int p1);
    public native void glDisable(int p0);
    public native void glDisableClientState(int p0);
    public native void glDrawArrays(int p0, int p1, int p2);
    public native void glDrawElements(int p0, int p1, int p2, java.nio.Buffer p3);
    public native void glEnable(int p0);
    public native void glEnableClientState(int p0);
    public native void glFinish();
    public native void glFlush();
    public native void glFogf(int p0, float p1);
    public native void glFogfv(int p0, float[] p1, int p2);
    public native void glFogfv(int p0, java.nio.FloatBuffer p1);
    public native void glFogx(int p0, int p1);
    public native void glFogxv(int p0, int[] p1, int p2);
    public native void glFogxv(int p0, java.nio.IntBuffer p1);
    public native void glFrontFace(int p0);
    public native void glFrustumf(float p0, float p1, float p2, float p3, float p4, float p5);
    public native void glFrustumx(int p0, int p1, int p2, int p3, int p4, int p5);
    public native void glGenTextures(int p0, int[] p1, int p2);
    public native void glGenTextures(int p0, java.nio.IntBuffer p1);
    public native int glGetError();
    public native void glGetIntegerv(int p0, int[] p1, int p2);
    public native void glGetIntegerv(int p0, java.nio.IntBuffer p1);
    public native java.lang.String _glGetString(int p0);
    public java.lang.String glGetString(int p0) { return null; }
    public native void glHint(int p0, int p1);
    public native void glLightModelf(int p0, float p1);
    public native void glLightModelfv(int p0, float[] p1, int p2);
    public native void glLightModelfv(int p0, java.nio.FloatBuffer p1);
    public native void glLightModelx(int p0, int p1);
    public native void glLightModelxv(int p0, int[] p1, int p2);
    public native void glLightModelxv(int p0, java.nio.IntBuffer p1);
    public native void glLightf(int p0, int p1, float p2);
    public native void glLightfv(int p0, int p1, float[] p2, int p3);
    public native void glLightfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glLightx(int p0, int p1, int p2);
    public native void glLightxv(int p0, int p1, int[] p2, int p3);
    public native void glLightxv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glLineWidth(float p0);
    public native void glLineWidthx(int p0);
    public native void glLoadIdentity();
    public native void glLoadMatrixf(float[] p0, int p1);
    public native void glLoadMatrixf(java.nio.FloatBuffer p0);
    public native void glLoadMatrixx(int[] p0, int p1);
    public native void glLoadMatrixx(java.nio.IntBuffer p0);
    public native void glLogicOp(int p0);
    public native void glMaterialf(int p0, int p1, float p2);
    public native void glMaterialfv(int p0, int p1, float[] p2, int p3);
    public native void glMaterialfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glMaterialx(int p0, int p1, int p2);
    public native void glMaterialxv(int p0, int p1, int[] p2, int p3);
    public native void glMaterialxv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glMatrixMode(int p0);
    public native void glMultMatrixf(float[] p0, int p1);
    public native void glMultMatrixf(java.nio.FloatBuffer p0);
    public native void glMultMatrixx(int[] p0, int p1);
    public native void glMultMatrixx(java.nio.IntBuffer p0);
    public native void glMultiTexCoord4f(int p0, float p1, float p2, float p3, float p4);
    public native void glMultiTexCoord4x(int p0, int p1, int p2, int p3, int p4);
    public native void glNormal3f(float p0, float p1, float p2);
    public native void glNormal3x(int p0, int p1, int p2);
    private native void glNormalPointerBounds(int p0, int p1, java.nio.Buffer p2, int p3);
    public void glNormalPointer(int p0, int p1, java.nio.Buffer p2) {}
    public native void glOrthof(float p0, float p1, float p2, float p3, float p4, float p5);
    public native void glOrthox(int p0, int p1, int p2, int p3, int p4, int p5);
    public native void glPixelStorei(int p0, int p1);
    public native void glPointSize(float p0);
    public native void glPointSizex(int p0);
    public native void glPolygonOffset(float p0, float p1);
    public native void glPolygonOffsetx(int p0, int p1);
    public native void glPopMatrix();
    public native void glPushMatrix();
    public native void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.Buffer p6);
    public native void glRotatef(float p0, float p1, float p2, float p3);
    public native void glRotatex(int p0, int p1, int p2, int p3);
    public native void glSampleCoverage(float p0, boolean p1);
    public native void glSampleCoveragex(int p0, boolean p1);
    public native void glScalef(float p0, float p1, float p2);
    public native void glScalex(int p0, int p1, int p2);
    public native void glScissor(int p0, int p1, int p2, int p3);
    public native void glShadeModel(int p0);
    public native void glStencilFunc(int p0, int p1, int p2);
    public native void glStencilMask(int p0);
    public native void glStencilOp(int p0, int p1, int p2);
    private native void glTexCoordPointerBounds(int p0, int p1, int p2, java.nio.Buffer p3, int p4);
    public void glTexCoordPointer(int p0, int p1, int p2, java.nio.Buffer p3) {}
    public native void glTexEnvf(int p0, int p1, float p2);
    public native void glTexEnvfv(int p0, int p1, float[] p2, int p3);
    public native void glTexEnvfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glTexEnvx(int p0, int p1, int p2);
    public native void glTexEnvxv(int p0, int p1, int[] p2, int p3);
    public native void glTexEnvxv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.Buffer p8);
    public native void glTexParameterf(int p0, int p1, float p2);
    public native void glTexParameterx(int p0, int p1, int p2);
    public native void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.Buffer p8);
    public native void glTranslatef(float p0, float p1, float p2);
    public native void glTranslatex(int p0, int p1, int p2);
    private native void glVertexPointerBounds(int p0, int p1, int p2, java.nio.Buffer p3, int p4);
    public void glVertexPointer(int p0, int p1, int p2, java.nio.Buffer p3) {}
    public native void glViewport(int p0, int p1, int p2, int p3);
    public native int glQueryMatrixxOES(int[] p0, int p1, int[] p2, int p3);
    public native int glQueryMatrixxOES(java.nio.IntBuffer p0, java.nio.IntBuffer p1);
    public native void glBindBuffer(int p0, int p1);
    public native void glBufferData(int p0, int p1, java.nio.Buffer p2, int p3);
    public native void glBufferSubData(int p0, int p1, int p2, java.nio.Buffer p3);
    public native void glClipPlanef(int p0, float[] p1, int p2);
    public native void glClipPlanef(int p0, java.nio.FloatBuffer p1);
    public native void glClipPlanex(int p0, int[] p1, int p2);
    public native void glClipPlanex(int p0, java.nio.IntBuffer p1);
    public native void glColor4ub(byte p0, byte p1, byte p2, byte p3);
    public native void glColorPointer(int p0, int p1, int p2, int p3);
    public native void glDeleteBuffers(int p0, int[] p1, int p2);
    public native void glDeleteBuffers(int p0, java.nio.IntBuffer p1);
    public native void glDrawElements(int p0, int p1, int p2, int p3);
    public native void glGenBuffers(int p0, int[] p1, int p2);
    public native void glGenBuffers(int p0, java.nio.IntBuffer p1);
    public native void glGetBooleanv(int p0, boolean[] p1, int p2);
    public native void glGetBooleanv(int p0, java.nio.IntBuffer p1);
    public native void glGetBufferParameteriv(int p0, int p1, int[] p2, int p3);
    public native void glGetBufferParameteriv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glGetClipPlanef(int p0, float[] p1, int p2);
    public native void glGetClipPlanef(int p0, java.nio.FloatBuffer p1);
    public native void glGetClipPlanex(int p0, int[] p1, int p2);
    public native void glGetClipPlanex(int p0, java.nio.IntBuffer p1);
    public native void glGetFixedv(int p0, int[] p1, int p2);
    public native void glGetFixedv(int p0, java.nio.IntBuffer p1);
    public native void glGetFloatv(int p0, float[] p1, int p2);
    public native void glGetFloatv(int p0, java.nio.FloatBuffer p1);
    public native void glGetLightfv(int p0, int p1, float[] p2, int p3);
    public native void glGetLightfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glGetLightxv(int p0, int p1, int[] p2, int p3);
    public native void glGetLightxv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glGetMaterialfv(int p0, int p1, float[] p2, int p3);
    public native void glGetMaterialfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glGetMaterialxv(int p0, int p1, int[] p2, int p3);
    public native void glGetMaterialxv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glGetTexEnviv(int p0, int p1, int[] p2, int p3);
    public native void glGetTexEnviv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glGetTexEnvxv(int p0, int p1, int[] p2, int p3);
    public native void glGetTexEnvxv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glGetTexParameterfv(int p0, int p1, float[] p2, int p3);
    public native void glGetTexParameterfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glGetTexParameteriv(int p0, int p1, int[] p2, int p3);
    public native void glGetTexParameteriv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glGetTexParameterxv(int p0, int p1, int[] p2, int p3);
    public native void glGetTexParameterxv(int p0, int p1, java.nio.IntBuffer p2);
    public native boolean glIsBuffer(int p0);
    public native boolean glIsEnabled(int p0);
    public native boolean glIsTexture(int p0);
    public native void glNormalPointer(int p0, int p1, int p2);
    public native void glPointParameterf(int p0, float p1);
    public native void glPointParameterfv(int p0, float[] p1, int p2);
    public native void glPointParameterfv(int p0, java.nio.FloatBuffer p1);
    public native void glPointParameterx(int p0, int p1);
    public native void glPointParameterxv(int p0, int[] p1, int p2);
    public native void glPointParameterxv(int p0, java.nio.IntBuffer p1);
    private native void glPointSizePointerOESBounds(int p0, int p1, java.nio.Buffer p2, int p3);
    public void glPointSizePointerOES(int p0, int p1, java.nio.Buffer p2) {}
    public native void glTexCoordPointer(int p0, int p1, int p2, int p3);
    public native void glTexEnvi(int p0, int p1, int p2);
    public native void glTexEnviv(int p0, int p1, int[] p2, int p3);
    public native void glTexEnviv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glTexParameterfv(int p0, int p1, float[] p2, int p3);
    public native void glTexParameterfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glTexParameteri(int p0, int p1, int p2);
    public native void glTexParameteriv(int p0, int p1, int[] p2, int p3);
    public native void glTexParameteriv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glTexParameterxv(int p0, int p1, int[] p2, int p3);
    public native void glTexParameterxv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glVertexPointer(int p0, int p1, int p2, int p3);
    public native void glCurrentPaletteMatrixOES(int p0);
    public native void glDrawTexfOES(float p0, float p1, float p2, float p3, float p4);
    public native void glDrawTexfvOES(float[] p0, int p1);
    public native void glDrawTexfvOES(java.nio.FloatBuffer p0);
    public native void glDrawTexiOES(int p0, int p1, int p2, int p3, int p4);
    public native void glDrawTexivOES(int[] p0, int p1);
    public native void glDrawTexivOES(java.nio.IntBuffer p0);
    public native void glDrawTexsOES(short p0, short p1, short p2, short p3, short p4);
    public native void glDrawTexsvOES(short[] p0, int p1);
    public native void glDrawTexsvOES(java.nio.ShortBuffer p0);
    public native void glDrawTexxOES(int p0, int p1, int p2, int p3, int p4);
    public native void glDrawTexxvOES(int[] p0, int p1);
    public native void glDrawTexxvOES(java.nio.IntBuffer p0);
    public native void glLoadPaletteFromModelViewMatrixOES();
    private native void glMatrixIndexPointerOESBounds(int p0, int p1, int p2, java.nio.Buffer p3, int p4);
    public void glMatrixIndexPointerOES(int p0, int p1, int p2, java.nio.Buffer p3) {}
    public native void glMatrixIndexPointerOES(int p0, int p1, int p2, int p3);
    private native void glWeightPointerOESBounds(int p0, int p1, int p2, java.nio.Buffer p3, int p4);
    public void glWeightPointerOES(int p0, int p1, int p2, java.nio.Buffer p3) {}
    public native void glWeightPointerOES(int p0, int p1, int p2, int p3);
    public native void glBindFramebufferOES(int p0, int p1);
    public native void glBindRenderbufferOES(int p0, int p1);
    public native void glBlendEquation(int p0);
    public native void glBlendEquationSeparate(int p0, int p1);
    public native void glBlendFuncSeparate(int p0, int p1, int p2, int p3);
    public native int glCheckFramebufferStatusOES(int p0);
    public native void glDeleteFramebuffersOES(int p0, int[] p1, int p2);
    public native void glDeleteFramebuffersOES(int p0, java.nio.IntBuffer p1);
    public native void glDeleteRenderbuffersOES(int p0, int[] p1, int p2);
    public native void glDeleteRenderbuffersOES(int p0, java.nio.IntBuffer p1);
    public native void glFramebufferRenderbufferOES(int p0, int p1, int p2, int p3);
    public native void glFramebufferTexture2DOES(int p0, int p1, int p2, int p3, int p4);
    public native void glGenerateMipmapOES(int p0);
    public native void glGenFramebuffersOES(int p0, int[] p1, int p2);
    public native void glGenFramebuffersOES(int p0, java.nio.IntBuffer p1);
    public native void glGenRenderbuffersOES(int p0, int[] p1, int p2);
    public native void glGenRenderbuffersOES(int p0, java.nio.IntBuffer p1);
    public native void glGetFramebufferAttachmentParameterivOES(int p0, int p1, int p2, int[] p3, int p4);
    public native void glGetFramebufferAttachmentParameterivOES(int p0, int p1, int p2, java.nio.IntBuffer p3);
    public native void glGetRenderbufferParameterivOES(int p0, int p1, int[] p2, int p3);
    public native void glGetRenderbufferParameterivOES(int p0, int p1, java.nio.IntBuffer p2);
    public native void glGetTexGenfv(int p0, int p1, float[] p2, int p3);
    public native void glGetTexGenfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glGetTexGeniv(int p0, int p1, int[] p2, int p3);
    public native void glGetTexGeniv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glGetTexGenxv(int p0, int p1, int[] p2, int p3);
    public native void glGetTexGenxv(int p0, int p1, java.nio.IntBuffer p2);
    public native boolean glIsFramebufferOES(int p0);
    public native boolean glIsRenderbufferOES(int p0);
    public native void glRenderbufferStorageOES(int p0, int p1, int p2, int p3);
    public native void glTexGenf(int p0, int p1, float p2);
    public native void glTexGenfv(int p0, int p1, float[] p2, int p3);
    public native void glTexGenfv(int p0, int p1, java.nio.FloatBuffer p2);
    public native void glTexGeni(int p0, int p1, int p2);
    public native void glTexGeniv(int p0, int p1, int[] p2, int p3);
    public native void glTexGeniv(int p0, int p1, java.nio.IntBuffer p2);
    public native void glTexGenx(int p0, int p1, int p2);
    public native void glTexGenxv(int p0, int p1, int[] p2, int p3);
    public native void glTexGenxv(int p0, int p1, java.nio.IntBuffer p2);
}
