package com.android.window.flags;

public final class FeatureFlagsImpl implements com.android.window.flags.FeatureFlags {
    public FeatureFlagsImpl() {}
    public boolean activityEmbeddingAnimationCustomizationFlag() { return false; }
    public boolean activityEmbeddingInteractiveDividerFlag() { return false; }
    public boolean activityEmbeddingOverlayPresentationFlag() { return false; }
    public boolean activitySnapshotByDefault() { return false; }
    public boolean activityWindowInfoFlag() { return false; }
    public boolean allowDisableActivityRecordInputSink() { return false; }
    public boolean allowHideScmButton() { return false; }
    public boolean allowsScreenSizeDecoupledFromStatusBarAndCutout() { return false; }
    public boolean alwaysDeferTransitionWhenApplyWct() { return false; }
    public boolean alwaysDrawMagnificationFullscreenBorder() { return false; }
    public boolean alwaysUpdateWallpaperPermission() { return false; }
    public boolean appCompatPropertiesApi() { return false; }
    public boolean appCompatRefactoring() { return false; }
    public boolean balDontBringExistingBackgroundTaskStackToFg() { return false; }
    public boolean balImproveRealCallerVisibilityCheck() { return false; }
    public boolean balImprovedMetrics() { return false; }
    public boolean balRequireOptInByPendingIntentCreator() { return false; }
    public boolean balRequireOptInSameUid() { return false; }
    public boolean balRespectAppSwitchStateWhenCheckBoundByForegroundUid() { return false; }
    public boolean balShowToasts() { return false; }
    public boolean balShowToastsBlocked() { return false; }
    public boolean blastSyncNotificationShadeOnDisplaySwitch() { return false; }
    public boolean bundleClientTransactionFlag() { return false; }
    public boolean cameraCompatForFreeform() { return false; }
    public boolean closeToSquareConfigIncludesStatusBar() { return false; }
    public boolean configurableFontScaleDefault() { return false; }
    public boolean coverDisplayOptIn() { return false; }
    public boolean deferDisplayUpdates() { return false; }
    public boolean delayNotificationToMagnificationWhenRecentsWindowToFrontTransition() { return false; }
    public boolean delegateUnhandledDrags() { return false; }
    public boolean deleteCaptureDisplay() { return false; }
    public boolean density390Api() { return false; }
    public boolean disableObjectPool() { return false; }
    public boolean disableThinLetterboxingPolicy() { return false; }
    public boolean doNotCheckIntersectionWhenNonMagnifiableWindowTransitions() { return false; }
    public boolean drawSnapshotAspectRatioMatch() { return false; }
    public boolean edgeToEdgeByDefault() { return false; }
    public boolean embeddedActivityBackNavFlag() { return false; }
    public boolean enableAdditionalWindowsAboveStatusBar() { return false; }
    public boolean enableAppHeaderWithTaskDensity() { return false; }
    public boolean enableBufferTransformHintFromDisplay() { return false; }
    public boolean enableCameraCompatForDesktopWindowing() { return false; }
    public boolean enableCompatuiSysuiLauncher() { return false; }
    public boolean enableDesktopWindowingImmersiveHandleHiding() { return false; }
    public boolean enableDesktopWindowingModalsPolicy() { return false; }
    public boolean enableDesktopWindowingMode() { return false; }
    public boolean enableDesktopWindowingQuickSwitch() { return false; }
    public boolean enableDesktopWindowingScvhCache() { return false; }
    public boolean enableDesktopWindowingSizeConstraints() { return false; }
    public boolean enableDesktopWindowingTaskLimit() { return false; }
    public boolean enableDesktopWindowingTaskbarRunningApps() { return false; }
    public boolean enableDesktopWindowingWallpaperActivity() { return false; }
    public boolean enableScaledResizing() { return false; }
    public boolean enableTaskStackObserverInShell() { return false; }
    public boolean enableThemedAppHeaders() { return false; }
    public boolean enableWindowingDynamicInitialBounds() { return false; }
    public boolean enableWindowingEdgeDragResize() { return false; }
    public boolean enableWmExtensionsForAllFlag() { return false; }
    public boolean enforceEdgeToEdge() { return false; }
    public boolean ensureWallpaperInTransitions() { return false; }
    public boolean explicitRefreshRateHints() { return false; }
    public boolean fifoPriorityForMajorUiProcesses() { return false; }
    public boolean fixNoContainerUpdateWithoutResize() { return false; }
    public boolean fixPipRestoreToOverlay() { return false; }
    public boolean fullscreenDimFlag() { return false; }
    public boolean getDimmerOnClosing() { return false; }
    public boolean immersiveAppRepositioning() { return false; }
    public boolean insetsControlChangedItem() { return false; }
    public boolean insetsControlSeq() { return false; }
    public boolean insetsDecoupledConfiguration() { return false; }
    public boolean introduceSmootherDimmer() { return false; }
    public boolean keyguardAppearTransition() { return false; }
    public boolean letterboxBackgroundWallpaper() { return false; }
    public boolean movableCutoutConfiguration() { return false; }
    public boolean moveAnimationOptionsToChange() { return false; }
    public boolean multiCrop() { return false; }
    public boolean navBarTransparentByDefault() { return false; }
    public boolean noConsecutiveVisibilityEvents() { return false; }
    public boolean noVisibilityEventOnDisplayStateChange() { return false; }
    public boolean offloadColorExtraction() { return false; }
    public boolean predictiveBackSystemAnims() { return false; }
    public boolean rearDisplayDisableForceDesktopSystemDecorations() { return false; }
    public boolean releaseSnapshotAggressively() { return false; }
    public boolean removePrepareSurfaceInPlacement() { return false; }
    public boolean screenRecordingCallbacks() { return false; }
    public boolean sdkDesiredPresentTime() { return false; }
    public boolean secureWindowState() { return false; }
    public boolean setScPropertiesInClient() { return false; }
    public boolean skipSleepingWhenSwitchingDisplay() { return false; }
    public boolean supportsMultiInstanceSystemUi() { return false; }
    public boolean surfaceControlInputReceiver() { return false; }
    public boolean surfaceTrustedOverlay() { return false; }
    public boolean syncScreenCapture() { return false; }
    public boolean taskFragmentSystemOrganizerFlag() { return false; }
    public boolean transitReadyTracking() { return false; }
    public boolean trustedPresentationListenerForWindow() { return false; }
    public boolean untrustedEmbeddingAnyAppPermission() { return false; }
    public boolean untrustedEmbeddingStateSharing() { return false; }
    public boolean useWindowOriginalTouchableRegionWhenMagnificationRecomputeBounds() { return false; }
    public boolean userMinAspectRatioAppDefault() { return false; }
    public boolean waitForTransitionOnDisplaySwitch() { return false; }
    public boolean wallpaperOffsetAsync() { return false; }
    public boolean windowSessionRelayoutInfo() { return false; }
    public boolean windowTokenConfigThreadSafe() { return false; }
}
