package android.window;

public enum DesktopExperienceFlags {
    BASE_DENSITY_FOR_EXTERNAL_DISPLAYS,
    CONNECTED_DISPLAYS_CURSOR,
    DISPLAY_TOPOLOGY,
    ENABLE_ACTIVITY_EMBEDDING_SUPPORT_FOR_CONNECTED_DISPLAYS,
    ENABLE_APP_HANDLE_POSITION_REPORTING,
    ENABLE_BLOCK_NON_DESKTOP_DISPLAY_WINDOW_DRAG_BUGFIX,
    ENABLE_BUG_FIXES_FOR_SECONDARY_DISPLAY,
    ENABLE_CONNECTED_DISPLAYS_DND,
    ENABLE_CONNECTED_DISPLAYS_PIP,
    ENABLE_CONNECTED_DISPLAYS_WALLPAPER,
    ENABLE_CONNECTED_DISPLAYS_WINDOW_DRAG,
    ENABLE_DEFAULT_DESK_WITHOUT_WARMUP_MIGRATION,
    ENABLE_DEFAULT_DISPLAY_IN_TOPOLOGY_SWITCH,
    ENABLE_DESKTOP_APP_HEADER_STATE_CHANGE_ANNOUNCEMENTS,
    ENABLE_DESKTOP_APP_LAUNCH_BUGFIX,
    ENABLE_DESKTOP_CLOSE_TASK_ANIMATION_IN_DTC_BUGFIX,
    ENABLE_DESKTOP_FIRST_BASED_DEFAULT_TO_DESKTOP_BUGFIX,
    ENABLE_DESKTOP_FIRST_BASED_DRAG_TO_MAXIMIZE,
    ENABLE_DESKTOP_FIRST_FULLSCREEN_REFOCUS_BUGFIX,
    ENABLE_DESKTOP_FIRST_LISTENER,
    ENABLE_DESKTOP_IME_BUGFIX,
    ENABLE_DESKTOP_SPLITSCREEN_TRANSITION_BUGFIX,
    ENABLE_DESKTOP_TAB_TEARING_LAUNCH_ANIMATION,
    ENABLE_DESKTOP_TASKBAR_ON_FREEFORM_DISPLAYS,
    ENABLE_DESKTOP_TASK_LIMIT_SEPARATE_TRANSITION,
    ENABLE_DESKTOP_WINDOWING_PIP,
    ENABLE_DESKTOP_WINDOWING_PIP_IN_OVERVIEW_BUGFIX,
    ENABLE_DISPLAY_COMPAT_MODE,
    ENABLE_DISPLAY_CONTENT_MODE_MANAGEMENT,
    ENABLE_DISPLAY_DISCONNECT_INTERACTION,
    ENABLE_DISPLAY_FOCUS_IN_SHELL_TRANSITIONS,
    ENABLE_DISPLAY_RECONNECT_INTERACTION,
    ENABLE_DISPLAY_WINDOWING_MODE_SWITCHING,
    ENABLE_DRAGGING_PIP_ACROSS_DISPLAYS,
    ENABLE_DRAG_TO_MAXIMIZE,
    ENABLE_DYNAMIC_RADIUS_COMPUTATION_BUGFIX,
    ENABLE_EMPTY_DESK_ON_MINIMIZE,
    ENABLE_FREEFORM_BOX_SHADOWS,
    ENABLE_FREEFORM_DISPLAY_LAUNCH_PARAMS,
    ENABLE_FULLSCREEN_WINDOW_CONTROLS,
    ENABLE_INDEPENDENT_BACK_IN_PROJECTED,
    ENABLE_KEYBOARD_SHORTCUTS_TO_SWITCH_DESKS,
    ENABLE_MODALS_FULLSCREEN_WITH_PLATFORM_SIGNATURE,
    ENABLE_MOVE_TO_NEXT_DISPLAY_SHORTCUT,
    ENABLE_MULTIDISPLAY_TRACKPAD_BACK_GESTURE,
    ENABLE_MULTIPLE_DESKTOPS_ACTIVATION_IN_DESKTOP_FIRST_DISPLAYS,
    ENABLE_MULTIPLE_DESKTOPS_BACKEND,
    ENABLE_MULTIPLE_DESKTOPS_FRONTEND,
    ENABLE_NESTED_TASKS_WITH_INDEPENDENT_BOUNDS_BUGFIX,
    ENABLE_NON_DEFAULT_DISPLAY_SPLIT,
    ENABLE_NO_WINDOW_DECORATION_FOR_DESKS,
    ENABLE_PARALLEL_CD_TRANSITIONS_DURING_RECENTS,
    ENABLE_PERSISTING_DISPLAY_SIZE_FOR_CONNECTED_DISPLAYS,
    ENABLE_PER_DISPLAY_DESKTOP_WALLPAPER_ACTIVITY,
    ENABLE_PINNING_APP_WITH_CONTEXT_MENU,
    ENABLE_PRESENTATION_FOR_CONNECTED_DISPLAYS,
    ENABLE_PROJECTED_DISPLAY_DESKTOP_MODE,
    ENABLE_REJECT_HOME_TRANSITION,
    ENABLE_REQUEST_FULLSCREEN_REFACTOR,
    ENABLE_RESTART_MENU_FOR_CONNECTED_DISPLAYS,
    ENABLE_RESTRICT_FREEFORM_HIDDEN_SYSTEM_BARS_TO_FILLING_TASKS,
    ENABLE_SEE_THROUGH_TASK_FRAGMENTS,
    ENABLE_SIZE_COMPAT_MODE_IMPROVEMENTS_FOR_CONNECTED_DISPLAYS,
    ENABLE_SYS_DECORS_CALLBACKS_VIA_WM,
    ENABLE_TALL_APP_HEADERS,
    ENABLE_TASKBAR_CONNECTED_DISPLAYS,
    ENABLE_TASKBAR_RECENT_TASKS_THROTTLE_BUGFIX,
    ENABLE_TILE_RESIZING,
    ENABLE_WINDOWING_TASK_STACK_ORDER_BUGFIX,
    ENABLE_WINDOWING_TRANSITION_HANDLERS_OBSERVERS,
    ENABLE_WINDOW_DECORATION_REFACTOR,
    ENABLE_WINDOW_REPOSITIONING_API,
    ENTER_DESKTOP_BY_DEFAULT_ON_FREEFORM_DISPLAYS,
    EXCLUDE_DESK_ROOTS_FROM_DESKTOP_TASKS,
    FORCE_CLOSE_TOP_TRANSPARENT_FULLSCREEN_TASK,
    FORM_FACTOR_BASED_DESKTOP_FIRST_SWITCH,
    PRESERVE_RECENTS_TASK_CONFIGURATION_ON_RELAUNCH,
    REPARENT_WINDOW_TOKEN_API,
    RESPECT_FULLSCREEN_ACTIVITY_OPTION_IN_DESKTOP_LAUNCH_PARAMS,
    SKIP_DEACTIVATION_OF_DESK_WITH_NOTHING_IN_FRONT,
    USE_RESOURCES_FROM_CONTEXT_TO_CREATE_DRAWABLE_ICONS;
    public static final java.lang.String SYSTEM_PROPERTY_NAME = "persist.wm.debug.desktop_experience_devopts";
    public static final java.lang.String SYSTEM_PROPERTY_OVERRIDE_PREFIX = "persist.wm.debug.desktop_experience.add_dev_option.";
    static boolean isDesktopExperienceDevOptionSupported() { return false; }
    public boolean isTrue() { return false; }
    public boolean getFlagValue() { return false; }
    public java.lang.String getFlagName() { return null; }
    public boolean isOverridable() { return false; }
    public static java.util.List<android.window.DesktopExperienceFlags.DesktopExperienceFlag> getRegisteredFlags() { return null; }
    public static boolean getToggleOverride() { return false; }
    static android.content.Context getApplicationContext() { return null; }

    public static class DesktopExperienceFlag {
        public DesktopExperienceFlag(java.util.function.BooleanSupplier p0, boolean p1, java.lang.String p2) {}
        public boolean isTrue() { return false; }
        public java.lang.String getFlagName() { return null; }
        public boolean getFlagValue() { return false; }
        public boolean isOverridable() { return false; }
    }
}
