package android.window;

public enum DesktopModeFlags {
    DISABLE_DESKTOP_LAUNCH_PARAMS_OUTSIDE_DESKTOP_BUG_FIX,
    DISABLE_NON_RESIZABLE_APP_SNAP_RESIZE,
    ENABLE_ACCESSIBLE_CUSTOM_HEADERS,
    ENABLE_APP_HEADER_WITH_TASK_DENSITY,
    ENABLE_CAMERA_COMPAT_SIMULATE_REQUESTED_ORIENTATION,
    ENABLE_CAPTION_COMPAT_INSET_FORCE_CONSUMPTION,
    ENABLE_CAPTION_COMPAT_INSET_FORCE_CONSUMPTION_ALWAYS,
    ENABLE_CASCADING_WINDOWS,
    ENABLE_DESKTOP_APP_HANDLE_ANIMATION,
    ENABLE_DESKTOP_APP_LAUNCH_ALTTAB_TRANSITIONS_BUGFIX,
    ENABLE_DESKTOP_APP_LAUNCH_TRANSITIONS_BUGFIX,
    ENABLE_DESKTOP_CLOSE_SHORTCUT_BUGFIX,
    ENABLE_DESKTOP_COMPAT_UI_VISIBILITY_STATUS,
    ENABLE_DESKTOP_IMMERSIVE_DRAG_BUGFIX,
    ENABLE_DESKTOP_INDICATOR_IN_SEPARATE_THREAD_BUGFIX,
    ENABLE_DESKTOP_OPENING_DEEPLINK_MINIMIZE_ANIMATION_BUGFIX,
    ENABLE_DESKTOP_RECENTS_TRANSITIONS_CORNERS_BUGFIX,
    ENABLE_DESKTOP_SKIP_COMPAT_UI_EDUCATION_IN_DESKTOP_MODE_BUGFIX,
    ENABLE_DESKTOP_SYSTEM_DIALOGS_TRANSITIONS,
    ENABLE_DESKTOP_TAB_TEARING_MINIMIZE_ANIMATION_BUGFIX,
    ENABLE_DESKTOP_TRAMPOLINE_CLOSE_ANIMATION_BUGFIX,
    ENABLE_DESKTOP_WALLPAPER_ACTIVITY_FOR_SYSTEM_USER,
    ENABLE_DESKTOP_WINDOWING_APP_TO_WEB,
    ENABLE_DESKTOP_WINDOWING_APP_TO_WEB_EDUCATION,
    ENABLE_DESKTOP_WINDOWING_BACK_NAVIGATION,
    ENABLE_DESKTOP_WINDOWING_ENTER_TRANSITIONS_BUGFIX,
    ENABLE_DESKTOP_WINDOWING_EXIT_BY_MINIMIZE_TRANSITION_BUGFIX,
    ENABLE_DESKTOP_WINDOWING_EXIT_TRANSITIONS_BUGFIX,
    ENABLE_DESKTOP_WINDOWING_HSUM,
    ENABLE_DESKTOP_WINDOWING_IMMERSIVE_HANDLE_HIDING,
    ENABLE_DESKTOP_WINDOWING_MODALS_POLICY,
    ENABLE_DESKTOP_WINDOWING_MODE,
    ENABLE_DESKTOP_WINDOWING_MULTI_INSTANCE_FEATURES,
    ENABLE_DESKTOP_WINDOWING_PERSISTENCE,
    ENABLE_DESKTOP_WINDOWING_QUICK_SWITCH,
    ENABLE_DESKTOP_WINDOWING_SCVH_CACHE,
    ENABLE_DESKTOP_WINDOWING_SIZE_CONSTRAINTS,
    ENABLE_DESKTOP_WINDOWING_TASKBAR_RUNNING_APPS,
    ENABLE_DESKTOP_WINDOWING_TASK_LIMIT,
    ENABLE_DESKTOP_WINDOWING_WALLPAPER_ACTIVITY,
    ENABLE_DRAG_RESIZE_SET_UP_IN_BG_THREAD,
    ENABLE_DRAG_TO_DESKTOP_INCOMING_TRANSITIONS_BUGFIX,
    ENABLE_FULLY_IMMERSIVE_IN_DESKTOP,
    ENABLE_HANDLE_INPUT_FIX,
    ENABLE_HOLD_TO_DRAG_APP_HANDLE,
    ENABLE_INPUT_LAYER_TRANSITION_FIX,
    ENABLE_MINIMIZE_BUTTON,
    ENABLE_MODALS_FULLSCREEN_WITH_PERMISSIONS,
    ENABLE_OPAQUE_BACKGROUND_FOR_TRANSPARENT_WINDOWS,
    ENABLE_QUICKSWITCH_DESKTOP_SPLIT_BUGFIX,
    ENABLE_REQUEST_FULLSCREEN_BUGFIX,
    ENABLE_RESIZING_METRICS,
    ENABLE_RESTORE_TO_PREVIOUS_SIZE_FROM_DESKTOP_IMMERSIVE,
    ENABLE_SHELL_INITIAL_BOUNDS_REGRESSION_BUG_FIX,
    ENABLE_START_LAUNCH_TRANSITION_FROM_TASKBAR_BUGFIX,
    ENABLE_TASKBAR_OVERFLOW,
    ENABLE_TASKBAR_RECENTS_LAYOUT_TRANSITION,
    ENABLE_TASK_RESIZING_KEYBOARD_SHORTCUTS,
    ENABLE_TASK_STACK_OBSERVER_IN_SHELL,
    ENABLE_THEMED_APP_HEADERS,
    ENABLE_TOP_VISIBLE_ROOT_TASK_PER_USER_TRACKING,
    ENABLE_VISUAL_INDICATOR_IN_TRANSITION_BUGFIX,
    ENABLE_WINDOWING_DYNAMIC_INITIAL_BOUNDS,
    ENABLE_WINDOWING_EDGE_DRAG_RESIZE,
    ENABLE_WINDOWING_SCALED_RESIZING,
    EXCLUDE_CAPTION_FROM_APP_BOUNDS,
    IGNORE_ASPECT_RATIO_RESTRICTIONS_FOR_RESIZEABLE_FREEFORM_ACTIVITIES,
    INCLUDE_TOP_TRANSPARENT_FULLSCREEN_TASK_IN_DESKTOP_HEURISTIC,
    INHERIT_TASK_BOUNDS_FOR_TRAMPOLINE_TASK_LAUNCHES,
    SKIP_DECOR_VIEW_RELAYOUT_WHEN_CLOSING_BUGFIX;
    public boolean isTrue() { return false; }
    public static boolean isDesktopModeForcedEnabled() { return false; }

    public static class DesktopModeFlag {
        public DesktopModeFlag(java.util.function.BooleanSupplier p0, boolean p1) {}
        public boolean isTrue() { return false; }
    }

    public static enum ToggleOverride {
        OVERRIDE_UNSET,
        OVERRIDE_OFF,
        OVERRIDE_ON;
        public int getSetting() { return 0; }
        public static android.window.DesktopModeFlags.ToggleOverride fromSetting(int p0, android.window.DesktopModeFlags.ToggleOverride p1) { return null; }
    }
}
