package com.android.internal.hidden_from_bootclasspath.android.view.accessibility;

public interface FeatureFlags {
    public boolean a11yCharacterInWindowApi();
    public boolean a11yExpansionStateApi();
    public boolean a11yIsRequiredApi();
    public boolean a11yIsVisitedApi();
    public boolean a11yOverlayCallbacks();
    public boolean a11ySelectionApi();
    public boolean a11ySequentialFocusStartingPoint();
    public boolean a11ySortDirectionApi();
    public boolean allowShortcutChooserOnLockscreen();
    public boolean brailleDisplayHid();
    public boolean cleanupAccessibilityWarningDialog();
    public boolean collectionInfoItemCounts();
    public boolean copyEventsForGestureDetection();
    public boolean deprecateAccessibilityAnnouncementApis();
    public boolean deprecateAniLabelForApis();
    public boolean enableRefreshWindowInfo();
    public boolean enableSystemPinchZoomGesture();
    public boolean enableTrustedAccessibilityServiceApi();
    public boolean enableTypeWindowControl();
    public boolean flashNotificationSystemApi();
    public boolean focusRectMinSize();
    public boolean forceInvertColor();
    public boolean globalActionMediaPlayPause();
    public boolean globalActionMenu();
    public boolean granularScrolling();
    public boolean ignoreUnimportantRoot();
    public boolean indeterminateRangeInfo();
    public boolean motionEventObserving();
    public boolean navbarFlipOrderOption();
    public boolean preventA11yNontoolFromInjectingIntoSensitiveViews();
    public boolean preventLeakingViewrootimpl();
    public boolean reduceWindowContentChangedEventThrottle();
    public boolean removeChildHoverCheckForTouchExploration();
    public boolean requestRectangleWithSource();
    public boolean restoreA11yShortcutTargetService();
    public boolean skipAccessibilityWarningDialogForTrustedServices();
    public boolean supplementalDescription();
    public boolean supportMultipleLabeledby();
    public boolean supportSystemPinchZoomOptOutApis();
    public boolean textCursorBlinkInterval();
    public boolean triStateChecked();
    public boolean updateAlwaysOnA11yService();
}
