package android.content.pm.parsing;

public interface ParsingPackage extends android.content.pm.parsing.ParsingPackageRead {
    public android.content.pm.parsing.ParsingPackage addActivity(android.content.pm.parsing.component.ParsedActivity p0);
    public android.content.pm.parsing.ParsingPackage addAdoptPermission(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addConfigPreference(android.content.pm.ConfigurationInfo p0);
    public android.content.pm.parsing.ParsingPackage addFeatureGroup(android.content.pm.FeatureGroupInfo p0);
    public android.content.pm.parsing.ParsingPackage addImplicitPermission(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addInstrumentation(android.content.pm.parsing.component.ParsedInstrumentation p0);
    public android.content.pm.parsing.ParsingPackage addKeySet(java.lang.String p0, java.security.PublicKey p1);
    public android.content.pm.parsing.ParsingPackage addLibraryName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addOriginalPackage(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addOverlayable(java.lang.String p0, java.lang.String p1);
    public android.content.pm.parsing.ParsingPackage addPermission(android.content.pm.parsing.component.ParsedPermission p0);
    public android.content.pm.parsing.ParsingPackage addPermissionGroup(android.content.pm.parsing.component.ParsedPermissionGroup p0);
    public android.content.pm.parsing.ParsingPackage addPreferredActivityFilter(java.lang.String p0, android.content.pm.parsing.component.ParsedIntentInfo p1);
    public android.content.pm.parsing.ParsingPackage addProperty(android.content.pm.PackageManager.Property p0);
    public android.content.pm.parsing.ParsingPackage addProtectedBroadcast(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addProvider(android.content.pm.parsing.component.ParsedProvider p0);
    public android.content.pm.parsing.ParsingPackage addAttribution(android.content.pm.parsing.component.ParsedAttribution p0);
    public android.content.pm.parsing.ParsingPackage addReceiver(android.content.pm.parsing.component.ParsedActivity p0);
    public android.content.pm.parsing.ParsingPackage addReqFeature(android.content.pm.FeatureInfo p0);
    public android.content.pm.parsing.ParsingPackage addUsesPermission(android.content.pm.parsing.component.ParsedUsesPermission p0);
    public android.content.pm.parsing.ParsingPackage addService(android.content.pm.parsing.component.ParsedService p0);
    public android.content.pm.parsing.ParsingPackage addUsesLibrary(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addUsesOptionalLibrary(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addUsesNativeLibrary(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addUsesOptionalNativeLibrary(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addUsesStaticLibrary(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addUsesStaticLibraryCertDigests(java.lang.String[] p0);
    public android.content.pm.parsing.ParsingPackage addUsesStaticLibraryVersion(long p0);
    public android.content.pm.parsing.ParsingPackage addQueriesIntent(android.content.Intent p0);
    public android.content.pm.parsing.ParsingPackage addQueriesPackage(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage addQueriesProvider(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setProcesses(java.util.Map<java.lang.String, android.content.pm.parsing.component.ParsedProcess> p0);
    public android.content.pm.parsing.ParsingPackage asSplit(java.lang.String[] p0, java.lang.String[] p1, int[] p2, android.util.SparseArray<int[]> p3);
    public android.content.pm.parsing.ParsingPackage setMetaData(android.os.Bundle p0);
    public android.content.pm.parsing.ParsingPackage setForceQueryable(boolean p0);
    public android.content.pm.parsing.ParsingPackage setMaxAspectRatio(float p0);
    public android.content.pm.parsing.ParsingPackage setMinAspectRatio(float p0);
    public android.content.pm.parsing.ParsingPackage setPermission(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setProcessName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setSharedUserId(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setStaticSharedLibName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setTaskAffinity(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setTargetSdkVersion(int p0);
    public android.content.pm.parsing.ParsingPackage setUiOptions(int p0);
    public android.content.pm.parsing.ParsingPackage setBaseHardwareAccelerated(boolean p0);
    public android.content.pm.parsing.ParsingPackage setResizeableActivity(java.lang.Boolean p0);
    public android.content.pm.parsing.ParsingPackage setResizeableActivityViaSdkVersion(boolean p0);
    public android.content.pm.parsing.ParsingPackage setAllowAudioPlaybackCapture(boolean p0);
    public android.content.pm.parsing.ParsingPackage setAllowBackup(boolean p0);
    public android.content.pm.parsing.ParsingPackage setAllowClearUserData(boolean p0);
    public android.content.pm.parsing.ParsingPackage setAllowClearUserDataOnFailedRestore(boolean p0);
    public android.content.pm.parsing.ParsingPackage setAllowTaskReparenting(boolean p0);
    public android.content.pm.parsing.ParsingPackage setOverlay(boolean p0);
    public android.content.pm.parsing.ParsingPackage setBackupInForeground(boolean p0);
    public android.content.pm.parsing.ParsingPackage setCantSaveState(boolean p0);
    public android.content.pm.parsing.ParsingPackage setDebuggable(boolean p0);
    public android.content.pm.parsing.ParsingPackage setDefaultToDeviceProtectedStorage(boolean p0);
    public android.content.pm.parsing.ParsingPackage setDirectBootAware(boolean p0);
    public android.content.pm.parsing.ParsingPackage setExternalStorage(boolean p0);
    public android.content.pm.parsing.ParsingPackage setExtractNativeLibs(boolean p0);
    public android.content.pm.parsing.ParsingPackage setFullBackupOnly(boolean p0);
    public android.content.pm.parsing.ParsingPackage setHasCode(boolean p0);
    public android.content.pm.parsing.ParsingPackage setHasFragileUserData(boolean p0);
    public android.content.pm.parsing.ParsingPackage setGame(boolean p0);
    public android.content.pm.parsing.ParsingPackage setIsolatedSplitLoading(boolean p0);
    public android.content.pm.parsing.ParsingPackage setKillAfterRestore(boolean p0);
    public android.content.pm.parsing.ParsingPackage setLargeHeap(boolean p0);
    public android.content.pm.parsing.ParsingPackage setMultiArch(boolean p0);
    public android.content.pm.parsing.ParsingPackage setPartiallyDirectBootAware(boolean p0);
    public android.content.pm.parsing.ParsingPackage setPersistent(boolean p0);
    public android.content.pm.parsing.ParsingPackage setProfileableByShell(boolean p0);
    public android.content.pm.parsing.ParsingPackage setProfileable(boolean p0);
    public android.content.pm.parsing.ParsingPackage setRequestLegacyExternalStorage(boolean p0);
    public android.content.pm.parsing.ParsingPackage setAllowNativeHeapPointerTagging(boolean p0);
    public android.content.pm.parsing.ParsingPackage setAutoRevokePermissions(int p0);
    public android.content.pm.parsing.ParsingPackage setPreserveLegacyExternalStorage(boolean p0);
    public android.content.pm.parsing.ParsingPackage setRestoreAnyVersion(boolean p0);
    public android.content.pm.parsing.ParsingPackage setSplitHasCode(int p0, boolean p1);
    public android.content.pm.parsing.ParsingPackage setStaticSharedLibrary(boolean p0);
    public android.content.pm.parsing.ParsingPackage setSupportsRtl(boolean p0);
    public android.content.pm.parsing.ParsingPackage setTestOnly(boolean p0);
    public android.content.pm.parsing.ParsingPackage setUseEmbeddedDex(boolean p0);
    public android.content.pm.parsing.ParsingPackage setUsesCleartextTraffic(boolean p0);
    public android.content.pm.parsing.ParsingPackage setUsesNonSdkApi(boolean p0);
    public android.content.pm.parsing.ParsingPackage setVisibleToInstantApps(boolean p0);
    public android.content.pm.parsing.ParsingPackage setVmSafeMode(boolean p0);
    public android.content.pm.parsing.ParsingPackage removeUsesOptionalLibrary(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage removeUsesOptionalNativeLibrary(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setAnyDensity(int p0);
    public android.content.pm.parsing.ParsingPackage setAppComponentFactory(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setBackupAgentName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setBanner(int p0);
    public android.content.pm.parsing.ParsingPackage setCategory(int p0);
    public android.content.pm.parsing.ParsingPackage setClassLoaderName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setClassName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setCompatibleWidthLimitDp(int p0);
    public android.content.pm.parsing.ParsingPackage setDescriptionRes(int p0);
    public android.content.pm.parsing.ParsingPackage setEnabled(boolean p0);
    public android.content.pm.parsing.ParsingPackage setGwpAsanMode(int p0);
    public android.content.pm.parsing.ParsingPackage setMemtagMode(int p0);
    public android.content.pm.parsing.ParsingPackage setNativeHeapZeroInitialized(int p0);
    public android.content.pm.parsing.ParsingPackage setRequestRawExternalStorageAccess(java.lang.Boolean p0);
    public android.content.pm.parsing.ParsingPackage setCrossProfile(boolean p0);
    public android.content.pm.parsing.ParsingPackage setFullBackupContent(int p0);
    public android.content.pm.parsing.ParsingPackage setDataExtractionRules(int p0);
    public android.content.pm.parsing.ParsingPackage setHasDomainUrls(boolean p0);
    public android.content.pm.parsing.ParsingPackage setIconRes(int p0);
    public android.content.pm.parsing.ParsingPackage setInstallLocation(int p0);
    public android.content.pm.parsing.ParsingPackage setLabelRes(int p0);
    public android.content.pm.parsing.ParsingPackage setLargestWidthLimitDp(int p0);
    public android.content.pm.parsing.ParsingPackage setLogo(int p0);
    public android.content.pm.parsing.ParsingPackage setManageSpaceActivityName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setMinExtensionVersions(android.util.SparseIntArray p0);
    public android.content.pm.parsing.ParsingPackage setMinSdkVersion(int p0);
    public android.content.pm.parsing.ParsingPackage setNetworkSecurityConfigRes(int p0);
    public android.content.pm.parsing.ParsingPackage setNonLocalizedLabel(java.lang.CharSequence p0);
    public android.content.pm.parsing.ParsingPackage setOverlayCategory(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setOverlayIsStatic(boolean p0);
    public android.content.pm.parsing.ParsingPackage setOverlayPriority(int p0);
    public android.content.pm.parsing.ParsingPackage setOverlayTarget(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setOverlayTargetName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setRealPackage(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setRequiredAccountType(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setRequiredForAllUsers(boolean p0);
    public android.content.pm.parsing.ParsingPackage setRequiresSmallestWidthDp(int p0);
    public android.content.pm.parsing.ParsingPackage setResizeable(int p0);
    public android.content.pm.parsing.ParsingPackage setRestrictUpdateHash(byte[] p0);
    public android.content.pm.parsing.ParsingPackage setRestrictedAccountType(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setRoundIconRes(int p0);
    public android.content.pm.parsing.ParsingPackage setSharedUserLabel(int p0);
    public android.content.pm.parsing.ParsingPackage setSigningDetails(android.content.pm.PackageParser.SigningDetails p0);
    public android.content.pm.parsing.ParsingPackage setSplitClassLoaderName(int p0, java.lang.String p1);
    public android.content.pm.parsing.ParsingPackage setStaticSharedLibVersion(long p0);
    public android.content.pm.parsing.ParsingPackage setSupportsLargeScreens(int p0);
    public android.content.pm.parsing.ParsingPackage setSupportsNormalScreens(int p0);
    public android.content.pm.parsing.ParsingPackage setSupportsSmallScreens(int p0);
    public android.content.pm.parsing.ParsingPackage setSupportsExtraLargeScreens(int p0);
    public android.content.pm.parsing.ParsingPackage setTargetSandboxVersion(int p0);
    public android.content.pm.parsing.ParsingPackage setTheme(int p0);
    public android.content.pm.parsing.ParsingPackage setRequestForegroundServiceExemption(boolean p0);
    public android.content.pm.parsing.ParsingPackage setUpgradeKeySets(java.util.Set<java.lang.String> p0);
    public android.content.pm.parsing.ParsingPackage setUse32BitAbi(boolean p0);
    public android.content.pm.parsing.ParsingPackage setVolumeUuid(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setZygotePreloadName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage sortActivities();
    public android.content.pm.parsing.ParsingPackage sortReceivers();
    public android.content.pm.parsing.ParsingPackage sortServices();
    public android.content.pm.parsing.ParsingPackage setBaseRevisionCode(int p0);
    public android.content.pm.parsing.ParsingPackage setVersionName(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setCompileSdkVersion(int p0);
    public android.content.pm.parsing.ParsingPackage setCompileSdkVersionCodename(java.lang.String p0);
    public android.content.pm.parsing.ParsingPackage setAttributionsAreUserVisible(boolean p0);
    public java.lang.Object hideAsParsed();
}
