package android.content.pm.parsing;

public class ParsingPackageUtils {
    public static final java.lang.String TAG = "PackageParsing";
    private boolean mOnlyCoreApps;
    private java.lang.String[] mSeparateProcesses;
    private android.util.DisplayMetrics mDisplayMetrics;
    private android.content.pm.parsing.ParsingPackageUtils.Callback mCallback;
    public static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseDefaultOneTime(java.io.File p0, int p1, boolean p2) { return null; }
    public static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseDefault(android.content.pm.parsing.result.ParseInput p0, java.io.File p1, int p2, boolean p3) { return null; }
    public ParsingPackageUtils(boolean p0, java.lang.String[] p1, android.util.DisplayMetrics p2, android.content.pm.parsing.ParsingPackageUtils.Callback p3) {}
    public android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parsePackage(android.content.pm.parsing.result.ParseInput p0, java.io.File p1, int p2) throws android.content.pm.PackageParser.PackageParserException { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseClusterPackage(android.content.pm.parsing.result.ParseInput p0, java.io.File p1, int p2) { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseMonolithicPackage(android.content.pm.parsing.result.ParseInput p0, java.io.File p1, int p2) throws android.content.pm.PackageParser.PackageParserException { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseBaseApk(android.content.pm.parsing.result.ParseInput p0, java.io.File p1, java.lang.String p2, android.content.res.AssetManager p3, int p4) { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseSplitApk(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, int p2, android.content.res.AssetManager p3, int p4) { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseBaseApk(android.content.pm.parsing.result.ParseInput p0, java.lang.String p1, java.lang.String p2, android.content.res.Resources p3, android.content.res.XmlResourceParser p4, int p5) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException, android.content.pm.PackageParser.PackageParserException { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseSplitApk(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3, int p4, int p5) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException, android.content.pm.PackageParser.PackageParserException { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseSplitApplication(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3, int p4, int p5) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private android.content.pm.parsing.result.ParseResult parseSplitBaseAppChildTags(android.content.pm.parsing.result.ParseInput p0, java.lang.String p1, android.content.pm.parsing.ParsingPackage p2, android.content.res.Resources p3, android.content.res.XmlResourceParser p4) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseBaseApkTags(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.TypedArray p2, android.content.res.Resources p3, android.content.res.XmlResourceParser p4, int p5) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private android.content.pm.parsing.result.ParseResult parseBaseApkTag(java.lang.String p0, android.content.pm.parsing.result.ParseInput p1, android.content.pm.parsing.ParsingPackage p2, android.content.res.Resources p3, android.content.res.XmlResourceParser p4, int p5) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseSharedUser(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.TypedArray p2) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseKeySets(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseAttribution(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parsePermissionGroup(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parsePermission(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parsePermissionTree(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseUsesPermission(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseUsesConfiguration(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseUsesFeature(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static android.content.pm.FeatureInfo parseFeatureInfo(android.content.res.Resources p0, android.util.AttributeSet p1) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseFeatureGroup(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseUsesSdk(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private static android.util.SparseIntArray exactSizedCopyOfSparseArray(android.util.SparseIntArray p0) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.util.SparseIntArray> parseExtensionSdk(android.content.pm.parsing.result.ParseInput p0, android.content.res.Resources p1, android.content.res.XmlResourceParser p2, android.util.SparseIntArray p3) { return null; }
    public static android.content.pm.parsing.result.ParseResult<java.lang.Integer> computeMinSdkVersion(int p0, java.lang.String p1, int p2, java.lang.String[] p3, android.content.pm.parsing.result.ParseInput p4) { return null; }
    public static android.content.pm.parsing.result.ParseResult<java.lang.Integer> computeTargetSdkVersion(int p0, java.lang.String p1, java.lang.String[] p2, android.content.pm.parsing.result.ParseInput p3) { return null; }
    private static boolean matchTargetCode(java.lang.String[] p0, java.lang.String p1) { return false; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseRestrictUpdateHash(int p0, android.content.pm.parsing.result.ParseInput p1, android.content.pm.parsing.ParsingPackage p2, android.content.res.Resources p3, android.content.res.XmlResourceParser p4) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseQueries(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseBaseApplication(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3, int p4) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private void parseBaseAppBasicFlags(android.content.pm.parsing.ParsingPackage p0, android.content.res.TypedArray p1) {}
    private android.content.pm.parsing.result.ParseResult parseBaseAppChildTag(android.content.pm.parsing.result.ParseInput p0, java.lang.String p1, android.content.pm.parsing.ParsingPackage p2, android.content.res.Resources p3, android.content.res.XmlResourceParser p4, int p5) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseStaticLibrary(android.content.pm.parsing.ParsingPackage p0, android.content.res.Resources p1, android.content.res.XmlResourceParser p2, android.content.pm.parsing.result.ParseInput p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseLibrary(android.content.pm.parsing.ParsingPackage p0, android.content.res.Resources p1, android.content.res.XmlResourceParser p2, android.content.pm.parsing.result.ParseInput p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseUsesStaticLibrary(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseUsesLibrary(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseProcesses(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3, java.lang.String[] p4, int p5) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseProfileable(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<java.lang.String[]> parseAdditionalCertificates(android.content.pm.parsing.result.ParseInput p0, android.content.res.Resources p1, android.content.res.XmlResourceParser p2) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.component.ParsedActivity> generateAppDetailsHiddenActivity(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1) { return null; }
    private static boolean hasDomainURLs(android.content.pm.parsing.ParsingPackage p0) { return false; }
    private static void setMaxAspectRatio(android.content.pm.parsing.ParsingPackage p0) {}
    private void setMinAspectRatio(android.content.pm.parsing.ParsingPackage p0) {}
    private void setSupportsSizeChanges(android.content.pm.parsing.ParsingPackage p0) {}
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseOverlay(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseProtectedBroadcast(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseSupportScreens(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseInstrumentation(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) throws org.xmlpull.v1.XmlPullParserException, java.io.IOException { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseOriginalPackage(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static android.content.pm.parsing.result.ParseResult<android.content.pm.parsing.ParsingPackage> parseAdoptPermissions(android.content.pm.parsing.result.ParseInput p0, android.content.pm.parsing.ParsingPackage p1, android.content.res.Resources p2, android.content.res.XmlResourceParser p3) { return null; }
    private static void convertNewPermissions(android.content.pm.parsing.ParsingPackage p0) {}
    private static void convertSplitPermissions(android.content.pm.parsing.ParsingPackage p0) {}
    private static void adjustPackageToBeUnresizeableAndUnpipable(android.content.pm.parsing.ParsingPackage p0) {}
    private static android.content.pm.parsing.result.ParseResult validateName(android.content.pm.parsing.result.ParseInput p0, java.lang.String p1, boolean p2, boolean p3) { return null; }
    public static android.content.pm.parsing.result.ParseResult<android.os.Bundle> parseMetaData(android.content.pm.parsing.ParsingPackage p0, android.content.res.Resources p1, android.content.res.XmlResourceParser p2, android.os.Bundle p3, android.content.pm.parsing.result.ParseInput p4) { return null; }
    public static android.content.pm.PackageParser.SigningDetails getSigningDetails(android.content.pm.parsing.ParsingPackageRead p0, boolean p1) throws android.content.pm.PackageParser.PackageParserException { return null; }
    public static android.content.pm.parsing.result.ParseResult<android.content.pm.PackageParser.SigningDetails> getSigningDetails(android.content.pm.parsing.result.ParseInput p0, java.lang.String p1, boolean p2, boolean p3, android.content.pm.PackageParser.SigningDetails p4, int p5) { return null; }
    private static boolean bool(boolean p0, int p1, android.content.res.TypedArray p2) { return false; }
    private static float aFloat(float p0, int p1, android.content.res.TypedArray p2) { return 0.0f; }
    private static float aFloat(int p0, android.content.res.TypedArray p1) { return 0.0f; }
    private static int anInt(int p0, int p1, android.content.res.TypedArray p2) { return 0; }
    private static int anInteger(int p0, int p1, android.content.res.TypedArray p2) { return 0; }
    private static int anInt(int p0, android.content.res.TypedArray p1) { return 0; }
    private static int resId(int p0, android.content.res.TypedArray p1) { return 0; }
    private static java.lang.String string(int p0, android.content.res.TypedArray p1) { return null; }
    private static java.lang.String nonConfigString(int p0, int p1, android.content.res.TypedArray p2) { return null; }
    private static java.lang.String nonResString(int p0, android.content.res.TypedArray p1) { return null; }

    public static interface Callback {
        public boolean hasFeature(java.lang.String p0);
        public android.content.pm.parsing.ParsingPackage startParsingPackage(java.lang.String p0, java.lang.String p1, java.lang.String p2, android.content.res.TypedArray p3, boolean p4);
    }
}
