package com.android.internal.org.bouncycastle.jcajce.provider.util;

public abstract class AsymmetricAlgorithmProvider extends com.android.internal.org.bouncycastle.jcajce.provider.util.AlgorithmProvider {
    public AsymmetricAlgorithmProvider() { super(); }
    protected void addSignatureAlgorithm(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, java.lang.String p2, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p3) {}
    protected void addSignatureAlias(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p2) {}
    protected void addSignatureAlgorithm(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, java.lang.String p2, java.lang.String p3) {}
    protected void addSignatureAlgorithm(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, java.lang.String p2, java.lang.String p3, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p4) {}
    protected void addSignatureAlgorithm(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, java.lang.String p2, java.lang.String p3, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p4, java.util.Map<java.lang.String, java.lang.String> p5) {}
    protected void addKeyPairGeneratorAlgorithm(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, java.lang.String p2, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p3) {}
    protected void addKeyFactoryAlgorithm(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, java.lang.String p2, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p3, com.android.internal.org.bouncycastle.jcajce.provider.util.AsymmetricKeyInfoConverter p4) {}
    protected void addKeyGeneratorAlgorithm(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, java.lang.String p2, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p3) {}
    protected void addCipherAlgorithm(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, java.lang.String p1, java.lang.String p2, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p3) {}
    protected void registerKeyFactoryOid(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p1, java.lang.String p2, com.android.internal.org.bouncycastle.jcajce.provider.util.AsymmetricKeyInfoConverter p3) {}
    protected void registerOid(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p1, java.lang.String p2, com.android.internal.org.bouncycastle.jcajce.provider.util.AsymmetricKeyInfoConverter p3) {}
    protected void registerOidAlgorithmParameters(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p1, java.lang.String p2) {}
    protected void registerOidAlgorithmParameterGenerator(com.android.internal.org.bouncycastle.jcajce.provider.config.ConfigurableProvider p0, com.android.internal.org.bouncycastle.asn1.ASN1ObjectIdentifier p1, java.lang.String p2) {}
}
