package com.android.ims;

public interface ImsUtInterface {
    public static final int ACTION_DEACTIVATION = 0;
    public static final int ACTION_ACTIVATION = 1;
    public static final int ACTION_REGISTRATION = 3;
    public static final int ACTION_ERASURE = 4;
    public static final int ACTION_INTERROGATION = 5;
    public static final int OIR_DEFAULT = 0;
    public static final int OIR_PRESENTATION_RESTRICTED = 1;
    public static final int OIR_PRESENTATION_NOT_RESTRICTED = 2;
    public static final int CDIV_CF_UNCONDITIONAL = 0;
    public static final int CDIV_CF_BUSY = 1;
    public static final int CDIV_CF_NO_REPLY = 2;
    public static final int CDIV_CF_NOT_REACHABLE = 3;
    public static final int CDIV_CF_ALL = 4;
    public static final int CDIV_CF_ALL_CONDITIONAL = 5;
    public static final int CDIV_CF_NOT_LOGGED_IN = 6;
    public static final int CB_BAIC = 1;
    public static final int CB_BAOC = 2;
    public static final int CB_BOIC = 3;
    public static final int CB_BOIC_EXHC = 4;
    public static final int CB_BIC_WR = 5;
    public static final int CB_BIC_ACR = 6;
    public static final int CB_BA_ALL = 7;
    public static final int CB_BA_MO = 8;
    public static final int CB_BA_MT = 9;
    public static final int CB_BS_MT = 10;
    public static final int INVALID = -1;
    public void queryCallBarring(int p0, android.os.Message p1);
    public void queryCallBarring(int p0, android.os.Message p1, int p2);
    public void queryCallForward(int p0, java.lang.String p1, android.os.Message p2);
    public void queryCallWaiting(android.os.Message p0);
    public void queryCLIR(android.os.Message p0);
    public void queryCLIP(android.os.Message p0);
    public void queryCOLR(android.os.Message p0);
    public void queryCOLP(android.os.Message p0);
    public void updateCallBarring(int p0, int p1, android.os.Message p2, java.lang.String[] p3);
    public void updateCallBarring(int p0, int p1, android.os.Message p2, java.lang.String[] p3, int p4);
    public void updateCallBarring(int p0, int p1, android.os.Message p2, java.lang.String[] p3, int p4, java.lang.String p5);
    public void updateCallForward(int p0, int p1, java.lang.String p2, int p3, int p4, android.os.Message p5);
    public void updateCallWaiting(boolean p0, int p1, android.os.Message p2);
    public void updateCLIR(int p0, android.os.Message p1);
    public void updateCLIP(boolean p0, android.os.Message p1);
    public void updateCOLR(int p0, android.os.Message p1);
    public void updateCOLP(boolean p0, android.os.Message p1);
    public void registerForSuppServiceIndication(android.os.Handler p0, int p1, java.lang.Object p2);
    public void unregisterForSuppServiceIndication(android.os.Handler p0);
}
