package com.android.internal.hidden_from_bootclasspath.com.android.window.flags;

public class CustomFeatureFlags implements com.android.internal.hidden_from_bootclasspath.com.android.window.flags.FeatureFlags {
    public CustomFeatureFlags(java.util.function.BiPredicate<java.lang.String, java.util.function.Predicate<com.android.internal.hidden_from_bootclasspath.com.android.window.flags.FeatureFlags>> p0) {}
    public boolean actionModeEdgeToEdge() { return false; }
    public boolean activityEmbeddingDelayTaskFragmentFinishForActivityLaunch() { return false; }
    public boolean activityEmbeddingInteractiveDividerFlag() { return false; }
    public boolean activityEmbeddingMetrics() { return false; }
    public boolean activityEmbeddingSupportForConnectedDisplays() { return false; }
    public boolean allowDisableActivityRecordInputSink() { return false; }
    public boolean allowsScreenSizeDecoupledFromStatusBarAndCutout() { return false; }
    public boolean alwaysDrawMagnificationFullscreenBorder() { return false; }
    public boolean alwaysSeqIdLayout() { return false; }
    public boolean alwaysUpdateWallpaperPermission() { return false; }
    public boolean aodTransition() { return false; }
    public boolean appCompatAsyncRelayout() { return false; }
    public boolean appCompatPropertiesApi() { return false; }
    public boolean appCompatRefactoring() { return false; }
    public boolean appCompatRefactoringRoundedCorners() { return false; }
    public boolean appCompatUiFramework() { return false; }
    public boolean appHandleNoRelayoutOnExclusionChange() { return false; }
    public boolean applyLifecycleOnPipChange() { return false; }
    public boolean avoidRebindingIntentionallyDisconnectedWallpaper() { return false; }
    public boolean backupAndRestoreForUserAspectRatioSettings() { return false; }
    public boolean balAdditionalLogging() { return false; }
    public boolean balAdditionalStartModes() { return false; }
    public boolean balClearAllowlistDuration() { return false; }
    public boolean balCoverIntentSender() { return false; }
    public boolean balDontBringExistingBackgroundTaskStackToFg() { return false; }
    public boolean balReduceGracePeriod() { return false; }
    public boolean balRespectAppSwitchStateWhenCheckBoundByForegroundUid() { return false; }
    public boolean balSendIntentWithOptions() { return false; }
    public boolean balShowToastsBlocked() { return false; }
    public boolean balStrictModeGracePeriod() { return false; }
    public boolean balStrictModeRo() { return false; }
    public boolean betterSupportNonMatchParentActivity() { return false; }
    public boolean cameraCompatForFreeform() { return false; }
    public boolean cameraCompatFullscreenPickSameTaskActivity() { return false; }
    public boolean closeToSquareConfigIncludesStatusBar() { return false; }
    public boolean coverDisplayOptIn() { return false; }
    public boolean currentAnimatorScaleUsesSharedMemory() { return false; }
    public boolean defaultDeskWithoutWarmupMigration() { return false; }
    public boolean delegateUnhandledDrags() { return false; }
    public boolean density390Api() { return false; }
    public boolean disableDesktopLaunchParamsOutsideDesktopBugFix() { return false; }
    public boolean disableNonResizableAppSnapResizing() { return false; }
    public boolean disableOptOutEdgeToEdge() { return false; }
    public boolean dispatchFirstKeyguardLockedState() { return false; }
    public boolean enableAccessibleCustomHeaders() { return false; }
    public boolean enableActivityEmbeddingSupportForConnectedDisplays() { return false; }
    public boolean enableAppHandlePositionReporting() { return false; }
    public boolean enableAppHeaderWithTaskDensity() { return false; }
    public boolean enableBlockNonDesktopDisplayWindowDragBugfix() { return false; }
    public boolean enableBorderSettings() { return false; }
    public boolean enableBoxShadowSettings() { return false; }
    public boolean enableBugFixesForSecondaryDisplay() { return false; }
    public boolean enableCameraCompatCheckDeviceRotationBugfix() { return false; }
    public boolean enableCameraCompatForDesktopWindowing() { return false; }
    public boolean enableCameraCompatForDesktopWindowingOptOut() { return false; }
    public boolean enableCameraCompatForDesktopWindowingOptOutApi() { return false; }
    public boolean enableCameraCompatTrackTaskAndAppBugfix() { return false; }
    public boolean enableCaptionCompatInsetConversion() { return false; }
    public boolean enableCaptionCompatInsetForceConsumption() { return false; }
    public boolean enableCaptionCompatInsetForceConsumptionAlways() { return false; }
    public boolean enableCascadingWindows() { return false; }
    public boolean enableCloseLidInteraction() { return false; }
    public boolean enableCompatUiVisibilityStatus() { return false; }
    public boolean enableCompatuiSysuiLauncher() { return false; }
    public boolean enableConnectedDisplaysDnd() { return false; }
    public boolean enableConnectedDisplaysPip() { return false; }
    public boolean enableConnectedDisplaysWindowDrag() { return false; }
    public boolean enableDesktopAppHandleAnimation() { return false; }
    public boolean enableDesktopAppHeaderStateChangeAnnouncements() { return false; }
    public boolean enableDesktopAppLaunchAlttabTransitions() { return false; }
    public boolean enableDesktopAppLaunchAlttabTransitionsBugfix() { return false; }
    public boolean enableDesktopAppLaunchBugfix() { return false; }
    public boolean enableDesktopAppLaunchTransitions() { return false; }
    public boolean enableDesktopAppLaunchTransitionsBugfix() { return false; }
    public boolean enableDesktopCloseShortcutBugfix() { return false; }
    public boolean enableDesktopCloseTaskAnimationInDtcBugfix() { return false; }
    public boolean enableDesktopFirstBasedDefaultToDesktopBugfix() { return false; }
    public boolean enableDesktopFirstBasedDragToMaximize() { return false; }
    public boolean enableDesktopFirstFullscreenRefocusBugfix() { return false; }
    public boolean enableDesktopFirstListener() { return false; }
    public boolean enableDesktopImeBugfix() { return false; }
    public boolean enableDesktopImmersiveDragBugfix() { return false; }
    public boolean enableDesktopIndicatorInSeparateThreadBugfix() { return false; }
    public boolean enableDesktopModeThroughDevOption() { return false; }
    public boolean enableDesktopOpeningDeeplinkMinimizeAnimationBugfix() { return false; }
    public boolean enableDesktopRecentsTransitionsCornersBugfix() { return false; }
    public boolean enableDesktopSplitscreenTransitionBugfix() { return false; }
    public boolean enableDesktopSystemDialogsTransitions() { return false; }
    public boolean enableDesktopTabTearingLaunchAnimation() { return false; }
    public boolean enableDesktopTabTearingMinimizeAnimationBugfix() { return false; }
    public boolean enableDesktopTaskLimitSeparateTransition() { return false; }
    public boolean enableDesktopTaskbarOnFreeformDisplays() { return false; }
    public boolean enableDesktopTrampolineCloseAnimationBugfix() { return false; }
    public boolean enableDesktopWallpaperActivityForSystemUser() { return false; }
    public boolean enableDesktopWindowingAppHandleEducation() { return false; }
    public boolean enableDesktopWindowingAppToWeb() { return false; }
    public boolean enableDesktopWindowingAppToWebEducation() { return false; }
    public boolean enableDesktopWindowingAppToWebEducationIntegration() { return false; }
    public boolean enableDesktopWindowingBackNavigation() { return false; }
    public boolean enableDesktopWindowingEnterTransitionBugfix() { return false; }
    public boolean enableDesktopWindowingEnterTransitions() { return false; }
    public boolean enableDesktopWindowingExitByMinimizeTransitionBugfix() { return false; }
    public boolean enableDesktopWindowingExitTransitions() { return false; }
    public boolean enableDesktopWindowingExitTransitionsBugfix() { return false; }
    public boolean enableDesktopWindowingHsum() { return false; }
    public boolean enableDesktopWindowingImmersiveHandleHiding() { return false; }
    public boolean enableDesktopWindowingModalsPolicy() { return false; }
    public boolean enableDesktopWindowingMode() { return false; }
    public boolean enableDesktopWindowingMultiInstanceFeatures() { return false; }
    public boolean enableDesktopWindowingPersistence() { return false; }
    public boolean enableDesktopWindowingPip() { return false; }
    public boolean enableDesktopWindowingPipInOverviewBugfix() { return false; }
    public boolean enableDesktopWindowingQuickSwitch() { return false; }
    public boolean enableDesktopWindowingScvhCacheBugFix() { return false; }
    public boolean enableDesktopWindowingSizeConstraints() { return false; }
    public boolean enableDesktopWindowingTaskLimit() { return false; }
    public boolean enableDesktopWindowingTaskbarRunningApps() { return false; }
    public boolean enableDesktopWindowingTransitions() { return false; }
    public boolean enableDesktopWindowingWallpaperActivity() { return false; }
    public boolean enableDeviceStateAutoRotateSettingLogging() { return false; }
    public boolean enableDeviceStateAutoRotateSettingRefactor() { return false; }
    public boolean enableDisplayCompatMode() { return false; }
    public boolean enableDisplayDisconnectInteraction() { return false; }
    public boolean enableDisplayFocusInShellTransitions() { return false; }
    public boolean enableDisplayReconnectInteraction() { return false; }
    public boolean enableDisplayWindowingModeSwitching() { return false; }
    public boolean enableDragResizeSetUpInBgThread() { return false; }
    public boolean enableDragToDesktopIncomingTransitionsBugfix() { return false; }
    public boolean enableDragToMaximize() { return false; }
    public boolean enableDraggingPipAcrossDisplays() { return false; }
    public boolean enableDynamicRadiusComputationBugfix() { return false; }
    public boolean enableEmptyDeskOnMinimize() { return false; }
    public boolean enableExperimentalBubblesController() { return false; }
    public boolean enableFreeformBoxShadows() { return false; }
    public boolean enableFreeformDisplayLaunchParams() { return false; }
    public boolean enableFullScreenWindowOnRemovingSplitScreenStageBugfix() { return false; }
    public boolean enableFullscreenWindowControls() { return false; }
    public boolean enableFullyImmersiveInDesktop() { return false; }
    public boolean enableHandleInputFix() { return false; }
    public boolean enableHandlersDebuggingMode() { return false; }
    public boolean enableHoldToDragAppHandle() { return false; }
    public boolean enableIndependentBackInProjected() { return false; }
    public boolean enableInorderTransitionCallbacksForDesktop() { return false; }
    public boolean enableInputLayerTransitionFix() { return false; }
    public boolean enableKeyGestureHandlerForSysui() { return false; }
    public boolean enableMinimizeButton() { return false; }
    public boolean enableModalsFullscreenWithPermission() { return false; }
    public boolean enableModalsFullscreenWithPlatformSignature() { return false; }
    public boolean enableMoveToNextDisplayShortcut() { return false; }
    public boolean enableMultiDisplaySplit() { return false; }
    public boolean enableMultidisplayTrackpadBackGesture() { return false; }
    public boolean enableMultipleDesktopsBackend() { return false; }
    public boolean enableMultipleDesktopsDefaultActivationInDesktopFirstDisplays() { return false; }
    public boolean enableMultipleDesktopsFrontend() { return false; }
    public boolean enableNoWindowDecorationForDesks() { return false; }
    public boolean enableNonDefaultDisplaySplit() { return false; }
    public boolean enableOmitAccelerometerRotationRestore() { return false; }
    public boolean enableOpaqueBackgroundForTransparentWindows() { return false; }
    public boolean enableOverflowButtonForTaskbarPinnedItems() { return false; }
    public boolean enablePerDisplayDesktopWallpaperActivity() { return false; }
    public boolean enablePerDisplayPackageContextCacheInStatusbarNotif() { return false; }
    public boolean enablePersistingDisplaySizeForConnectedDisplays() { return false; }
    public boolean enablePinningAppWithContextMenu() { return false; }
    public boolean enablePresentationForConnectedDisplays() { return false; }
    public boolean enableProjectedDisplayDesktopMode() { return false; }
    public boolean enableQuickswitchDesktopSplitBugfix() { return false; }
    public boolean enableRejectHomeTransition() { return false; }
    public boolean enableRequestFullscreenBugfix() { return false; }
    public boolean enableRequestFullscreenRefactor() { return false; }
    public boolean enableResizingMetrics() { return false; }
    public boolean enableRestartMenuForConnectedDisplays() { return false; }
    public boolean enableRestoreToPreviousSizeFromDesktopImmersive() { return false; }
    public boolean enableSeeThroughTaskFragments() { return false; }
    public boolean enableShellInitialBoundsRegressionBugFix() { return false; }
    public boolean enableSizeCompatModeImprovementsForConnectedDisplays() { return false; }
    public boolean enableStartLaunchTransitionFromTaskbarBugfix() { return false; }
    public boolean enableSysDecorsCallbacksViaWm() { return false; }
    public boolean enableTallAppHeaders() { return false; }
    public boolean enableTaskResizingKeyboardShortcuts() { return false; }
    public boolean enableTaskStackObserverInShell() { return false; }
    public boolean enableTaskbarConnectedDisplays() { return false; }
    public boolean enableTaskbarOverflow() { return false; }
    public boolean enableTaskbarRecentTasksThrottleBugfix() { return false; }
    public boolean enableTaskbarRecentsLayoutTransition() { return false; }
    public boolean enableThemedAppHeaders() { return false; }
    public boolean enableTileResizing() { return false; }
    public boolean enableTopVisibleRootTaskPerUserTracking() { return false; }
    public boolean enableTransitionOnActivitySetRequestedOrientation() { return false; }
    public boolean enableVisualIndicatorInTransitionBugfix() { return false; }
    public boolean enableWindowContextOverrideType() { return false; }
    public boolean enableWindowContextResourcesUpdateOnConfigChange() { return false; }
    public boolean enableWindowDecorationRefactor() { return false; }
    public boolean enableWindowRepositioningApi() { return false; }
    public boolean enableWindowingDynamicInitialBounds() { return false; }
    public boolean enableWindowingEdgeDragResize() { return false; }
    public boolean enableWindowingScaledResizing() { return false; }
    public boolean enableWindowingTaskStackOrderBugfix() { return false; }
    public boolean enableWindowingTransitionHandlersObservers() { return false; }
    public boolean enforceEdgeToEdge() { return false; }
    public boolean ensureKeyguardDoesTransitionStarting() { return false; }
    public boolean enterDesktopByDefaultOnFreeformDisplays() { return false; }
    public boolean excludeCaptionFromAppBounds() { return false; }
    public boolean excludeDeskRootsFromDesktopTasks() { return false; }
    public boolean excludeNonMainWindowFromSnapshot() { return false; }
    public boolean excludeTaskFromRecents() { return false; }
    public boolean extendingPersistenceSnapshotQueueDepth() { return false; }
    public boolean fallbackToFocusedDisplay() { return false; }
    public boolean fifoPriorityForMajorUiProcesses() { return false; }
    public boolean fixFullscreenInMultiWindow() { return false; }
    public boolean fixHideOverlayApi() { return false; }
    public boolean fixLayoutRestoredTask() { return false; }
    public boolean fixMovingUnfocusedTask() { return false; }
    public boolean fixSetAdjacentTaskFragmentsWithParams() { return false; }
    public boolean fixShowWhenLockedSyncTimeout() { return false; }
    public boolean forceCloseTopTransparentFullscreenTask() { return false; }
    public boolean forceShowSystemBarForBubble() { return false; }
    public boolean formFactorBasedDesktopFirstSwitch() { return false; }
    public boolean getDimmerOnClosing() { return false; }
    public boolean grantManageKeyGesturesToRecents() { return false; }
    public boolean ignoreAspectRatioRestrictionsForResizeableFreeformActivities() { return false; }
    public boolean ignoreCornerRadiusAndShadows() { return false; }
    public boolean includeTopTransparentFullscreenTaskInDesktopHeuristic() { return false; }
    public boolean inheritTaskBoundsForTrampolineTaskLaunches() { return false; }
    public boolean insetsDecoupledConfiguration() { return false; }
    public boolean interceptMotionFromMoveToCancel() { return false; }
    public boolean jankApi() { return false; }
    public boolean keyboardShortcutsToSwitchDesks() { return false; }
    public boolean letterboxBackgroundWallpaper() { return false; }
    public boolean movableCutoutConfiguration() { return false; }
    public boolean moveToExternalDisplayShortcut() { return false; }
    public boolean multiCrop() { return false; }
    public boolean navBarTransparentByDefault() { return false; }
    public boolean nestedTasksWithIndependentBoundsBugfix() { return false; }
    public boolean offloadColorExtraction() { return false; }
    public boolean parallelCdTransitionsDuringRecents() { return false; }
    public boolean portWindowSizeAnimation() { return false; }
    public boolean predictiveBackDefaultEnableSdk36() { return false; }
    public boolean predictiveBackPrioritySystemNavigationObserver() { return false; }
    public boolean predictiveBackSwipeEdgeNoneApi() { return false; }
    public boolean predictiveBackSystemOverrideCallback() { return false; }
    public boolean predictiveBackThreeButtonNav() { return false; }
    public boolean predictiveBackTimestampApi() { return false; }
    public boolean preserveRecentsTaskConfigurationOnRelaunch() { return false; }
    public boolean rearDisplayDisableForceDesktopSystemDecorations() { return false; }
    public boolean reduceChangedExclusionRectsMsgs() { return false; }
    public boolean reduceTaskSnapshotMemoryUsage() { return false; }
    public boolean relativeInsets() { return false; }
    public boolean releaseSnapshotAggressively() { return false; }
    public boolean releaseSurfaceOnTransitionFinish() { return false; }
    public boolean removeActivityStarterDreamCallback() { return false; }
    public boolean removeDepartTargetFromMotion() { return false; }
    public boolean removeStartingInTransition() { return false; }
    public boolean reparentToDefaultWithDisplayRemoval() { return false; }
    public boolean reparentWindowTokenApi() { return false; }
    public boolean respectFullscreenActivityOptionInDesktopLaunchParams() { return false; }
    public boolean respectHierarchySurfaceVisibility() { return false; }
    public boolean respectLeafTaskBounds() { return false; }
    public boolean respectOrientationChangeForUnresizeable() { return false; }
    public boolean restoreUserAspectRatioSettingsUsingService() { return false; }
    public boolean restrictFreeformHiddenSystemBarsToFillingTasks() { return false; }
    public boolean rootTaskForBubble() { return false; }
    public boolean safeRegionLetterboxing() { return false; }
    public boolean safeReleaseSnapshotAggressively() { return false; }
    public boolean schedulingForNotificationShade() { return false; }
    public boolean scrambleSnapshotFileName() { return false; }
    public boolean screenBrightnessDimOnEmulator() { return false; }
    public boolean screenRecordingCallbacks() { return false; }
    public boolean scrollingFromLetterbox() { return false; }
    public boolean scvhSurfaceControlLifetimeFix() { return false; }
    public boolean sdkDesiredPresentTime() { return false; }
    public boolean setScPropertiesInClient() { return false; }
    public boolean showAppHandleLargeScreens() { return false; }
    public boolean showDesktopExperienceDevOption() { return false; }
    public boolean showDesktopWindowingDevOption() { return false; }
    public boolean showHomeBehindDesktop() { return false; }
    public boolean skipCompatUiEducationInDesktopMode() { return false; }
    public boolean skipDeactivationOfDeskWithNothingInFront() { return false; }
    public boolean skipDecorViewRelayoutWhenClosingBugfix() { return false; }
    public boolean splashScreenViewSyncTransaction() { return false; }
    public boolean supportsDragAssistantToMultiwindow() { return false; }
    public boolean supportsMultiInstanceSystemUi() { return false; }
    public boolean surfaceControlInputReceiver() { return false; }
    public boolean surfaceTrustedOverlay() { return false; }
    public boolean syncScreenCapture() { return false; }
    public boolean systemUiPostAnimationEnd() { return false; }
    public boolean touchPassThroughOptIn() { return false; }
    public boolean transitReadyTracking() { return false; }
    public boolean transitTrackerPlumbing() { return false; }
    public boolean transitionHandlerCujTags() { return false; }
    public boolean trustedPresentationListenerForWindow() { return false; }
    public boolean unifyBackNavigationTransition() { return false; }
    public boolean unifyShellBinders() { return false; }
    public boolean universalResizableByDefault() { return false; }
    public boolean untrustedEmbeddingAnyAppPermission() { return false; }
    public boolean untrustedEmbeddingStateSharing() { return false; }
    public boolean updateDimsWhenWindowShown() { return false; }
    public boolean updateHostInputTransferToken() { return false; }
    public boolean updateTaskMinDimensionsWithRootActivity() { return false; }
    public boolean useCachedInsetsForDisplaySwitch() { return false; }
    public boolean useTasksDimOnly() { return false; }
    public boolean vdmForceAppUniversalResizableApi() { return false; }
    public boolean wallpaperOffsetAsync() { return false; }
    public boolean wlinfoOncreate() { return false; }
    public boolean isFlagReadOnlyOptimized(java.lang.String p0) { return false; }
    protected boolean getValue(java.lang.String p0, java.util.function.Predicate<com.android.internal.hidden_from_bootclasspath.com.android.window.flags.FeatureFlags> p1) { return false; }
    public java.util.List<java.lang.String> getFlagNames() { return null; }
}
