package com.android.internal.telephony.flags;

public class CustomFeatureFlags implements com.android.internal.telephony.flags.FeatureFlags {
    public CustomFeatureFlags(java.util.function.BiPredicate<java.lang.String, java.util.function.Predicate<com.android.internal.telephony.flags.FeatureFlags>> p0) {}
    public boolean addAnomalyWhenNotifyConfigChangedWithInvalidPhone() { return false; }
    public boolean addRatRelatedSuggestedActionToImsRegistration() { return false; }
    public boolean allowMmtelInNonVops() { return false; }
    public boolean answerAudioOnlyWhenAnsweringViaMmiCode() { return false; }
    public boolean apDomainSelectionEnabled() { return false; }
    public boolean apnSettingFieldSupportFlag() { return false; }
    public boolean autoDataSwitchAllowRoaming() { return false; }
    public boolean autoDataSwitchUsesDataEnabled() { return false; }
    public boolean backupAndRestoreForEnable2g() { return false; }
    public boolean callExtraForNonHoldSupportedCarriers() { return false; }
    public boolean carrierEnabledSatelliteFlag() { return false; }
    public boolean carrierRestrictionRulesEnhancement() { return false; }
    public boolean carrierRestrictionStatus() { return false; }
    public boolean changeMethodOfObtainingImsRegistrationRadioTech() { return false; }
    public boolean cleanupOpenLogicalChannelRecordOnDispose() { return false; }
    public boolean clearCachedImsPhoneNumberWhenDeviceLostImsRegistration() { return false; }
    public boolean combineRilDeathHandle() { return false; }
    public boolean conferenceHoldUnholdChangedToSendMessage() { return false; }
    public boolean dataCallSessionStatsCapturesCrossSimCalling() { return false; }
    public boolean dataOnlyCellularService() { return false; }
    public boolean dataOnlyServiceAllowEmergencyCallOnly() { return false; }
    public boolean dataRatMetricEnabled() { return false; }
    public boolean dismissNetworkSelectionNotificationOnSimDisable() { return false; }
    public boolean doNotOverridePreciseLabel() { return false; }
    public boolean domainSelectionMetricsEnabled() { return false; }
    public boolean dsrsDiagnosticsEnabled() { return false; }
    public boolean emergencyRegistrationState() { return false; }
    public boolean enableAeadAlgorithms() { return false; }
    public boolean enableCarrierConfigN1ControlAttempt2() { return false; }
    public boolean enableIdentifierDisclosureTransparency() { return false; }
    public boolean enableIdentifierDisclosureTransparencyUnsolEvents() { return false; }
    public boolean enableModemCipherTransparency() { return false; }
    public boolean enableModemCipherTransparencyUnsolEvents() { return false; }
    public boolean enableMultipleSaProposals() { return false; }
    public boolean enableSipSubscribeRetry() { return false; }
    public boolean enableTelephonyAnalytics() { return false; }
    public boolean enableWpsCheckApiFlag() { return false; }
    public boolean enforceSubscriptionUserFilter() { return false; }
    public boolean enforceTelephonyFeatureMapping() { return false; }
    public boolean enforceTelephonyFeatureMappingForPublicApis() { return false; }
    public boolean ensureAccessToCallSettingsIsRestricted() { return false; }
    public boolean esimAvailableMemory() { return false; }
    public boolean esimBootstrapProvisioningFlag() { return false; }
    public boolean fixCrashOnGettingConfigWhenPhoneIsGone() { return false; }
    public boolean forceIwlanMms() { return false; }
    public boolean hidePrefer3gItem() { return false; }
    public boolean hidePreinstalledCarrierAppAtMostOnce() { return false; }
    public boolean hideRoamingIcon() { return false; }
    public boolean ignoreAlreadyTerminatedIncomingCallBeforeRegisteringListener() { return false; }
    public boolean ignoreExistingNetworksForInternetAllowedChecking() { return false; }
    public boolean imsiKeyRetryDownloadOnPhoneUnlock() { return false; }
    public boolean keepEmptyRequestsNetwork() { return false; }
    public boolean logMmsSmsDatabaseAccessInfo() { return false; }
    public boolean meteredEmbbUrlcc() { return false; }
    public boolean minimalTelephonyCdmCheck() { return false; }
    public boolean minimalTelephonyManagersConditionalOnFeatures() { return false; }
    public boolean mmsDisabledError() { return false; }
    public boolean mmsGetApnFromPdsc() { return false; }
    public boolean networkRegistrationInfoRejectCause() { return false; }
    public boolean networkValidation() { return false; }
    public boolean notifyDataActivityChangedWithSlot() { return false; }
    public boolean notifyInitialImsProvisioningStatus() { return false; }
    public boolean oemEnabledSatelliteFlag() { return false; }
    public boolean preventInvocationRepeatOfRilCallWhenDeviceDoesNotSupportVoice() { return false; }
    public boolean preventSystemServerAndPhoneDeadlock() { return false; }
    public boolean reconnectQualifiedNetwork() { return false; }
    public boolean refinePreferredDataProfileSelection() { return false; }
    public boolean relaxHoTeardown() { return false; }
    public boolean removeCountryCodeFromLocalSingaporeCalls() { return false; }
    public boolean reorganizeRoamingNotification() { return false; }
    public boolean resetMobileNetworkSettings() { return false; }
    public boolean resetPrimarySimDefaultValues() { return false; }
    public boolean roamingNotificationForSingleDataNetwork() { return false; }
    public boolean saferGetPhoneNumber() { return false; }
    public boolean satelliteInternet() { return false; }
    public boolean satellitePersistentLogging() { return false; }
    public boolean setCarrierRestrictionStatus() { return false; }
    public boolean setNoReplyTimerForCfnry() { return false; }
    public boolean setNumberOfSimForImsEnable() { return false; }
    public boolean showCallFailNotificationFor2gToggle() { return false; }
    public boolean showCallIdAndCallWaitingInAdditionalSettingsMenu() { return false; }
    public boolean simultaneousCallingIndications() { return false; }
    public boolean slicingAdditionalErrorCodes() { return false; }
    public boolean smsDomainSelectionEnabled() { return false; }
    public boolean stopSpammingEmergencyNotification() { return false; }
    public boolean subscriptionUserAssociationQuery() { return false; }
    public boolean supportNrSaRrcIdle() { return false; }
    public boolean supportPsimToEsimConversion() { return false; }
    public boolean terminateActiveVideoCallWhenAcceptingSecondVideoCallAsAudioOnly() { return false; }
    public boolean unregisterSmsBroadcastReceiverFromCatService() { return false; }
    public boolean unthrottleCheckTransport() { return false; }
    public boolean updateImsServiceByGatheringProvisioningChanges() { return false; }
    public boolean updateRoamingStateToSetWfcMode() { return false; }
    public boolean useAlarmCallback() { return false; }
    public boolean useAospDomainSelectionService() { return false; }
    public boolean useOemDomainSelectionService() { return false; }
    public boolean useRelaxedIdMatch() { return false; }
    public boolean vonrEnabledMetric() { return false; }
    public boolean workProfileApiSplit() { return false; }
    public boolean isFlagReadOnlyOptimized(java.lang.String p0) { return false; }
    protected boolean getValue(java.lang.String p0, java.util.function.Predicate<com.android.internal.telephony.flags.FeatureFlags> p1) { return false; }
    public java.util.List<java.lang.String> getFlagNames() { return null; }
}
