package com.android.internal.widget;

public interface DecorToolbar {
    public android.view.ViewGroup getViewGroup();
    public android.content.Context getContext();
    public boolean isSplit();
    public boolean hasExpandedActionView();
    public void collapseActionView();
    public void setWindowCallback(android.view.Window.Callback p0);
    public void setWindowTitle(java.lang.CharSequence p0);
    public java.lang.CharSequence getTitle();
    public void setTitle(java.lang.CharSequence p0);
    public java.lang.CharSequence getSubtitle();
    public void setSubtitle(java.lang.CharSequence p0);
    public void initProgress();
    public void initIndeterminateProgress();
    public boolean canSplit();
    public void setSplitView(android.view.ViewGroup p0);
    public void setSplitToolbar(boolean p0);
    public void setSplitWhenNarrow(boolean p0);
    public boolean hasIcon();
    public boolean hasLogo();
    public void setIcon(int p0);
    public void setIcon(android.graphics.drawable.Drawable p0);
    public void setLogo(int p0);
    public void setLogo(android.graphics.drawable.Drawable p0);
    public boolean canShowOverflowMenu();
    public boolean isOverflowMenuShowing();
    public boolean isOverflowMenuShowPending();
    public boolean showOverflowMenu();
    public boolean hideOverflowMenu();
    public void setMenuPrepared();
    public void setMenu(android.view.Menu p0, com.android.internal.view.menu.MenuPresenter.Callback p1);
    public void dismissPopupMenus();
    public int getDisplayOptions();
    public void setDisplayOptions(int p0);
    public void setEmbeddedTabView(com.android.internal.widget.ScrollingTabContainerView p0);
    public boolean hasEmbeddedTabs();
    public boolean isTitleTruncated();
    public void setCollapsible(boolean p0);
    public void setHomeButtonEnabled(boolean p0);
    public int getNavigationMode();
    public void setNavigationMode(int p0);
    public void setDropdownParams(android.widget.SpinnerAdapter p0, android.widget.AdapterView.OnItemSelectedListener p1);
    public void setDropdownSelectedPosition(int p0);
    public int getDropdownSelectedPosition();
    public int getDropdownItemCount();
    public void setCustomView(android.view.View p0);
    public android.view.View getCustomView();
    public void animateToVisibility(int p0);
    public android.animation.Animator setupAnimatorToVisibility(int p0, long p1);
    public void setNavigationIcon(android.graphics.drawable.Drawable p0);
    public void setNavigationIcon(int p0);
    public void setNavigationContentDescription(java.lang.CharSequence p0);
    public void setNavigationContentDescription(int p0);
    public void setDefaultNavigationContentDescription(int p0);
    public void setDefaultNavigationIcon(android.graphics.drawable.Drawable p0);
    public void saveHierarchyState(android.util.SparseArray<android.os.Parcelable> p0);
    public void restoreHierarchyState(android.util.SparseArray<android.os.Parcelable> p0);
    public void setBackgroundDrawable(android.graphics.drawable.Drawable p0);
    public int getHeight();
    public void setVisibility(int p0);
    public int getVisibility();
    public void setMenuCallbacks(com.android.internal.view.menu.MenuPresenter.Callback p0, com.android.internal.view.menu.MenuBuilder.Callback p1);
    public android.view.Menu getMenu();
}
