package com.android.graphics.surfaceflinger.flags;

public interface FeatureFlags {
    public boolean addSfSkippedFramesToTrace();
    public boolean adpfGpuSf();
    public boolean allowNVsyncsInTargeter();
    public boolean cacheWhenSourceCropLayerOnlyMoved();
    public boolean ceFencePromise();
    public boolean commitNotComposited();
    public boolean connectedDisplay();
    public boolean deprecateVsyncSf();
    public boolean detachedMirror();
    public boolean displayProtected();
    public boolean dontSkipOnEarlyRo();
    public boolean enableFroDependentFeatures();
    public boolean enableLayerCommandBatching();
    public boolean enableSmallAreaDetection();
    public boolean flushBufferSlotsToUncache();
    public boolean forceCompileGraphiteRenderengine();
    public boolean fp16ClientTarget();
    public boolean frameRateCategoryMrr();
    public boolean gameDefaultFrameRate();
    public boolean graphiteRenderengine();
    public boolean hdcpLevelHal();
    public boolean hotplug2();
    public boolean latchUnsignaledWithAutoRefreshChanged();
    public boolean localTonemapScreenshots();
    public boolean misc1();
    public boolean multithreadedPresent();
    public boolean overrideTrustedOverlay();
    public boolean protectedIfClient();
    public boolean refreshRateOverlayOnExternalDisplay();
    public boolean renderableBufferUsage();
    public boolean restoreBlurStep();
    public boolean screenshotFencePreservation();
    public boolean singleHopScreenshot();
    public boolean useKnownRefreshRateForFpsConsistency();
    public boolean vrrBugfix24q4();
    public boolean vrrConfig();
    public boolean vulkanRenderengine();
}
