package org.xmlpull.v1;

public interface XmlPullParser {
    public static final int CDSECT = 5;
    public static final int COMMENT = 9;
    public static final int DOCDECL = 10;
    public static final int END_DOCUMENT = 1;
    public static final int END_TAG = 3;
    public static final int ENTITY_REF = 6;
    public static final java.lang.String FEATURE_PROCESS_DOCDECL = "http://xmlpull.org/v1/doc/features.html#process-docdecl";
    public static final java.lang.String FEATURE_PROCESS_NAMESPACES = "http://xmlpull.org/v1/doc/features.html#process-namespaces";
    public static final java.lang.String FEATURE_REPORT_NAMESPACE_ATTRIBUTES = "http://xmlpull.org/v1/doc/features.html#report-namespace-prefixes";
    public static final java.lang.String FEATURE_VALIDATION = "http://xmlpull.org/v1/doc/features.html#validation";
    public static final int IGNORABLE_WHITESPACE = 7;
    public static final java.lang.String NO_NAMESPACE = "";
    public static final int PROCESSING_INSTRUCTION = 8;
    public static final int START_DOCUMENT = 0;
    public static final int START_TAG = 2;
    public static final int TEXT = 4;
    public static final java.lang.String[] TYPES = null;
    public void setFeature(java.lang.String p0, boolean p1) throws org.xmlpull.v1.XmlPullParserException;
    public boolean getFeature(java.lang.String p0);
    public void setProperty(java.lang.String p0, java.lang.Object p1) throws org.xmlpull.v1.XmlPullParserException;
    public java.lang.Object getProperty(java.lang.String p0);
    public void setInput(java.io.Reader p0) throws org.xmlpull.v1.XmlPullParserException;
    public void setInput(java.io.InputStream p0, java.lang.String p1) throws org.xmlpull.v1.XmlPullParserException;
    public java.lang.String getInputEncoding();
    public void defineEntityReplacementText(java.lang.String p0, java.lang.String p1) throws org.xmlpull.v1.XmlPullParserException;
    public int getNamespaceCount(int p0) throws org.xmlpull.v1.XmlPullParserException;
    public java.lang.String getNamespacePrefix(int p0) throws org.xmlpull.v1.XmlPullParserException;
    public java.lang.String getNamespaceUri(int p0) throws org.xmlpull.v1.XmlPullParserException;
    public java.lang.String getNamespace(java.lang.String p0);
    public int getDepth();
    public java.lang.String getPositionDescription();
    public int getLineNumber();
    public int getColumnNumber();
    public boolean isWhitespace() throws org.xmlpull.v1.XmlPullParserException;
    public java.lang.String getText();
    public char[] getTextCharacters(int[] p0);
    public java.lang.String getNamespace();
    public java.lang.String getName();
    public java.lang.String getPrefix();
    public boolean isEmptyElementTag() throws org.xmlpull.v1.XmlPullParserException;
    public int getAttributeCount();
    public java.lang.String getAttributeNamespace(int p0);
    public java.lang.String getAttributeName(int p0);
    public java.lang.String getAttributePrefix(int p0);
    public java.lang.String getAttributeType(int p0);
    public boolean isAttributeDefault(int p0);
    public java.lang.String getAttributeValue(int p0);
    public java.lang.String getAttributeValue(java.lang.String p0, java.lang.String p1);
    public int getEventType() throws org.xmlpull.v1.XmlPullParserException;
    public int next() throws java.io.IOException, org.xmlpull.v1.XmlPullParserException;
    public int nextToken() throws java.io.IOException, org.xmlpull.v1.XmlPullParserException;
    public void require(int p0, java.lang.String p1, java.lang.String p2) throws java.io.IOException, org.xmlpull.v1.XmlPullParserException;
    public java.lang.String nextText() throws java.io.IOException, org.xmlpull.v1.XmlPullParserException;
    public int nextTag() throws java.io.IOException, org.xmlpull.v1.XmlPullParserException;
}
