package com.android.internal.hidden_from_bootclasspath.android.media.audio;

public interface FeatureFlags {
    public boolean assistantVolumeControl();
    public boolean audioFocusDesktop();
    public boolean autoPublicVolumeApiHardening();
    public boolean cacheGetStreamMinMaxVolume();
    public boolean cacheGetStreamVolume();
    public boolean concurrentAudioRecordBypassPermission();
    public boolean dapInjectionStarveManagement();
    public boolean deprecateStreamBtSco();
    public boolean deviceVolumeApis();
    public boolean dolbyAc4Level4EncodingApi();
    public boolean enableMultichannelGroupDevice();
    public boolean enablePlatformPcType();
    public boolean enableRingtoneHapticsCustomization();
    public boolean featureSpatialAudioHeadtrackingLowLatency();
    public boolean focusExclusiveWithRecording();
    public boolean focusFreezeTestApi();
    public boolean foregroundAudioControl();
    public boolean hardeningPermissionApi();
    public boolean hardeningPermissionSpa();
    public boolean iamfDefinitionsApi();
    public boolean leaudioSwOffload();
    public boolean loudnessConfiguratorApi();
    public boolean muteBackgroundAudio();
    public boolean mutedByPortVolumeApi();
    public boolean registerVolumeCallbackApiHardening();
    public boolean ringtoneUserUriCheck();
    public boolean roForegroundAudioControl();
    public boolean roVolumeRingerApiHardening();
    public boolean routedDeviceIds();
    public boolean scoManagedByAudio();
    public boolean sony360raMpegh3dFormat();
    public boolean spatialAudioSettingsVersioning();
    public boolean spatializerCapabilities();
    public boolean speakerCleanupUsage();
    public boolean speakerLayoutApi();
    public boolean supportedDeviceTypesApi();
    public boolean unifyAbsoluteVolumeManagement();
    public boolean volumeRingerApiHardening();
}
