package com.android.server.telecom.flags;

public final class FeatureFlagsImpl implements com.android.server.telecom.flags.FeatureFlags {
    public FeatureFlagsImpl() {}
    public boolean addCallUriForMissedCalls() { return false; }
    public boolean associatedUserRefactorForWorkProfile() { return false; }
    public boolean availableRoutesNeverUpdatedAfterSetSystemAudioState() { return false; }
    public boolean businessCallComposer() { return false; }
    public boolean cacheCallAudioCallbacks() { return false; }
    public boolean callAudioCommunicationDeviceRefactor() { return false; }
    public boolean callDetailsIdChanges() { return false; }
    public boolean cancelRemovalOnEmergencyRedial() { return false; }
    public boolean clearCommunicationDeviceAfterAudioOpsComplete() { return false; }
    public boolean communicationDeviceProtectedByLock() { return false; }
    public boolean earlyBindingToIncallService() { return false; }
    public boolean earlyUpdateInternalCallAudioState() { return false; }
    public boolean eccKeyguard() { return false; }
    public boolean enableCallSequencing() { return false; }
    public boolean ensureAudioModeUpdatesOnForegroundCallChange() { return false; }
    public boolean fixAudioFlickerForOutgoingCalls() { return false; }
    public boolean genAnomReportOnFocusTimeout() { return false; }
    public boolean getLastKnownCellIdentity() { return false; }
    public boolean getRegisteredPhoneAccounts() { return false; }
    public boolean ignoreAutoRouteToWatchDevice() { return false; }
    public boolean isNewOutgoingCallBroadcastUnblocking() { return false; }
    public boolean onlyUpdateTelephonyOnValidSubIds() { return false; }
    public boolean postponeRegisterToLeaudio() { return false; }
    public boolean profileUserSupport() { return false; }
    public boolean resetMuteWhenEnteringQuiescentBtRoute() { return false; }
    public boolean resolveSwitchingBtDevicesComputation() { return false; }
    public boolean separatelyBindToBtIncallService() { return false; }
    public boolean setAudioModeBeforeAbandonFocus() { return false; }
    public boolean setMuteState() { return false; }
    public boolean setRemoteConnectionCallId() { return false; }
    public boolean skipFilterPhoneAccountPerformDndFilter() { return false; }
    public boolean telecomLogExternalWearableCalls() { return false; }
    public boolean telecomMainlineBlockedNumbersManager() { return false; }
    public boolean telecomResolveHiddenDependencies() { return false; }
    public boolean telecomSkipLogBasedOnExtra() { return false; }
    public boolean telephonyHasDefaultButTelecomDoesNot() { return false; }
    public boolean transactionalCsVerifier() { return false; }
    public boolean transactionalHoldDisconnectsUnholdable() { return false; }
    public boolean transactionalVideoState() { return false; }
    public boolean transitRouteBeforeAudioDisconnectBt() { return false; }
    public boolean unregisterUnresolvableAccounts() { return false; }
    public boolean updateRouteMaskWhenBtConnected() { return false; }
    public boolean updatedRcsCallCountTracking() { return false; }
    public boolean useActualAddressToEnterConnectingState() { return false; }
    public boolean useDeviceProvidedSerializedRingerVibration() { return false; }
    public boolean useImprovedListenerOrder() { return false; }
    public boolean useRefactoredAudioRouteSwitching() { return false; }
    public boolean voipAppActionsSupport() { return false; }
}
