package android.content.pm;

public interface FeatureFlags {
    public boolean alwaysLoadPastCertsV4();
    public boolean appCompatOption16kb();
    public boolean archiving();
    public boolean aslInApkAppMetadataSource();
    public boolean audioPlaybackCaptureAllowance();
    public boolean cacheSdkSystemFeatures();
    public boolean changeLauncherBadging();
    public boolean cloudCompilationPm();
    public boolean cloudCompilationVerification();
    public boolean disallowSdkLibsToBeApps();
    public boolean emergencyInstallPermission();
    public boolean fixDuplicatedFlags();
    public boolean getPackageInfo();
    public boolean getPackageInfoWithFd();
    public boolean getPackageStorageStats();
    public boolean getResolvedApkPath();
    public boolean improveInstallFreeze();
    public boolean includeFeatureFlagsInPackageCacher();
    public boolean introduceMediaProcessingType();
    public boolean mergePackageChangedBroadcast();
    public boolean minTargetSdk24();
    public boolean optimizeParsingInRegisteredServicesCache();
    public boolean parallelPackageParsingAcrossSystemDirs();
    public boolean protectSupervisionPackages();
    public boolean provideInfoOfApkInApex();
    public boolean quarantinedEnabled();
    public boolean readInstallInfo();
    public boolean recoverabilityDetection();
    public boolean reduceBroadcastsForComponentStateChanges();
    public boolean relativeReferenceIntentFilters();
    public boolean removeHiddenModuleUsage();
    public boolean restrictNonpreloadsSystemShareduids();
    public boolean rollbackLifetime();
    public boolean sdkDependencyInstaller();
    public boolean sdkLibIndependence();
    public boolean setPreVerifiedDomains();
    public boolean stayStopped();
    public boolean uidBasedProviderLookup();
    public boolean useArtServiceV2();
    public boolean usePiaV2();
}
