package com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags;

public class CustomFeatureFlags implements com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags {
    private java.util.function.BiFunction<java.lang.String, java.util.function.Function<com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags, ?>, ?> mGetGenericValueImpl;
    private java.util.function.BiPredicate<java.lang.String, java.util.function.Predicate<com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags>> mGetValueImpl;
    private java.util.Set<java.lang.String> mReadOnlyFlagsSet;
    public CustomFeatureFlags(java.util.function.BiPredicate<java.lang.String, java.util.function.Predicate<com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags>> p0) {}
    public CustomFeatureFlags(java.util.function.BiPredicate<java.lang.String, java.util.function.Predicate<com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags>> p0, java.util.function.BiFunction<java.lang.String, java.util.function.Function<com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags, ?>, ?> p1) {}
    private boolean isOptimizationEnabled() { return false; }
    public boolean addImsRedialCodesForEmergencyCalls() { return false; }
    public boolean addRatRelatedSuggestedActionToImsRegistration() { return false; }
    public boolean allowNonStandaloneOpportunisticAdsPolicy() { return false; }
    public boolean allowSkipPasswordValidationForCallBarring() { return false; }
    public boolean astSkyloFallback() { return false; }
    public boolean cacheSmsApplicationData() { return false; }
    public boolean cancelObsoleteDataRetryOnApnChange() { return false; }
    public boolean carrierEnabledSatelliteFlag() { return false; }
    public boolean carrierIdFromCarrierIdentifier() { return false; }
    public boolean carrierPrivilegeSegmentation() { return false; }
    public boolean carrierRestrictionStatus() { return false; }
    public boolean carrierRoamingNbIotNtn() { return false; }
    public boolean cellIdentityForBarringInfo() { return false; }
    public boolean cleanupCarrierAppUpdateEnabledStateLogic() { return false; }
    public boolean configForEnablingCarrier() { return false; }
    public boolean customizeLtePlusIcon() { return false; }
    public boolean dataOnlyCellularService() { return false; }
    public boolean dataServiceNotifyImsDataNetwork() { return false; }
    public boolean dataServiceUserDataToggleNotify() { return false; }
    public boolean deleteCdma() { return false; }
    public boolean disconnectOtherDomainCallsOnEmergencyRedial() { return false; }
    public boolean domainSelectionMetricsEnabled() { return false; }
    public boolean downloadableSubscriptionIncludeCarrierIdentifierInternal() { return false; }
    public boolean drbSecurityTransparency() { return false; }
    public boolean dsdaAdhocFiltering() { return false; }
    public boolean emergencyCallbackModeNotification() { return false; }
    public boolean emergencyMessagingRoutingForInternationalRoaming() { return false; }
    public boolean emergencyOverNrRequiresVonrEnabled() { return false; }
    public boolean emergencyRegistrationState() { return false; }
    public boolean enableAeadAlgorithms() { return false; }
    public boolean enableCarrierConfigApnStringRestriction() { return false; }
    public boolean enableDataStallRecoveryRandomization() { return false; }
    public boolean enableIsPrivateNetworkApi() { return false; }
    public boolean enableMultipleSaProposals() { return false; }
    public boolean enableNewDisplayNameApis() { return false; }
    public boolean enableOnsCleanup() { return false; }
    public boolean enableOnsTelemetry() { return false; }
    public boolean enablePhoneNumberParsingApi() { return false; }
    public boolean enableRttHoldCarrierConfig() { return false; }
    public boolean enableTrafficDescriptorConnectionCapability() { return false; }
    public boolean enableVonrProvisioningStatus() { return false; }
    public boolean enableVtCallLowBatteryConfig() { return false; }
    public boolean enableWpsCheckApiFlag() { return false; }
    public boolean enforceEmergencyExitMultiCall() { return false; }
    public boolean enforceSubscriptionUserFilter() { return false; }
    public boolean esimAvailableMemory() { return false; }
    public boolean exposeOpptAutoDataSwitchPolicies() { return false; }
    public boolean fixCsFallbackSsOnVowifi() { return false; }
    public boolean fixGetCfnryTimeWhenTimerNotSupported() { return false; }
    public boolean fixImsPdnDisconnectUponSimRemoval() { return false; }
    public boolean fixInconsistentRefreshState() { return false; }
    public boolean fixSatelliteProvisionStateOutOfSync() { return false; }
    public boolean fixSqlInjectionHbpcd() { return false; }
    public boolean geofenceEnhancementForBetterUx() { return false; }
    public java.util.List<java.lang.String> getFlagNames() { return null; }
    protected <T extends java.lang.Object> T getGenericValue(java.lang.String p0, java.util.function.Function<com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags, T> p1) { return null; }
    public boolean getPhoneNumberTs43Api() { return false; }
    public boolean getPreferredDataSubIsOpportunisticSetDataSub() { return false; }
    public boolean getServiceStateForSlot() { return false; }
    protected boolean getValue(java.lang.String p0, java.util.function.Predicate<com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags> p1) { return false; }
    public boolean hideDefaultOutgoingAccountIfNotMultiple() { return false; }
    public boolean hideNonActiveOpportunisticSubscriptions() { return false; }
    public boolean hidePrefer3gItem() { return false; }
    public boolean ignoreIncallMmiForEmergency() { return false; }
    public boolean ignoreNetworkSuggestedRetryFallback() { return false; }
    public boolean incallHandoverPolicy() { return false; }
    public boolean initRcsProvisioningMonitorAsync() { return false; }
    public boolean initializeTelecomAccountRegistryAsync() { return false; }
    public boolean isFlagReadOnlyOptimized(java.lang.String p0) { return false; }
    public boolean keepWfcOnApm() { return false; }
    public boolean key2gToggleEmergency() { return false; }
    public boolean keyCarrier2gToggle() { return false; }
    public boolean loadGidEfsEarly() { return false; }
    public boolean logCallsAnsweredElsewhere() { return false; }
    public boolean logMmsSmsDatabaseAccessInfo() { return false; }
    public boolean macroBasedOpportunisticNetworks() { return false; }
    public boolean makeMeteredUnmeteredConfigurableForSliceNetwork() { return false; }
    public boolean mccMncLocaleResolution() { return false; }
    public boolean messagePromotion() { return false; }
    public boolean mmsDisabledError() { return false; }
    public boolean networkRegistrationInfoRejectCause() { return false; }
    public boolean networkSecurityEventIndications() { return false; }
    public boolean networkValidation() { return false; }
    public boolean newSatelliteIcon() { return false; }
    public boolean newSimAuthPermission() { return false; }
    public boolean nrNtn() { return false; }
    public boolean oemEnabledSatelliteFlag() { return false; }
    public boolean oemEnabledSatellitePhase2() { return false; }
    public boolean offloadStartupBinderCalls() { return false; }
    public boolean onsHandlerThread() { return false; }
    public boolean onsThreadConsolidation() { return false; }
    public boolean passCopiedCallStateList() { return false; }
    public boolean pcscfAddress() { return false; }
    public boolean powerDownRaceFix() { return false; }
    public boolean preventDialingDuringResume() { return false; }
    public boolean propagateConferenceVideoStateToParticipants() { return false; }
    public boolean redactGenericOtpSms() { return false; }
    public boolean redactOtpSms() { return false; }
    public boolean redactOtpSmsApi() { return false; }
    public boolean redactWebotpSms() { return false; }
    public boolean refactorUiccProfileToUseCorrectCardState() { return false; }
    public boolean remapDisconnectCauseSipRequestCancelled() { return false; }
    public boolean removeTetheringConditionWhenEnablingIndications() { return false; }
    public boolean requestSignalStrength() { return false; }
    public boolean resetCarrierIdOnSimRefresh() { return false; }
    public boolean resetImsRegistrationOnInvalidSubid() { return false; }
    public boolean resetMobileNetworkSettings() { return false; }
    public boolean restrictSendUssdRequest() { return false; }
    public boolean robustNumberVerification() { return false; }
    public boolean satellite25q4Apis() { return false; }
    public boolean satellite26q2Apis() { return false; }
    public boolean satellite26q4Apis() { return false; }
    public boolean satelliteDataMetricsEnhancement() { return false; }
    public boolean satelliteExitP2pSessionOutsideGeofence() { return false; }
    public boolean satelliteImproveMultiThreadDesign() { return false; }
    public boolean satelliteMetricsEnhancement() { return false; }
    public boolean satelliteSignalHysteresisThresholds() { return false; }
    public boolean satelliteStateChangeListener() { return false; }
    public boolean satelliteSuspend() { return false; }
    public boolean satelliteSystemApis() { return false; }
    public boolean satelliteUpsell() { return false; }
    public boolean satelliteUpsell26q4() { return false; }
    public boolean secureAccessToRestrictedRcsMessages() { return false; }
    public boolean secureRemoveSubscriptionsFromGroup() { return false; }
    public boolean setCarrierRestrictionStatus() { return false; }
    public boolean simultaneousCallingIndications() { return false; }
    public boolean skipStkShortCodeCheck() { return false; }
    public boolean slicingAdditionalErrorCodes() { return false; }
    public boolean slotPortSwitchFailureFix() { return false; }
    public boolean smsNetworkSecurityEvents() { return false; }
    public boolean stkSendSmsTerminalResponseOnSendSuccess() { return false; }
    public boolean stkSmsPacking() { return false; }
    public boolean stkSmsTpMrHandling() { return false; }
    public boolean stkSmscAddressExtraction() { return false; }
    public boolean stopSpammingEmergencyNotification() { return false; }
    public boolean subscriptionPlanEnhancement() { return false; }
    public boolean subscriptionUserAssociationQuery() { return false; }
    public boolean supportAutoUnhold() { return false; }
    public boolean supportCarrierIdsInGeofence() { return false; }
    public boolean supportImsMmtelInterface() { return false; }
    public boolean supportImsRegistrationEventDownload() { return false; }
    public boolean supportImsSmsSmma() { return false; }
    public boolean supportIsimRecord() { return false; }
    public boolean supportLowBatteryAlert() { return false; }
    public boolean supportPsimToEsimConversion() { return false; }
    public boolean supportSameUriConferenceSrvcc() { return false; }
    public boolean supportSlotSwitching2psim1esimConfig() { return false; }
    public boolean supportSmsOverImsApis() { return false; }
    public boolean supportStkCommandUssdAndCall() { return false; }
    public boolean supportTargetedHoldActions() { return false; }
    public boolean supportThrottleTimeForDeregistration() { return false; }
    public boolean synchronousRcsUceCallbackRegistration() { return false; }
    public boolean systemSelectionSpecifierEnhancement() { return false; }
    public boolean telephonySatelliteApis() { return false; }
    public boolean telephonySatelliteMainlinePhase1() { return false; }
    public boolean temporaryFailuresInCarrierMessagingService() { return false; }
    public boolean updateCarrierNameAfterSimReady() { return false; }
    public boolean updateDeviceSatellitePlmnByConfigupdater() { return false; }
    public boolean useAospDomainSelectionService() { return false; }
    public boolean useEmergencyOverImsSupported3gppNetworkTypesForEmergencySmsOnNr() { return false; }
    public boolean useOemDomainSelectionService() { return false; }
    public boolean useSubscriptionManagerForPstnPhoneNumber() { return false; }
    public boolean vendorSpecificCellularIdentifierDisclosureIndications() { return false; }
    public boolean vzwAstSkyloFallback() { return false; }
    public boolean workProfileApiSplit() { return false; }
    public boolean writeSimAsync() { return false; }
}
