package com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags;

public final class FeatureFlagsImpl implements com.android.internal.hidden_from_bootclasspath.com.android.internal.telephony.flags.FeatureFlags {
    public FeatureFlagsImpl() {}
    public boolean actionSimPreferenceSettings() { return false; }
    public boolean addImsRedialCodesForEmergencyCalls() { return false; }
    public boolean addRatRelatedSuggestedActionToImsRegistration() { return false; }
    public boolean allowedServices() { return false; }
    public boolean answerAudioOnlyWhenAnsweringViaMmiCode() { return false; }
    public boolean apDomainSelectionEnabled() { return false; }
    public boolean asyncInitCarrierPrivilegesTracker() { return false; }
    public boolean autoDataPruneListener() { return false; }
    public boolean avoidDeletingImsObjectFromCache() { return false; }
    public boolean carrierEnabledSatelliteFlag() { return false; }
    public boolean carrierIdFromCarrierIdentifier() { return false; }
    public boolean carrierRestrictionStatus() { return false; }
    public boolean carrierRoamingNbIotNtn() { return false; }
    public boolean catServiceCreationFix() { return false; }
    public boolean cellularIdentifierDisclosureIndications() { return false; }
    public boolean changeMethodOfObtainingImsRegistrationRadioTech() { return false; }
    public boolean cleanupCarrierAppUpdateEnabledStateLogic() { return false; }
    public boolean cleanupCarrierNetworkChangeByPhoneid() { return false; }
    public boolean cleanupCdma() { return false; }
    public boolean clearCachedImsPhoneNumberWhenDeviceLostImsRegistration() { return false; }
    public boolean conferenceHoldUnholdChangedToSendMessage() { return false; }
    public boolean dataOnlyCellularService() { return false; }
    public boolean dataServiceCheck() { return false; }
    public boolean dataServiceNotifyImsDataNetwork() { return false; }
    public boolean dataServiceUserDataToggleNotify() { return false; }
    public boolean delayPhoneAccountRegistration() { return false; }
    public boolean deprecateCdma() { return false; }
    public boolean disableCarrierNetworkChangeOnCarrierAppLost() { return false; }
    public boolean disableEcbmBasedOnRat() { return false; }
    public boolean domainSelectionMetricsEnabled() { return false; }
    public boolean dynamicDoNotAskAgainText() { return false; }
    public boolean dynamicModemShutdown() { return false; }
    public boolean emergencyCallbackModeNotification() { return false; }
    public boolean emergencyRegistrationState() { return false; }
    public boolean enableAeadAlgorithms() { return false; }
    public boolean enableMultipleSaProposals() { return false; }
    public boolean enableSipSubscribeRetry() { return false; }
    public boolean enableWpsCheckApiFlag() { return false; }
    public boolean enforceSubscriptionUserFilter() { return false; }
    public boolean esimAvailableMemory() { return false; }
    public boolean esimBootstrapProvisioningFlag() { return false; }
    public boolean geofenceEnhancementForBetterUx() { return false; }
    public boolean getGroupIdLevel2() { return false; }
    public boolean hangupActiveCallBasedOnEmergencyCallDomain() { return false; }
    public boolean hidePrefer3gItem() { return false; }
    public boolean ignoreAlreadyTerminatedIncomingCallBeforeRegisteringListener() { return false; }
    public boolean immediatelyProcessDoNotShowAgainBroadcast() { return false; }
    public boolean imsResolverUserAware() { return false; }
    public boolean incallHandoverPolicy() { return false; }
    public boolean keepWfcOnApm() { return false; }
    public boolean logMmsSmsDatabaseAccessInfo() { return false; }
    public boolean macroBasedOpportunisticNetworks() { return false; }
    public boolean mmsDisabledError() { return false; }
    public boolean nationalCountryCodeFormattingForLocalCalls() { return false; }
    public boolean networkRegistrationInfoRejectCause() { return false; }
    public boolean networkValidation() { return false; }
    public boolean notifyInitialImsProvisioningStatus() { return false; }
    public boolean oemEnabledSatelliteFlag() { return false; }
    public boolean oemEnabledSatellitePhase2() { return false; }
    public boolean oemPaidPrivate() { return false; }
    public boolean onsThreadConsolidation() { return false; }
    public boolean optimizationApduSender() { return false; }
    public boolean passCopiedCallStateList() { return false; }
    public boolean performCrossStackRedialCheckForEmergencyCall() { return false; }
    public boolean phoneTypeCleanup() { return false; }
    public boolean powerDownRaceFix() { return false; }
    public boolean preventHangupDuringCallMerge() { return false; }
    public boolean preventInvocationRepeatOfRilCallWhenDeviceDoesNotSupportVoice() { return false; }
    public boolean preventSystemServerAndPhoneDeadlock() { return false; }
    public boolean qosUpdateNetworkAgent() { return false; }
    public boolean remapDisconnectCauseSipRequestCancelled() { return false; }
    public boolean removeCountryCodeFromLocalSingaporeCalls() { return false; }
    public boolean resetMobileNetworkSettings() { return false; }
    public boolean reuseOriginalConnRemoteConfBehavior() { return false; }
    public boolean robustNumberVerification() { return false; }
    public boolean satellite25q4Apis() { return false; }
    public boolean satelliteDataMetrics() { return false; }
    public boolean satelliteExitP2pSessionOutsideGeofence() { return false; }
    public boolean satelliteImproveMultiThreadDesign() { return false; }
    public boolean satellitePersistentLogging() { return false; }
    public boolean satelliteStateChangeListener() { return false; }
    public boolean satelliteSystemApis() { return false; }
    public boolean securityAlgorithmsUpdateIndications() { return false; }
    public boolean sendImsiKeyForDuplicateSim() { return false; }
    public boolean setCarrierRestrictionStatus() { return false; }
    public boolean setNoReplyTimerForCfnry() { return false; }
    public boolean setNumberOfSimForImsEnable() { return false; }
    public boolean simPhonebookCacheFix() { return false; }
    public boolean simultaneousCallingIndications() { return false; }
    public boolean skipMmiCodeCheckForEmergencyCall() { return false; }
    public boolean slicingAdditionalErrorCodes() { return false; }
    public boolean smsMmsDeliverBroadcastsRedirectToMainUser() { return false; }
    public boolean starlinkDataBugfix() { return false; }
    public boolean stopSpammingEmergencyNotification() { return false; }
    public boolean subscriptionPlanAllowStatusAndEndDate() { return false; }
    public boolean subscriptionUserAssociationQuery() { return false; }
    public boolean supportCarrierServicesForHsum() { return false; }
    public boolean supportImsMmtelInterface() { return false; }
    public boolean supportIsimRecord() { return false; }
    public boolean supportPsimToEsimConversion() { return false; }
    public boolean supportSmsOverImsApis() { return false; }
    public boolean temporaryFailuresInCarrierMessagingService() { return false; }
    public boolean terminateActiveVideoCallWhenAcceptingSecondVideoCallAsAudioOnly() { return false; }
    public boolean threadShred() { return false; }
    public boolean unregisterSmsBroadcastReceiverFromCatService() { return false; }
    public boolean updateImsServiceByGatheringProvisioningChanges() { return false; }
    public boolean updateResourceConfiguration() { return false; }
    public boolean updateRoamingStateToSetWfcMode() { return false; }
    public boolean useAospDomainSelectionService() { return false; }
    public boolean useCarrierConfigForCfnryTimeViaMmi() { return false; }
    public boolean useI18nForMccMapping() { return false; }
    public boolean useOemDomainSelectionService() { return false; }
    public boolean vendorSpecificCellularIdentifierDisclosureIndications() { return false; }
    public boolean workProfileApiSplit() { return false; }
}
