package com.android.internal.util.function.pooled;

public interface PooledLambda {
    public void recycle();
    public com.android.internal.util.function.pooled.PooledLambda recycleOnUse();
    public static <R extends java.lang.Object> com.android.internal.util.function.pooled.ArgumentPlaceholder<R> __() { return null; }
    public static <R extends java.lang.Object> com.android.internal.util.function.pooled.ArgumentPlaceholder<R> __(java.lang.Class<R> p0) { return null; }
    public static <R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(R p0) { return null; }
    public static com.android.internal.util.function.pooled.PooledSupplier.OfInt obtainSupplier(int p0) { return null; }
    public static com.android.internal.util.function.pooled.PooledSupplier.OfLong obtainSupplier(long p0) { return null; }
    public static com.android.internal.util.function.pooled.PooledSupplier.OfDouble obtainSupplier(double p0) { return null; }
    public static <A extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(java.util.function.Consumer<? super A> p0, A p1) { return null; }
    public static <A extends java.lang.Object> android.os.Message obtainMessage(java.util.function.Consumer<? super A> p0, A p1) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(java.util.function.BiConsumer<? super A, ? super B> p0, A p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledPredicate<A> obtainPredicate(java.util.function.BiPredicate<? super A, ? super B> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object> com.android.internal.util.function.pooled.PooledPredicate<A> obtainPredicate(com.android.internal.util.function.TriPredicate<? super A, ? super B, ? super C> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> com.android.internal.util.function.pooled.PooledPredicate<A> obtainPredicate(com.android.internal.util.function.QuadPredicate<? super A, ? super B, ? super C, ? super D> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object> com.android.internal.util.function.pooled.PooledPredicate<A> obtainPredicate(com.android.internal.util.function.QuintPredicate<? super A, ? super B, ? super C, ? super D, ? super E> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2, C p3, D p4, E p5) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledPredicate<B> obtainPredicate(java.util.function.BiPredicate<? super A, ? super B> p0, A p1, com.android.internal.util.function.pooled.ArgumentPlaceholder<B> p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> android.os.Message obtainMessage(java.util.function.BiConsumer<? super A, ? super B> p0, A p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.TriConsumer<? super A, ? super B, ? super C> p0, A p1, B p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.TriConsumer<? super A, ? super B, ? super C> p0, A p1, B p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.QuadConsumer<? super A, ? super B, ? super C, ? super D> p0, A p1, B p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.QuadConsumer<? super A, ? super B, ? super C, ? super D> p0, A p1, B p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.QuintConsumer<? super A, ? super B, ? super C, ? super D, ? super E> p0, A p1, B p2, C p3, D p4, E p5) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.QuintConsumer<? super A, ? super B, ? super C, ? super D, ? super E> p0, A p1, B p2, C p3, D p4, E p5) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.HexConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F> p0, A p1, B p2, C p3, D p4, E p5, F p6) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.HexConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F> p0, A p1, B p2, C p3, D p4, E p5, F p6) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.HeptConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.HeptConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.OctConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.OctConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.NonaConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.NonaConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object, J extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.DecConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I, ? super J> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9, J p10) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object, J extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.DecConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I, ? super J> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9, J p10) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object, J extends java.lang.Object, K extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.UndecConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I, ? super J, ? super K> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9, J p10, K p11) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object, J extends java.lang.Object, K extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.UndecConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I, ? super J, ? super K> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9, J p10, K p11) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object, J extends java.lang.Object, K extends java.lang.Object, L extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.DodecConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I, ? super J, ? super K, ? super L> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9, J p10, K p11, L p12) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object, J extends java.lang.Object, K extends java.lang.Object, L extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.DodecConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I, ? super J, ? super K, ? super L> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9, J p10, K p11, L p12) { return null; }
}
