package com.android.internal.util.function.pooled;

public interface PooledLambda {
    public void recycle();
    public com.android.internal.util.function.pooled.PooledLambda recycleOnUse();
    public static <R extends java.lang.Object> com.android.internal.util.function.pooled.ArgumentPlaceholder<R> __() { return null; }
    public static <R extends java.lang.Object> com.android.internal.util.function.pooled.ArgumentPlaceholder<R> __(java.lang.Class<R> p0) { return null; }
    public static <R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(R p0) { return null; }
    public static com.android.internal.util.function.pooled.PooledSupplier.OfInt obtainSupplier(int p0) { return null; }
    public static com.android.internal.util.function.pooled.PooledSupplier.OfLong obtainSupplier(long p0) { return null; }
    public static com.android.internal.util.function.pooled.PooledSupplier.OfDouble obtainSupplier(double p0) { return null; }
    public static <A extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(java.util.function.Consumer<? super A> p0, A p1) { return null; }
    public static <A extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<java.lang.Boolean> obtainSupplier(java.util.function.Predicate<? super A> p0, A p1) { return null; }
    public static <A extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(java.util.function.Function<? super A, ? extends R> p0, A p1) { return null; }
    public static <A extends java.lang.Object> android.os.Message obtainMessage(java.util.function.Consumer<? super A> p0, A p1) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(java.util.function.BiConsumer<? super A, ? super B> p0, A p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<java.lang.Boolean> obtainSupplier(java.util.function.BiPredicate<? super A, ? super B> p0, A p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(java.util.function.BiFunction<? super A, ? super B, ? extends R> p0, A p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<A> obtainConsumer(java.util.function.BiConsumer<? super A, ? super B> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledPredicate<A> obtainPredicate(java.util.function.BiPredicate<? super A, ? super B> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<A, R> obtainFunction(java.util.function.BiFunction<? super A, ? super B, ? extends R> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<B> obtainConsumer(java.util.function.BiConsumer<? super A, ? super B> p0, A p1, com.android.internal.util.function.pooled.ArgumentPlaceholder<B> p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> com.android.internal.util.function.pooled.PooledPredicate<B> obtainPredicate(java.util.function.BiPredicate<? super A, ? super B> p0, A p1, com.android.internal.util.function.pooled.ArgumentPlaceholder<B> p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<B, R> obtainFunction(java.util.function.BiFunction<? super A, ? super B, ? extends R> p0, A p1, com.android.internal.util.function.pooled.ArgumentPlaceholder<B> p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object> android.os.Message obtainMessage(java.util.function.BiConsumer<? super A, ? super B> p0, A p1, B p2) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.TriConsumer<? super A, ? super B, ? super C> p0, A p1, B p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(com.android.internal.util.function.TriFunction<? super A, ? super B, ? super C, ? extends R> p0, A p1, B p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<A> obtainConsumer(com.android.internal.util.function.TriConsumer<? super A, ? super B, ? super C> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<A, R> obtainFunction(com.android.internal.util.function.TriFunction<? super A, ? super B, ? super C, ? extends R> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<B> obtainConsumer(com.android.internal.util.function.TriConsumer<? super A, ? super B, ? super C> p0, A p1, com.android.internal.util.function.pooled.ArgumentPlaceholder<B> p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<B, R> obtainFunction(com.android.internal.util.function.TriFunction<? super A, ? super B, ? super C, ? extends R> p0, A p1, com.android.internal.util.function.pooled.ArgumentPlaceholder<B> p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<C> obtainConsumer(com.android.internal.util.function.TriConsumer<? super A, ? super B, ? super C> p0, A p1, B p2, com.android.internal.util.function.pooled.ArgumentPlaceholder<C> p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<C, R> obtainFunction(com.android.internal.util.function.TriFunction<? super A, ? super B, ? super C, ? extends R> p0, A p1, B p2, com.android.internal.util.function.pooled.ArgumentPlaceholder<C> p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.TriConsumer<? super A, ? super B, ? super C> p0, A p1, B p2, C p3) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.QuadConsumer<? super A, ? super B, ? super C, ? super D> p0, A p1, B p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(com.android.internal.util.function.QuadFunction<? super A, ? super B, ? super C, ? super D, ? extends R> p0, A p1, B p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<A> obtainConsumer(com.android.internal.util.function.QuadConsumer<? super A, ? super B, ? super C, ? super D> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<A, R> obtainFunction(com.android.internal.util.function.QuadFunction<? super A, ? super B, ? super C, ? super D, ? extends R> p0, com.android.internal.util.function.pooled.ArgumentPlaceholder<A> p1, B p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<B> obtainConsumer(com.android.internal.util.function.QuadConsumer<? super A, ? super B, ? super C, ? super D> p0, A p1, com.android.internal.util.function.pooled.ArgumentPlaceholder<B> p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<B, R> obtainFunction(com.android.internal.util.function.QuadFunction<? super A, ? super B, ? super C, ? super D, ? extends R> p0, A p1, com.android.internal.util.function.pooled.ArgumentPlaceholder<B> p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<C> obtainConsumer(com.android.internal.util.function.QuadConsumer<? super A, ? super B, ? super C, ? super D> p0, A p1, B p2, com.android.internal.util.function.pooled.ArgumentPlaceholder<C> p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<C, R> obtainFunction(com.android.internal.util.function.QuadFunction<? super A, ? super B, ? super C, ? super D, ? extends R> p0, A p1, B p2, com.android.internal.util.function.pooled.ArgumentPlaceholder<C> p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> com.android.internal.util.function.pooled.PooledConsumer<D> obtainConsumer(com.android.internal.util.function.QuadConsumer<? super A, ? super B, ? super C, ? super D> p0, A p1, B p2, C p3, com.android.internal.util.function.pooled.ArgumentPlaceholder<D> p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledFunction<D, R> obtainFunction(com.android.internal.util.function.QuadFunction<? super A, ? super B, ? super C, ? super D, ? extends R> p0, A p1, B p2, C p3, com.android.internal.util.function.pooled.ArgumentPlaceholder<D> p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.QuadConsumer<? super A, ? super B, ? super C, ? super D> p0, A p1, B p2, C p3, D p4) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.QuintConsumer<? super A, ? super B, ? super C, ? super D, ? super E> p0, A p1, B p2, C p3, D p4, E p5) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(com.android.internal.util.function.QuintFunction<? super A, ? super B, ? super C, ? super D, ? super E, ? extends R> p0, A p1, B p2, C p3, D p4, E p5) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.QuintConsumer<? super A, ? super B, ? super C, ? super D, ? super E> p0, A p1, B p2, C p3, D p4, E p5) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.HexConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F> p0, A p1, B p2, C p3, D p4, E p5, F p6) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(com.android.internal.util.function.HexFunction<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? extends R> p0, A p1, B p2, C p3, D p4, E p5, F p6) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.HexConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F> p0, A p1, B p2, C p3, D p4, E p5, F p6) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.HeptConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(com.android.internal.util.function.HeptFunction<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? extends R> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.HeptConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.OctConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(com.android.internal.util.function.OctFunction<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? extends R> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.OctConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object> com.android.internal.util.function.pooled.PooledRunnable obtainRunnable(com.android.internal.util.function.NonaConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object, R extends java.lang.Object> com.android.internal.util.function.pooled.PooledSupplier<R> obtainSupplier(com.android.internal.util.function.NonaFunction<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I, ? extends R> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9) { return null; }
    public static <A extends java.lang.Object, B extends java.lang.Object, C extends java.lang.Object, D extends java.lang.Object, E extends java.lang.Object, F extends java.lang.Object, G extends java.lang.Object, H extends java.lang.Object, I extends java.lang.Object> android.os.Message obtainMessage(com.android.internal.util.function.NonaConsumer<? super A, ? super B, ? super C, ? super D, ? super E, ? super F, ? super G, ? super H, ? super I> p0, A p1, B p2, C p3, D p4, E p5, F p6, G p7, H p8, I p9) { return null; }
}
