package android.view.flags;

public interface FeatureFlags {
    public boolean addSchandleToVriSurface();
    public boolean bufferStuffingRecovery();
    public boolean customizableWindowHeaders();
    public boolean deprecateSurfaceViewZOrderApis();
    public boolean disableDrawWakeLock();
    public boolean dynamicViewRotaryHapticsConfiguration();
    public boolean enableArrowIconOnHoverWhenClickable();
    public boolean enableDispatchOnScrollChanged();
    public boolean enableInvalidateCheckThread();
    public boolean enableScrollFeedbackForTouch();
    public boolean enableSurfaceNativeAllocRegistrationRo();
    public boolean enableUseMeasureCacheDuringForceLayout();
    public boolean enableVectorCursorA11ySettings();
    public boolean enableVectorCursors();
    public boolean expectedPresentationTimeApi();
    public boolean expectedPresentationTimeReadOnly();
    public boolean notifyGpuLoadUp();
    public boolean rootViewChangedListener();
    public boolean scrollCaptureRelaxScrollViewCriteria();
    public boolean scrollCaptureTargetZOrderFix();
    public boolean scrollFeedbackApi();
    public boolean sensitiveContentAppProtection();
    public boolean sensitiveContentAppProtectionApi();
    public boolean sensitiveContentPrematureProtectionRemovedFix();
    public boolean setFrameRateCallback();
    public boolean surfaceViewGetSurfacePackage();
    public boolean surfaceViewSetCompositionOrder();
    public boolean toolkitFrameRateBySizeReadOnly();
    public boolean toolkitFrameRateDebug();
    public boolean toolkitFrameRateTouchBoost25q1();
    public boolean toolkitInitialTouchBoost();
    public boolean toolkitMetricsForFrameRateDecision();
    public boolean toolkitSetFrameRate();
    public boolean toolkitSetFrameRateReadOnly();
    public boolean toolkitVelocityMapSysprop();
    public boolean toolkitViewgroupSetRequestedFrameRateApi();
    public boolean useRefactoredRoundScrollbar();
    public boolean useViewBasedRotaryEncoderScrollHaptics();
    public boolean viewVelocityApi();
}
